[package]
  name = "windows_targets"
  version = "0.1.0"
  description = "Windows import archive carrier for Cangjie"
  output-type = "static"
  cjc-version = "1.1.0"
  compile-option = "-Woff unused"
