from __future__ import annotations

import subprocess
import tempfile
import unittest
from pathlib import Path

import embed_winmd_resources as embed


def write_required_winmd_files(root: Path) -> Path:
    winmd_dir = root / "winmd"
    winmd_dir.mkdir(parents=True, exist_ok=True)
    for name, resource_id in embed.WINMD_RESOURCE_IDS:
        (winmd_dir / name).write_bytes(f"{name}:{resource_id}".encode("utf-8"))
    return winmd_dir


class EmbedWinmdResourceScriptTests(unittest.TestCase):
    def test_python_and_cangjie_resource_manifests_stay_aligned(self) -> None:
        repo_root = Path(__file__).resolve().parents[3]
        cangjie_source = (repo_root / "windows_bindgen" / "src" / "embedded_winmd.cj").read_text(encoding="utf-8")

        for name, resource_id in embed.WINMD_RESOURCE_IDS:
            self.assertIn(f'"{name}"', cangjie_source)
            self.assertIn(str(resource_id), cangjie_source)

    def test_resource_script_uses_stable_integer_ids(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            winmd_dir = write_required_winmd_files(root)

            text = embed.resource_script_text(winmd_dir)

            self.assertIn("1000 RCDATA", text)
            self.assertIn("1008 RCDATA", text)
            self.assertIn("Microsoft.Foundation.winmd", text)
            self.assertIn("Windows.winmd", text)

    def test_generate_resource_object_invokes_windres(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            write_required_winmd_files(root)
            commands: list[list[str]] = []

            def fake_run(command, **_kwargs):
                commands.append(command)
                return subprocess.CompletedProcess(command, 0)

            resource = embed.generate_resource_object(root, resource_compiler="windres", run=fake_run)

            self.assertEqual(commands, [["windres", "-O", "coff", str(resource.rc_path), "-o", str(resource.obj_path)]])
            self.assertTrue(resource.rc_path.read_text(encoding="utf-8").startswith("// Generated by"))
            self.assertEqual(resource.obj_path.name, "winmd_resources.obj")

    def test_build_temporarily_injects_link_option_and_restores_toml(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            write_required_winmd_files(root)
            package_dir = root / "windows_bindgen"
            package_dir.mkdir(parents=True)
            original_toml = (
                "[package]\n"
                '  name = "windows_bindgen"\n'
                '  output-type = "executable"\n'
                '  compile-option = "-Woff unused"\n'
            )
            (package_dir / "cjpm.toml").write_text(original_toml, encoding="utf-8")
            build_envs: list[dict[str, str]] = []

            def fake_run(command, **kwargs):
                if command[0] == "windres":
                    return subprocess.CompletedProcess(command, 0)
                if command == ["cjpm", "build", "-m", "windows_bindgen"]:
                    build_envs.append(kwargs["env"])
                    patched = (package_dir / "cjpm.toml").read_text(encoding="utf-8")
                    self.assertIn("link-option", patched)
                    self.assertIn("winmd_resources.obj", patched)
                    return subprocess.CompletedProcess(command, 0)
                raise AssertionError(f"unexpected command: {command}")

            embed.build_windows_bindgen_with_embedded_winmd(root, resource_compiler="windres", run=fake_run)

            self.assertEqual((package_dir / "cjpm.toml").read_text(encoding="utf-8"), original_toml)
            self.assertEqual(build_envs[0]["cjHeapSize"], "32GB")

    def test_inject_link_option_refuses_existing_manual_link_option(self) -> None:
        with self.assertRaises(RuntimeError):
            embed.inject_link_option('[package]\n  link-option = "manual.obj"\n', "generated.obj")


if __name__ == "__main__":
    unittest.main()
