[package]
  name = "windows_sample_com_uri"
  version = "0.1.0"
  description = "Create an IUri via CreateUri and print its domain and port"
  authors = ["Zxilly"]
  repository = "https://github.com/Zxilly/windows-cj"
  license = ["MIT"]
  output-type = "executable"
  cjc-version = "1.1.0"
  compile-option = "--experimental --incremental-compile -Woff unused"

[dependencies]
  windows_sample_com_uri_bindings = { path = "./bindings" }
  windows_strings = { path = "../../../windows_strings" }
  windows_core = { path = "../../../windows_core" }
