#!/usr/bin/env python3
"""Audit Cangjie @C ABI declarations.

Generated projections must carry the windows-bindgen sentinel. Hand-authored
runtime ABI is allowed only for the exact symbols listed below.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parent
GENERATED_SENTINEL = "// Auto-generated by windows-bindgen. Do not edit."
DECL_RE = re.compile(r"\b(struct|class|func)\s+([A-Za-z_][A-Za-z0-9_]*)")

RUNTIME_ABI: dict[str, tuple[str, set[str]]] = {
    "windows/src/callbacks.cj": (
        "Win32 callback thunks for user closures",
        {"func enumWindowsThunk", "func timerProcThunk", "func wndProcThunk"},
    ),
    "windows-core/src/agile_reference.cj": (
        "IAgileReference runtime thunk",
        {"func agileReferenceResolveThunk"},
    ),
    "windows-core/src/generic_factory.cj": (
        "WinRT activation factory vtable used by core",
        {"struct IGenericFactoryVtbl"},
    ),
    "windows-core/src/inspectable.cj": (
        "IInspectable runtime thunks",
        {
            "func iinspectableGetIidsThunk",
            "func iinspectableGetRuntimeClassNameThunk",
            "func iinspectableGetTrustLevelThunk",
        },
    ),
    "windows-core/src/marshaler.cj": (
        "aggregated IMarshal runtime thunks",
        {
            "func aggregatedMarshalerQueryInterfaceThunk",
            "func aggregatedMarshalerAddRefThunk",
            "func aggregatedMarshalerReleaseThunk",
            "func aggregatedMarshalerGetUnmarshalClassThunk",
            "func aggregatedMarshalerGetMarshalSizeMaxThunk",
            "func aggregatedMarshalerMarshalInterfaceThunk",
            "func aggregatedMarshalerUnmarshalInterfaceThunk",
            "func aggregatedMarshalerReleaseMarshalDataThunk",
            "func aggregatedMarshalerDisconnectObjectThunk",
        },
    ),
    "windows-core/src/weak.cj": (
        "IWeakReference core helper thunks",
        {"func weakReferenceResolveThunk", "func weakReferenceSourceGetWeakReferenceThunk"},
    ),
    "windows-core/src/weak_ref_count.cj": (
        "local weak reference tear-off thunks",
        {
            "func localWeakReferenceSourceQueryInterfaceThunk",
            "func localWeakReferenceSourceAddRefThunk",
            "func localWeakReferenceSourceReleaseThunk",
            "func localWeakReferenceSourceGetWeakReferenceThunk",
            "func localWeakReferenceQueryInterfaceThunk",
            "func localWeakReferenceAddRefThunk",
            "func localWeakReferenceReleaseThunk",
            "func localWeakReferenceResolveThunk",
        },
    ),
    "windows-implement/src/com_box.cj": (
        "COM object slot header",
        {"struct ComBox"},
    ),
    "windows-implement/src/thunk_builder.cj": (
        "IUnknown/IInspectable implementation thunks",
        {
            "func iunknownQueryInterfaceThunk",
            "func iunknownAddRefThunk",
            "func iunknownReleaseThunk",
            "func iinspectableGetIidsThunk",
            "func iinspectableGetRuntimeClassNameThunk",
            "func iinspectableGetTrustLevelThunk",
        },
    ),
    "windows-implement/src/weak_ref_count.cj": (
        "implementation weak reference tear-off thunks",
        {
            "func weakReferenceSourceQueryInterfaceThunk",
            "func weakReferenceSourceAddRefThunk",
            "func weakReferenceSourceReleaseThunk",
            "func weakReferenceSourceGetWeakReferenceThunk",
            "func weakReferenceQueryInterfaceThunk",
            "func weakReferenceAddRefThunk",
            "func weakReferenceReleaseThunk",
            "func weakReferenceResolveThunk",
        },
    ),
    "windows-interface/src/guid.cj": (
        "base COM GUID ABI",
        {"struct GUID"},
    ),
    "windows-interface/src/interface_wrapper.cj": (
        "base COM/WinRT support vtables",
        {
            "struct IUnknownVtbl",
            "struct IInspectableVtbl",
            "struct IAgileObjectVtbl",
            "struct IAgileReferenceVtbl",
            "struct IMarshalVtbl",
            "struct IWeakReferenceVtbl",
            "struct IWeakReferenceSourceVtbl",
            "struct IActivationFactoryVtbl",
        },
    ),
    "windows-registry/src/lib.cj": (
        "registry FILETIME ABI",
        {"struct FILETIME"},
    ),
    "windows-result/src/bindings.cj": (
        "error COM ABI bindings",
        {
            "struct UInt128",
            "struct GUID",
            "struct IUnknown",
            "struct IErrorInfo",
            "struct IRestrictedErrorInfo",
            "struct IUnknownVtbl",
            "struct IErrorInfoVtbl",
            "struct IRestrictedErrorInfoVtbl",
        },
    ),
    "windows-result/src/internal_test.cj": (
        "test-only fake COM ABI",
        {
            "struct FakeIdentityInterface",
            "func fakeIdentityQueryInterface",
            "func fakeIdentityAddRef",
            "func fakeIdentityRelease",
            "struct FakeErrorInfo",
            "struct FakeRestrictedErrorInfo",
            "func fakeErrorInfoQueryInterface",
            "func fakeErrorInfoAddRef",
            "func fakeErrorInfoRelease",
            "func fakeGetDescription",
            "func fakeGetErrorDetails",
            "func fakeGetReference",
        },
    ),
    "windows-result/src/ntstatus.cj": ("status code ABI newtype", {"struct NTSTATUS"}),
    "windows-result/src/rpc_status.cj": ("status code ABI newtype", {"struct RPC_STATUS"}),
    "windows-result/src/win32_error.cj": ("status code ABI newtype", {"struct WIN32_ERROR"}),
    "windows-services/src/lib.cj": (
        "service control manager structs and thunks",
        {
            "struct SERVICE_STATUS",
            "struct SERVICE_TABLE_ENTRYW",
            "func serviceMainThunk",
            "func handlerThunk",
        },
    ),
    "windows-strings/src/ref_count.cj": (
        "HSTRING header ABI",
        {"struct HStringHeader"},
    ),
    "windows-threading/src/lib.cj": (
        "threadpool callback environment and thunk",
        {"struct TP_CALLBACK_ENVIRON_V3", "func taskThunk"},
    ),
    "windows-version/src/lib.cj": (
        "version information ABI",
        {"struct OSVERSIONINFOEXW"},
    ),
}


RUST_BOUNDARY: dict[str, tuple[str, str]] = {
    "windows/src/callbacks.cj": (
        "projection-extension-thunk",
        "Rust windows has hand-written extensions under crates/libs/windows/src/extensions, but no repr(C) callback thunk analog.",
    ),
    "windows-core/src/agile_reference.cj": (
        "core-runtime",
        "Rust: crates/libs/core/src/agile_reference.rs + imp/com_bindings.rs",
    ),
    "windows-core/src/generic_factory.cj": (
        "core-runtime",
        "Rust: crates/libs/core/src/imp/generic_factory.rs",
    ),
    "windows-core/src/inspectable.cj": (
        "core-runtime",
        "Rust: crates/libs/core/src/inspectable.rs",
    ),
    "windows-core/src/marshaler.cj": (
        "core-runtime",
        "Rust: crates/libs/core/src/imp/marshaler.rs",
    ),
    "windows-core/src/weak.cj": (
        "core-runtime",
        "Rust: crates/libs/core/src/weak.rs + imp/com_bindings.rs",
    ),
    "windows-core/src/weak_ref_count.cj": (
        "core-runtime",
        "Rust: crates/libs/core/src/imp/weak_ref_count.rs",
    ),
    "windows-implement/src/com_box.cj": (
        "implement-runtime",
        "Rust: crates/libs/implement/src/gen.rs emits repr(C) implementation object layout",
    ),
    "windows-implement/src/thunk_builder.cj": (
        "implement-runtime",
        "Rust: crates/libs/core/src/unknown.rs and inspectable.rs vtable thunk constructors",
    ),
    "windows-implement/src/weak_ref_count.cj": (
        "implement-runtime",
        "Rust: crates/libs/core/src/imp/weak_ref_count.rs",
    ),
    "windows-interface/src/guid.cj": (
        "base-com-runtime",
        "Rust: crates/libs/core/src/guid.rs",
    ),
    "windows-interface/src/interface_wrapper.cj": (
        "base-com-runtime",
        "Rust: crates/libs/core/src/unknown.rs, inspectable.rs, imp/com_bindings.rs, imp/marshaler.rs, imp/generic_factory.rs",
    ),
    "windows-registry/src/lib.cj": (
        "support-binding",
        "Rust: crates/libs/registry/src/bindings.rs",
    ),
    "windows-result/src/bindings.cj": (
        "support-binding",
        "Rust: crates/libs/result/src/bindings.rs",
    ),
    "windows-result/src/internal_test.cj": (
        "test-only",
        "Rust: test-only fake COM layouts are not part of public ABI",
    ),
    "windows-result/src/ntstatus.cj": (
        "support-binding",
        "Rust: crates/libs/result/src/bindings.rs exposes NTSTATUS as an ABI status type",
    ),
    "windows-result/src/rpc_status.cj": (
        "support-binding",
        "Rust: crates/libs/core/src/imp/bindings.rs exposes RPC_STATUS as an ABI status type",
    ),
    "windows-result/src/win32_error.cj": (
        "support-binding",
        "Rust: crates/libs/result/src/bindings.rs exposes WIN32_ERROR as an ABI status type",
    ),
    "windows-services/src/lib.cj": (
        "support-binding-and-thunk",
        "Rust: crates/libs/services/src/bindings.rs; Cangjie adds service callback thunks for closure dispatch",
    ),
    "windows-strings/src/ref_count.cj": (
        "core-string-runtime",
        "Rust: crates/libs/strings/src/hstring_header.rs",
    ),
    "windows-threading/src/lib.cj": (
        "support-binding-and-thunk",
        "Rust: crates/libs/threading/src/bindings.rs; Cangjie adds task thunk for closure dispatch",
    ),
    "windows-version/src/lib.cj": (
        "support-binding",
        "Rust: crates/libs/version/src/bindings.rs",
    ),
}


@dataclass(frozen=True)
class CAbiDecl:
    path: Path
    line: int
    symbol: str
    declaration: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Audit ownership of Cangjie @C declarations.")
    parser.add_argument("--verbose", action="store_true", help="Print allowed hand-authored ABI declarations.")
    return parser.parse_args()


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def is_generated(lines: list[str]) -> bool:
    return any(line.strip() == GENERATED_SENTINEL for line in lines[:5])


def declaration_after(lines: list[str], index: int) -> str:
    for line in lines[index + 1 : index + 8]:
        stripped = line.strip()
        if not stripped or stripped.startswith("//") or stripped.startswith("@"):
            continue
        return stripped
    return "<missing declaration>"


def symbol_for(declaration: str) -> str:
    match = DECL_RE.search(declaration)
    if not match:
        return "<unknown>"
    return f"{match.group(1)} {match.group(2)}"


def iter_source_files() -> list[Path]:
    ignored = {".git", "target"}
    return sorted(
        path
        for path in ROOT.rglob("*.cj")
        if not any(part in ignored for part in path.relative_to(ROOT).parts)
    )


def find_decls(path: Path) -> tuple[bool, list[CAbiDecl]]:
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    decls: list[CAbiDecl] = []
    for index, line in enumerate(lines):
        if line.strip() != "@C":
            continue
        declaration = declaration_after(lines, index)
        decls.append(CAbiDecl(path, index + 1, symbol_for(declaration), declaration))
    return is_generated(lines), decls


def main() -> None:
    args = parse_args()
    violations: list[CAbiDecl] = []
    generated_files = 0
    runtime_decls: list[tuple[CAbiDecl, str]] = []
    missing_boundary = sorted(set(RUNTIME_ABI) - set(RUST_BOUNDARY))
    stale_boundary = sorted(set(RUST_BOUNDARY) - set(RUNTIME_ABI))

    if missing_boundary or stale_boundary:
        print("C ABI audit configuration is inconsistent.", file=sys.stderr)
        for path in missing_boundary:
            print(f"  missing Rust boundary: {path}", file=sys.stderr)
        for path in stale_boundary:
            print(f"  stale Rust boundary: {path}", file=sys.stderr)
        sys.exit(1)

    for path in iter_source_files():
        generated, decls = find_decls(path)
        if not decls:
            continue
        if generated:
            generated_files += 1
            continue

        rel_path = rel(path)
        allowed = RUNTIME_ABI.get(rel_path)
        allowed_symbols = allowed[1] if allowed else set()
        reason = allowed[0] if allowed else ""

        for decl in decls:
            if decl.symbol in allowed_symbols:
                runtime_decls.append((decl, reason))
            else:
                violations.append(decl)

    if violations:
        print("C ABI audit failed: unexpected hand-authored @C declarations.", file=sys.stderr)
        print("Generated files must start with:", file=sys.stderr)
        print(f"  {GENERATED_SENTINEL}", file=sys.stderr)
        print("Runtime-owned ABI must be listed in RUNTIME_ABI.", file=sys.stderr)
        for decl in violations:
            print(f"  {rel(decl.path)}:{decl.line}: {decl.symbol} :: {decl.declaration}", file=sys.stderr)
        sys.exit(1)

    boundary_counts: dict[str, int] = {}
    for decl, _ in runtime_decls:
        category = RUST_BOUNDARY[rel(decl.path)][0]
        boundary_counts[category] = boundary_counts.get(category, 0) + 1

    print("C ABI audit passed.")
    print(f"  generated @C files: {generated_files}")
    print(f"  hand-authored @C declarations: {len(runtime_decls)}")
    print(f"  hand-authored @C files: {len({decl.path for decl, _ in runtime_decls})}")
    for category, count in sorted(boundary_counts.items()):
        print(f"  {category}: {count}")

    if args.verbose:
        for decl, reason in runtime_decls:
            category, rust_source = RUST_BOUNDARY[rel(decl.path)]
            print(f"  {rel(decl.path)}:{decl.line}: {decl.symbol} ({category}; {reason}; {rust_source})")


if __name__ == "__main__":
    main()
