[workspace]
members = [
    "windows_libloading",
    "windows_result",
    "windows_strings",
    "windows_interface",
    "windows_implement",
    "windows_core",
    "windows_polyfill",
    "windows_foundation",
    "windows_collections",
    "windows_future",
    "windows_time",
    "windows_reference",
    "windows_threading",
    "windows_version",
    "windows_numerics",
    "windows_variant",
    "windows_propvariant",
    "windows_safearray",
    "windows_targets",
    "windows_registry",
    "windows_services",
    "windows_common",
    "windows_reactor",
    "samples/reactor/windows_reactor_gallery",
    "samples/reactor/windows_reactor_minimal",
    "samples/reactor/windows_reactor_apps",
    "samples/windows/enum_windows/bindings",
    "samples/windows/enum_windows",
    "samples/windows/com_uri/bindings",
    "samples/windows/com_uri",
    "samples/windows/credentials/bindings",
    "samples/windows/credentials",
    "samples/windows/kernel_event/bindings",
    "samples/windows/kernel_event",
    "samples/windows/thread_pool_work/bindings",
    "samples/windows/thread_pool_work",
    "samples/windows/simple/bindings",
    "samples/windows/simple",
    "samples/windows/xml/bindings",
    "samples/windows/xml",
    "samples/windows/privileges/bindings",
    "samples/windows/privileges",
    "samples/windows/message_box/bindings",
    "samples/windows/message_box",
    "samples/windows/overlapped/bindings",
    "samples/windows/overlapped",
    "samples/windows/memory_buffer/bindings",
    "samples/windows/memory_buffer",
    "samples/windows/spellchecker/bindings",
    "samples/windows/spellchecker",
    "samples/windows/shell/bindings",
    "samples/windows/shell",
    "samples/windows/create_window/bindings",
    "samples/windows/create_window",
    "samples/windows/counter/bindings",
    "samples/windows/counter",
    "samples/windows/file_dialogs/bindings",
    "samples/windows/file_dialogs",
    "samples/windows/task_dialog/bindings",
    "samples/windows/task_dialog",
    "samples/windows/device_watcher/bindings",
    "samples/windows/device_watcher",
    "samples/windows/consent/bindings",
    "samples/windows/consent",
    "samples/windows/data_protection/bindings",
    "samples/windows/data_protection",
    "samples/windows/wmi/bindings",
    "samples/windows/wmi",
    "samples/windows/uiautomation/bindings",
    "samples/windows/uiautomation",
    "samples/windows/ocr/bindings",
    "samples/windows/ocr",
    "samples/windows/rss/bindings",
    "samples/windows/rss",
    "samples/services/simple",
    "samples/services/time/bindings",
    "samples/services/time",
    "samples/windows/bits/bindings",
    "samples/windows/bits",
    "samples/windows/core_app/bindings",
    "samples/windows/core_app",
    "samples/windows/xaml_app/bindings",
    "samples/windows/xaml_app",
    "samples/windows/direct2d/bindings",
    "samples/windows/direct2d",
    "samples/windows/direct3d12/bindings",
    "samples/windows/direct3d12",
    "samples/windows/dcomp/bindings",
    "samples/windows/dcomp",
    "windows_bindgen"
]
