[workspace]
members = [
    "windows-metadata",
    "windows-bindgen",
    "windows-sync",
    "windows-sys",
    "windows-result",
    "windows-strings",
    "windows-interface",
    "windows-implement",
    "windows-core",
    "windows-polyfill",
    "windows"
]

compile-option = "--cfg ./windows-cj"

[windows-cj]
features = []
