[workspace]
members = [
    "windows-libloading",
    "windows-result",
    "windows-strings",
    "windows-interface",
    "windows-implement",
    "windows-core",
    "windows-polyfill",
    "windows-runtime",
    "windows-threading",
    "windows-version",
    "windows-numerics",
    "windows-variant",
    "windows-targets",
    "windows-registry",
    "windows-services",
    "windows-common",
    "windows-winui3",
    "windows"
]
