[package]
  name = "windows_sample_device_watcher"
  version = "0.1.0"
  description = "Watch device enumeration via DeviceWatcher and WinRT TypedEventHandler delegates"
  output-type = "executable"
  cjc-version = "1.1.0"
  compile-option = "-Woff unused"

[dependencies]
  windows_sample_device_watcher_bindings = { path = "./bindings" }
  windows_core = { path = "../../../windows_core" }
  windows_interface = { path = "../../../windows_interface" }
