[package]
  name = "windows_sample_uiautomation"
  version = "0.1.0"
  description = "Read a window's UI Automation name and WinRT ExecutableFileName"
  authors = ["Zxilly"]
  repository = "https://github.com/Zxilly/windows-cj"
  license = ["MIT"]
  output-type = "executable"
  cjc-version = "1.1.0"
  compile-option = "-Woff unused"

[dependencies]
  windows_sample_uiautomation_bindings = { path = "./bindings" }
  windows_core = { path = "../../../windows_core" }
  windows_strings = { path = "../../../windows_strings" }
  windows_interface = { path = "../../../windows_interface" }
