[package]
  name = "windows_sample_xml"
  version = "0.1.0"
  description = "Activate the XmlDocument WinRT class, LoadXml a string, read DocumentElement NodeName + InnerText"
  authors = ["Zxilly"]
  repository = "https://github.com/Zxilly/windows-cj"
  license = ["MIT"]
  output-type = "executable"
  cjc-version = "1.1.0"
  compile-option = "-Woff unused"

[dependencies]
  windows_sample_xml_bindings = { path = "./bindings" }
  windows_core = { path = "../../../windows_core" }
