[package]
  name = "windows_webview2_sys"
  version = "0.1.0"
  description = "Raw FFI bindings for Microsoft WebView2 APIs for Cangjie"
  output-type = "static"
  cjc-version = "1.1.0"
  compile-option = "--cfg . -Woff unused -Woff parser -Woff package-import --profile-compile-time"

[dependencies]
  windows_core = { path = "../windows-core" }
  windows_interface = { path = "../windows-interface" }
  windows_libloading = { path = "../windows-libloading" }
  windows_polyfill = { path = "../windows-polyfill" }
  windows_result = { path = "../windows-result" }
  windows_strings = { path = "../windows-strings" }
  windows_sys = { path = "../windows-sys" }
