$ErrorActionPreference = "Stop"

$repoRoot = "E:/Project/CS_Project/2026/ling"
$packageRoot = Join-Path $repoRoot "windows-cj/windows-bindgen"
$fixtureWin32 = Join-Path $repoRoot "ref/windows-rs/crates/libs/bindgen/default/Windows.Win32.winmd"
$fixtureWinrt = Join-Path $repoRoot "ref/windows-rs/crates/libs/bindgen/default/Windows.winmd"
$outputRoot = Join-Path $packageRoot "tests/output/p1_p2_architecture"
$highLevelOut = Join-Path $outputRoot "high_level"
$sysOut = Join-Path $outputRoot "sys"

if (!(Test-Path $fixtureWin32)) {
    throw "Missing fixture winmd: $fixtureWin32"
}
if (!(Test-Path $fixtureWinrt)) {
    throw "Missing fixture winmd: $fixtureWinrt"
}

if (Test-Path $outputRoot) {
    Remove-Item -Recurse -Force $outputRoot
}
New-Item -ItemType Directory -Force $outputRoot | Out-Null

Push-Location $packageRoot
try {
    cjpm build | Out-Host

    cjpm run -- `
        --in $fixtureWinrt `
        --out $highLevelOut `
        --flat `
        --no-sys `
        --high-level `
        --index `
        --link windows_link `
        --rustfmt rustfmt `
        --no-comment `
        --no-allow `
        --filter Windows.Foundation.Collections `
        --filter Windows.Foundation | Out-Host

    cjpm run -- `
        --in $fixtureWin32 `
        --out $sysOut `
        --flat `
        --sys `
        --link windows_link `
        --sys-fn-ptrs `
        --filter Windows.Win32.System.SystemInformation | Out-Host
}
finally {
    Pop-Location
}

$collectionsFile = Join-Path $highLevelOut "collections.cj"
$foundationFile = Join-Path $highLevelOut "foundation.cj"
$featuresIndexFile = Join-Path $highLevelOut "features.json"
$librariesFile = Join-Path $highLevelOut "libraries.cj"
$sysFile = Join-Path $sysOut "system_information.cj"
$sysLibrariesFile = Join-Path $sysOut "libraries.cj"

foreach ($path in @($collectionsFile, $foundationFile, $featuresIndexFile, $librariesFile, $sysFile, $sysLibrariesFile)) {
    if (!(Test-Path $path)) {
        throw "Missing generated artifact: $path"
    }
}

$collections = Get-Content -Raw $collectionsFile
$foundation = Get-Content -Raw $foundationFile
$featuresIndex = Get-Content -Raw $featuresIndexFile
$libraries = Get-Content -Raw $librariesFile
$sys = Get-Content -Raw $sysFile
$sysLibraries = Get-Content -Raw $sysLibrariesFile

if ($foundation -match '(?m)^// Auto-generated by windows-bindgen') {
    throw "--no-comment should suppress the generated source banner"
}

if ($collections -notmatch 'public class IIteratorIterator<T> <: Iterator<T>') {
    throw "IIterator projection is missing Iterator adapter support"
}
if ($collections -notmatch 'public func intoIterator\(\): Iterator<T>') {
    throw "IIterable projection is missing intoIterator support"
}
if ($collections -notmatch 'public func iterator\(\): Iterator<T>') {
    throw "IIterable projection is missing Iterable support"
}
if ($foundation -notmatch 'public func iterator\(\): Iterator<') {
    throw "WinRT classes implementing IIterable are missing iterator projection methods"
}

if ($featuresIndex -notmatch '"version"\s*:\s*2') {
    throw "features.json is missing the expected index version"
}
if ($featuresIndex -notmatch '"Windows\.Foundation"') {
    throw "features.json is missing namespace index entries"
}

if ($libraries -notmatch '(?m)^public let defaultLinkPackage: String = "windows_link"$') {
    throw "libraries.cj is missing the configured link package surface"
}
if ($sysLibraries -notmatch '(?m)^public let defaultLinkPackage: String = "windows_link"$') {
    throw "sys libraries.cj is missing the configured link package surface"
}
if ($sysLibraries -notmatch 'kernel32') {
    throw "sys libraries.cj is missing collected library names"
}

if ($sys -notmatch 'public type GetTickCountFn = CFunc<\(\) -> UInt32>') {
    throw "--sys-fn-ptrs should emit function pointer aliases for sys bindings"
}

Write-Host "windows-bindgen P1/P2 architecture smoke test passed."
