[package]
  name = "windows_sync"
  version = "0.1.0"
  description = "Windows feature sync tool for Cangjie"
  output-type = "executable"
  cjc-version = "1.1.0"

[target]
  [target.x86_64-w64-mingw32]
    [target.x86_64-w64-mingw32.bin-dependencies]
      path-option = ["C:/Users/Admin/.cjv/toolchains/nightly-1.1.0-alpha.20260330010029/modules/windows_x86_64_cjnative/std"]
