[package]
  name = "windows_services"
  version = "0.1.0"
  description = "Windows service helpers for Cangjie bindings"
  authors = ["Zxilly"]
  repository = "https://github.com/Zxilly/windows-cj"
  license = []
  output-type = "static"
  cjc-version = "1.1.0"
  compile-option = "-Woff unused"

[dependencies]
  windows_common = { path = "../windows_common" }
  windows_strings = { path = "../windows_strings" }
