[package]
  name = "windows_core"
  version = "0.1.0"
  description = "Core runtime types for Windows API bindings in Cangjie"
  authors = ["Zxilly"]
  repository = "https://github.com/Zxilly/windows-cj"
  license = []
  output-type = "static"
  cjc-version = "1.1.0"
  compile-option = "-Woff unused"

[dependencies]
  windows_libloading = { path = "../windows_libloading" }
  windows_result = { path = "../windows_result" }
  windows_strings = { path = "../windows_strings" }
  windows_interface = { path = "../windows_interface" }
  windows_implement = { path = "../windows_implement" }
