[package]
  name = "windows_bindgen"
  version = "0.1.0"
  description = "Windows metadata bindgen CLI for Cangjie"
  authors = ["Zxilly"]
  repository = "https://github.com/Zxilly/windows-cj"
  license = ["MIT"]
  output-type = "executable"
  cjc-version = "1.1.0"
  compile-option = "-Woff unused"

[dependencies]

[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["${CANGJIE_STDX_PATH_STATIC}/stdx"]
