[package]
  name = "windows_result"
  version = "0.1.0"
  description = "Result and status-code primitives for Windows bindings in Cangjie"
  output-type = "static"
  cjc-version = "1.1.0"
  compile-option = "-loleaut32 -lwindowsapp"

[dependencies]

[profile.customized-option]
  slim = "--cfg=\"slim_errors=true\""
