#!/usr/bin/env python3
"""Verify the active windows-cj workspace layout.

This script intentionally checks the current JSON-backed Cangjie generator
layout. Legacy cfg-era and Python bindgen packages must live outside this
workspace under the sibling deprecated_windows_cj directory.
"""

from __future__ import annotations

import sys
import subprocess
import tomllib
import ast
import hashlib
import json
import re
from pathlib import Path


ACTIVE_WORKSPACE_MEMBERS = {
    "windows-libloading",
    "windows-result",
    "windows-strings",
    "windows-interface",
    "windows-implement",
    "windows-core",
    "windows-polyfill",
    "windows-runtime",
    "windows-threading",
    "windows-version",
    "windows-numerics",
    "windows-variant",
    "windows-propvariant",
    "windows-safearray",
    "windows-targets",
    "windows-registry",
    "windows-services",
    "windows-common",
    "windows-projection",
    "windows-winui3",
    "windows-bindgen",
}

REFERENCE_ONLY_PACKAGES = {
    "windows-sys",
    "windows-webview2-sys",
    "windows-appsdk-sys",
    "windows-webview2",
    "windows-appsdk",
    "windows-bindgen-legacy",
    "windows-cfggen",
    "windows-cfggen-legacy",
    "windows-cj-bindgen-py",
    "windows-cj-cfggen-py",
}

PACKAGE_DEPENDENCIES = {
    "windows_bindgen": set(),
    "windows_common": {
        "windows_core",
        "windows_interface",
        "windows_libloading",
        "windows_polyfill",
        "windows_strings",
    },
    "windows_core": {
        "windows_implement",
        "windows_interface",
        "windows_libloading",
        "windows_result",
        "windows_strings",
    },
    "windows_implement": {
        "windows_interface",
        "windows_libloading",
        "windows_result",
        "windows_strings",
    },
    "windows_interface": {
        "windows_result",
        "windows_strings",
    },
    "windows_libloading": set(),
    "windows_numerics": {"windows_common"},
    "windows_polyfill": set(),
    "windows_projection": {
        "windows_common",
    },
    "windows_propvariant": {
        "windows_common",
        "windows_interface",
        "windows_libloading",
        "windows_polyfill",
        "windows_strings",
        "windows_variant",
    },
    "windows_registry": {
        "windows_common",
        "windows_result",
        "windows_strings",
    },
    "windows_result": {"windows_libloading"},
    "windows_runtime": {
        "windows_common",
        "windows_core",
        "windows_interface",
        "windows_strings",
    },
    "windows_safearray": {
        "windows_common",
        "windows_libloading",
        "windows_strings",
        "windows_variant",
    },
    "windows_services": {
        "windows_common",
        "windows_strings",
    },
    "windows_strings": {"windows_libloading"},
    "windows_targets": set(),
    "windows_threading": {"windows_common"},
    "windows_variant": {
        "windows_common",
        "windows_libloading",
        "windows_strings",
    },
    "windows_version": {
        "windows_common",
        "windows_strings",
    },
    "windows_winui3": {
        "windows_common",
        "windows_core",
    },
}

WINDOWS_IMPORT_RE = re.compile(
    r"^\s*(?:(?:public|private|internal|protected)\s+)?import\s+(windows_[A-Za-z0-9_]+)",
    re.MULTILINE,
)
LOCAL_NATIVE_PROC_CACHE_RE = re.compile(r"\bcached[A-Za-z0-9_]*\s*[:=].*CPointer<Unit>")
TEST_COM_OBJECT_OWNER_RE = re.compile(
    r"\blet\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*"
    r"(?:createComObjectFromSchemas|createFixtureCounter|createCompositeFixtureCounter|"
    r"createInheritedFixture|createInheritedDefaultThunkFixture)\("
)
TEMP_COM_OBJECT_OWNER_RE = re.compile(
    r"\blet\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*"
    r"(?:ComObject<.*>(?:\.new)?|createComObject(?:FromSchemas|FromDescriptors)?|"
    r"createImplementedComObject)\("
)
GENERATED_HEADER = "// Generated by windows-bindgen. DO NOT EDIT."
GENERATED_TOML_HEADER = "# Generated by windows-bindgen. DO NOT EDIT."
GENERATED_MANIFEST_HEADER = "Generated by windows-bindgen. DO NOT EDIT."
GENERATED_COMMON_IGNORED_FILES = {
    "cjpm.lock",
    "codegen-manifest.json",
}
GENERATED_COMMON_FORBIDDEN_IMPORTS = {
    "import windows_core.*",
    "import windows_interface.*",
    "import windows_interface.macros.*",
}
WINDOWS_INTERFACE_MACRO_TEST_IMPORTS = {"windows_core"}
WINDOWS_INTERFACE_MACRO_TEST_LINK_CLOSURE = {
    "windows_interface",
    "windows_implement",
    "windows_core",
    "windows_result",
    "windows_strings",
    "windows_libloading",
}
IGNORED_SHELL_SCRIPT_DIRS = {".git", "target"}
FORBIDDEN_SCRIPT_EXTENSIONS = {".sh", ".ps1", ".bat"}
FINALIZER_SAFE_CLEANUP_HELPERS = {
    "closeBstrStateNoThrow",
    "closeHStringStateNoThrow",
    "closeHStringBuilderStateNoThrow",
}


def fail(message: str) -> None:
    print(f"FAIL: {message}", file=sys.stderr)
    sys.exit(1)


def check_path_exists(path: Path, kind: str) -> None:
    if not path.exists():
        fail(f"missing {kind}: {path}")


def load_toml(path: Path) -> dict:
    with path.open("rb") as f:
        return tomllib.load(f)


def expected_dependency_path(dependency: str) -> str:
    return "../" + dependency.replace("_", "-")


def load_python_string_list(path: Path, name: str) -> list[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        for target in node.targets:
            if isinstance(target, ast.Name) and target.id == name:
                value = ast.literal_eval(node.value)
                if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
                    fail(f"{path.relative_to(path.parent.parent)} {name} must be a literal string list")
                return value
    fail(f"{path} must define {name}")


def rel_posix(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def section_between(text: str, start: str, end: str, label: str) -> str:
    start_index = text.find(start)
    if start_index < 0:
        fail(f"missing {label} start marker")
    end_index = text.find(end, start_index + len(start))
    if end_index < 0:
        fail(f"missing {label} end marker")
    return text[start_index:end_index]


def require_text_before(text: str, earlier: str, later: str, message: str) -> None:
    earlier_index = text.find(earlier)
    later_index = text.find(later)
    if earlier_index < 0 or later_index < 0 or earlier_index > later_index:
        fail(message)


def check_winui_xaml_failed_out_cleanup(workspace: Path) -> None:
    xaml = workspace / "windows-winui3" / "src" / "xaml" / "mod.cj"
    check_path_exists(xaml, "windows-winui3 XAML helper")
    text = xaml.read_text(encoding="utf-8")
    require_text_before(
        text,
        "releaseFailedWinuiOutSlot(CPointer<CPointer<Unit>>(inout inner))",
        'checkHRESULT(hr, "IWindowFactory.CreateInstance")',
        "windows-winui3 IWindowFactory.CreateInstance must release failed inner out slot before checkHRESULT",
    )
    require_text_before(
        text,
        "releaseFailedWinuiOutSlot(CPointer<CPointer<Unit>>(inout result))",
        'checkHRESULT(hr, "IWindowFactory.CreateInstance")',
        "windows-winui3 IWindowFactory.CreateInstance must release failed result out slot before checkHRESULT",
    )
    require_text_before(
        text,
        "releaseFailedWinuiOutSlot(CPointer<CPointer<Unit>>(inout result))",
        'checkHRESULT(hr, "IFrameworkElement.FindName(${name})")',
        "windows-winui3 IFrameworkElement.FindName must release failed result out slot before checkHRESULT",
    )
    require_text_before(
        text,
        "releaseFailedWinuiOutSlot(CPointer<CPointer<Unit>>(inout result))",
        'checkHRESULT(hr, "IXamlReaderStatics.Load")',
        "windows-winui3 IXamlReaderStatics.Load must release failed result out slot before checkHRESULT",
    )
    cleanup = section_between(
        text,
        "func releaseFailedWinuiOutSlot",
        "func readWinuiVtbl",
        "windows-winui3 failed out-slot cleanup helper",
    )
    require_text_before(
        cleanup,
        "unsafe { slot.write(CPointer<Unit>()) }",
        "releaseRaw(raw)",
        "windows-winui3 failed out-slot cleanup must clear the slot before releasing it",
    )


def check_test_com_object_owners_released(workspace: Path) -> None:
    source_roots = [
        workspace / "windows-runtime" / "src",
        workspace / "windows-interface" / "tests" / "macros",
    ]
    for source_root in source_roots:
        if not source_root.exists():
            continue
        for source in source_root.rglob("*.cj"):
            lines = source.read_text(encoding="utf-8").splitlines()
            for index, line in enumerate(lines):
                match = TEST_COM_OBJECT_OWNER_RE.search(line)
                if match is None:
                    continue
                name = match.group(1)
                release_window = "\n".join(lines[index : index + 24])
                if f"{name}.close()" in release_window or f"{name}.releaseBase()" in release_window:
                    continue
                fail(
                    f"{source.relative_to(workspace)}:{index + 1} must release temporary "
                    f"COM object owner {name} after projecting interfaces"
                )


def check_temporary_com_object_projection_ownership(workspace: Path) -> None:
    source_roots = [
        workspace / "windows-runtime" / "src",
        workspace / "windows-implement" / "src",
        workspace / "windows-threading" / "src",
    ]
    for source_root in source_roots:
        if not source_root.exists():
            continue
        for source in source_root.rglob("*.cj"):
            if source.name.endswith("_test.cj"):
                continue
            lines = source.read_text(encoding="utf-8").splitlines()
            for index, line in enumerate(lines):
                match = TEMP_COM_OBJECT_OWNER_RE.search(line)
                if match is None:
                    continue
                name = match.group(1)
                projection_window = "\n".join(lines[index : index + 40])
                if f"{name}.intoInterface(" in projection_window:
                    continue
                if f"{name}.toInterface(" not in projection_window:
                    continue
                if f"{name}.close()" in projection_window or f"{name}.releaseBase()" in projection_window:
                    continue
                fail(
                    f"{source.relative_to(workspace)}:{index + 1} must consume or explicitly "
                    f"release temporary COM object owner {name} after projecting interfaces"
                )


def check_threading_pools_use_scope_or_explicit_close(workspace: Path) -> None:
    pool_create_re = re.compile(r"\b(?:Pool\.new|Pool)\(")
    source_roots = [
        workspace / "windows-core" / "src",
        workspace / "windows-implement" / "src",
        workspace / "windows-runtime" / "src",
        workspace / "windows-services" / "src",
        workspace / "windows-threading" / "src",
    ]
    for source_root in source_roots:
        if not source_root.exists():
            continue
        for source in source_root.rglob("*.cj"):
            relative = source.relative_to(workspace)
            if source.name.endswith("_test.cj"):
                continue
            if relative.as_posix() == "windows-threading/src/lib.cj":
                continue
            lines = source.read_text(encoding="utf-8").splitlines()
            for index, line in enumerate(lines):
                match = pool_create_re.search(line)
                if match is None or "Pool.withScope(" in line:
                    continue
                assignment = re.search(r"\blet\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*", line)
                if assignment is None:
                    fail(
                        f"{relative}:{index + 1} must use Pool.withScope or assign Pool "
                        "to a Resource owner that closes it"
                    )
                name = assignment.group(1)
                close_window = "\n".join(lines[index : index + 60])
                if f"{name}.close()" in close_window:
                    continue
                fail(f"{relative}:{index + 1} must close thread Pool {name} explicitly")


def check_finalizers_do_not_block_on_locks(workspace: Path) -> None:
    finalizer_decl = re.compile(r"(?m)^[ \t]*~init\s*\(\s*\)")
    blocked_patterns = (
        "synchronized(",
        ".lock()",
        ".unlock()",
        "spawn {",
        "releaseRaw(",
        "releaseArrayRawData(",
        "freeNativeValue(",
        "LibC.free",
        "coTaskMemFree(",
        "CloseHandle(",
        "RegCloseKey(",
        "CoTaskMemFree(",
        "SysFreeString(",
        "HeapFree(",
        "WindowsDeleteString(",
        "resolveProc(",
        "closeHStringState(",
        "finalizeHStringState(",
        "closeHStringBuilderState(",
        "closeBstrState(",
        "sysFreeStringAbi(",
        "closeOwnedState(",
        "hStringFree(",
        "sysFreeString(",
        "releaseSystemHStringHandle(",
        "closeStock",
        ".free()",
        ".close()",
        "wrapper.close()",
        "reference.close()",
        ".clear()",
        "unregisterTerminalEvent(",
        "CloseThreadpoolCleanupGroupMembers(",
        "releaseBase(",
        "closeComposableActivationState(",
        "clearRoutedEventHandlerSlot(",
        "compareAndSwap(",
    )
    blocked_helper_calls = (
        re.compile(r"\brelease[A-Za-z0-9_]*NoThrow\s*\("),
        re.compile(r"\bclose[A-Za-z0-9_]*NoThrow\s*\("),
        re.compile(r"\bcloseRegistryKey[A-Za-z0-9_]*\s*\("),
        re.compile(r"\bdestroySafeArrayNoThrow\s*\("),
        re.compile(r"\breleaseOwnedComPointer\s*\("),
    )
    for source in sorted(workspace.rglob("*.cj")):
        if any(part in IGNORED_SHELL_SCRIPT_DIRS for part in source.relative_to(workspace).parts):
            continue
        text = source.read_text(encoding="utf-8")
        offset = 0
        while True:
            match = finalizer_decl.search(text, offset)
            if match is None:
                break
            start = match.start()
            brace = text.find("{", match.end())
            if brace < 0:
                fail(f"{source.relative_to(workspace)} contains malformed ~init block")
            end = matching_cj_brace_end(text, brace)
            if end is None:
                fail(f"{source.relative_to(workspace)} contains unterminated ~init block")
            end += 1
            body = text[brace:end]
            for pattern in blocked_patterns:
                if pattern in body:
                    line = text[:start].count("\n") + 1
                    fail(
                        f"{source.relative_to(workspace)}:{line} finalizers must not use "
                        f"blocking cleanup paths; found {pattern}"
                    )
            for pattern in blocked_helper_calls:
                for match in pattern.finditer(body):
                    helper = match.group(0).split("(", 1)[0].strip()
                    if helper in FINALIZER_SAFE_CLEANUP_HELPERS:
                        continue
                    line = text[:start].count("\n") + 1
                    found = re.sub(r"\s+", "", match.group(0))
                    fail(
                        f"{source.relative_to(workspace)}:{line} finalizers must not call "
                        f"native/COM cleanup helpers; found {found}"
                    )
            offset = end


def matching_cj_brace_end(text: str, open_index: int) -> int | None:
    depth = 0
    in_string = False
    escaped = False
    in_line_comment = False
    in_block_comment = False
    index = open_index
    while index < len(text):
        char = text[index]
        next_char = text[index + 1] if index + 1 < len(text) else ""
        if in_line_comment:
            if char == "\n":
                in_line_comment = False
            index += 1
            continue
        if in_block_comment:
            if char == "*" and next_char == "/":
                in_block_comment = False
                index += 2
                continue
            index += 1
            continue
        if escaped:
            escaped = False
            index += 1
            continue
        if char == "\\" and in_string:
            escaped = True
            index += 1
            continue
        if not in_string and char == "/" and next_char == "/":
            in_line_comment = True
            index += 2
            continue
        if not in_string and char == "/" and next_char == "*":
            in_block_comment = True
            index += 2
            continue
        if char == '"':
            in_string = not in_string
            index += 1
            continue
        if in_string:
            index += 1
            continue
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return index
        index += 1
    return None


def cj_function_body(text: str, name: str, source: Path, workspace: Path) -> str:
    match = re.search(rf"\bfunc\s+{re.escape(name)}\s*\(", text)
    if match is None:
        fail(f"{source.relative_to(workspace)} must define {name}()")
    brace = text.find("{", match.end())
    if brace < 0:
        fail(f"{source.relative_to(workspace)} contains malformed {name}() body")
    depth = 0
    end = brace
    while end < len(text):
        char = text[end]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                end += 1
                break
        end += 1
    if depth != 0:
        fail(f"{source.relative_to(workspace)} contains unterminated {name}() body")
    return text[brace:end]


def check_windows_string_finalizer_paths_are_lock_free(workspace: Path) -> None:
    strings_root = workspace / "windows-strings" / "src"
    ref_count = strings_root / "ref_count.cj"
    native = strings_root / "native.cj"
    check_path_exists(ref_count, "windows-strings HString ref-count implementation")
    check_path_exists(native, "windows-strings native ABI implementation")

    ref_count_text = ref_count.read_text(encoding="utf-8")
    for pattern in ("Mutex", "synchronized("):
        if pattern in ref_count_text:
            fail(
                f"{ref_count.relative_to(workspace)} must keep HString finalizer "
                f"ref-count release lock-free; found {pattern}"
            )

    native_text = native.read_text(encoding="utf-8")
    if "FinalizerSafeProc(\"oleaut32.dll\", \"SysFreeString\")" not in native_text:
        fail(
            f"{native.relative_to(workspace)} must use windows_libloading.FinalizerSafeProc "
            "for BSTR finalizer-safe SysFreeString"
        )
    sys_free_body = cj_function_body(native_text, "sysFreeStringAbi", native, workspace)
    for pattern in (
        "ensureResolved(",
        "resolveProc(",
        "resolveOleaut32Proc(",
        "resolveWinrtStringProc(",
        "resolveKernel32Proc(",
    ):
        if pattern in sys_free_body:
            fail(
                f"{native.relative_to(workspace)} sysFreeStringAbi() is used by BSTR finalizers "
                f"and must not resolve symbols during finalization; found {pattern}"
            )


def check_long_lived_vtables_are_unmanaged(workspace: Path) -> None:
    blocked_patterns = (
        re.compile(r"CPointerHandle<[^>]*[Vv]tbl"),
        re.compile(r"CPointerHandle<CPointer<Unit>>"),
        re.compile(r"acquireArrayRawData\s*\(\s*Array<[^>]*[Vv]tbl"),
        re.compile(r"acquireArrayRawData\s*\(\s*[A-Za-z_][A-Za-z0-9_]*[Vv]tbl[A-Za-z0-9_]*\s*\)"),
        re.compile(r"acquireArrayRawData\s*\(\s*slots\s*\)"),
    )
    source_roots = [
        workspace / "windows-core" / "src",
        workspace / "windows-implement" / "src",
        workspace / "windows-interface" / "src",
        workspace / "windows-runtime" / "src",
    ]
    for source_root in source_roots:
        if not source_root.exists():
            continue
        for source in sorted(source_root.rglob("*.cj")):
            if any(part in IGNORED_SHELL_SCRIPT_DIRS for part in source.relative_to(workspace).parts):
                continue
            text = source.read_text(encoding="utf-8")
            for pattern in blocked_patterns:
                match = pattern.search(text)
                if match is not None:
                    line = text[: match.start()].count("\n") + 1
                    fail(
                        f"{source.relative_to(workspace)}:{line} must store long-lived "
                        "vtable memory in unmanaged native storage, not pinned Cangjie arrays"
                    )


def iter_cj_class_blocks(text: str) -> list[tuple[int, str, str]]:
    blocks: list[tuple[int, str, str]] = []
    offset = 0
    while True:
        start = text.find("class ", offset)
        if start < 0:
            break
        brace = text.find("{", start)
        if brace < 0:
            break
        header = text[start:brace]
        depth = 0
        end = brace
        while end < len(text):
            char = text[end]
            if char == "{":
                depth += 1
            elif char == "}":
                depth -= 1
                if depth == 0:
                    end += 1
                    break
            end += 1
        if depth != 0:
            break
        line = text[:start].count("\n") + 1
        blocks.append((line, header, text[start:end]))
        offset = end
    return blocks


def iter_cj_function_bodies(text: str, name: str) -> list[tuple[int, str]]:
    blocks: list[tuple[int, str]] = []
    search = f"func {name}"
    offset = 0
    while True:
        start = text.find(search, offset)
        if start < 0:
            break
        line_end = text.find("\n", start)
        if line_end < 0:
            line_end = len(text)
        brace = text.find("{", start, line_end)
        if brace < 0:
            offset = line_end
            continue
        depth = 0
        end = brace
        while end < len(text):
            char = text[end]
            if char == "{":
                depth += 1
            elif char == "}":
                depth -= 1
                if depth == 0:
                    end += 1
                    break
            end += 1
        if depth != 0:
            break
        line = text[:start].count("\n") + 1
        blocks.append((line, text[start:end]))
        offset = end
    return blocks


def check_native_allocations_have_deterministic_owner(workspace: Path) -> None:
    source_roots = [
        workspace / "windows-core" / "src",
        workspace / "windows-implement" / "src",
        workspace / "windows-interface" / "src",
        workspace / "windows-runtime" / "src",
    ]
    for source_root in source_roots:
        if not source_root.exists():
            continue
        for source in sorted(source_root.rglob("*.cj")):
            relative = source.relative_to(workspace)
            if any(part in IGNORED_SHELL_SCRIPT_DIRS for part in relative.parts):
                continue
            if relative.as_posix() == "windows-interface/src/macros/windows_interface_macros.cj":
                continue
            text = source.read_text(encoding="utf-8")
            for line, header, body in iter_cj_class_blocks(text):
                if "allocateNativeValue" not in body and "allocateNativeArray" not in body:
                    continue
                resource_close = (
                    "Resource" in header
                    and "func close(): Unit" in body
                    and "func isClosed(): Bool" in body
                    and "freeNativeValue" in body
                )
                refcount_destroy = "func destroy" in body and "freeNativeValue" in body
                runtime_destroy_callback = "setOnDestroy" in body and "freeNativeValue" in body
                if resource_close or refcount_destroy or runtime_destroy_callback:
                    continue
                fail(
                    f"{relative}:{line} owns native allocated storage but has no deterministic "
                    "Resource.close, refcount destroy, or runtime onDestroy free path"
                )


def check_collection_indexof_thunks_reject_null_index(workspace: Path) -> None:
    runtime_path = workspace / "windows-runtime" / "src" / "collections_runtime.cj"
    text = runtime_path.read_text(encoding="utf-8")
    bodies = iter_cj_function_bodies(text, "__winrtThunk_IndexOf")
    if len(bodies) < 3:
        fail("windows-runtime collection IndexOf thunks are missing expected producer implementations")
    for line, body in bodies:
        dispatch = body.find("this.IndexOf(")
        prefix = body[:dispatch if dispatch >= 0 else len(body)]
        compact_prefix = re.sub(r"\s+", "", prefix)
        has_index_guard = re.search(
            r"if\([^{};]*arg1\.isNull\(\)[^{};]*\)\{returnE_POINTER(?:\.value)?;?\}",
            compact_prefix,
        )
        if has_index_guard is None:
            fail(
                f"windows-runtime/src/collections_runtime.cj:{line} IndexOf thunk must reject null "
                "index out pointer before dispatch"
            )


def check_array_materialization_cleanup(workspace: Path) -> None:
    array_text = (workspace / "windows-core" / "src" / "array.cj").read_text(encoding="utf-8")
    native_array_with_len = section_between(
        array_text,
        "public static func withLen(length: Int64): NativeAbiArrayStorage<T>",
        "public func len(): UInt32",
        "windows-core NativeAbiArrayStorage.withLen",
    )
    for pattern in (
        "let raw = coTaskMemAlloc(totalBytes)",
        "if (raw.isNull())",
        "throw WindowsException(E_OUTOFMEMORY)",
    ):
        if pattern not in native_array_with_len:
            fail("windows-core NativeAbiArrayStorage.withLen must reject CoTaskMemAlloc failure")
    native_array_clear = section_between(
        array_text,
        "public func clear(): Unit",
        "public func rawOrNull(): CPointer<T>",
        "windows-core NativeAbiArrayStorage.clear",
    )
    if "coTaskMemFree(CPointer<Unit>(data))" not in native_array_clear:
        fail("windows-core NativeAbiArrayStorage.clear must free owned CoTaskMem arrays")
    native_into_abi_start = array_text.find("public func intoAbi(): (CPointer<T>, UInt32)")
    if native_into_abi_start < 0:
        fail("missing windows-core AbiArray.intoAbi")
    native_into_abi = array_text[native_into_abi_start:]
    if "native.detach()" not in native_into_abi or "closed = true" not in native_into_abi:
        fail("windows-core AbiArray.intoAbi must detach storage exactly once and close the owner")

    array_proxy_text = (workspace / "windows-core" / "src" / "array_proxy.cj").read_text(encoding="utf-8")
    release_slots = section_between(
        array_proxy_text,
        "func releasePublishedObjectSlots",
        "func publishCopyArray",
        "windows-core ArrayProxy object slot cleanup",
    )
    for pattern in (
        "releaseSystemHStringHandle(raw)",
        "interfaceHandleReleaseRaw(raw)",
    ):
        if pattern not in release_slots:
            fail("windows-core ArrayProxy must release every published HSTRING/interface slot kind")
    publish_object_array = section_between(
        array_proxy_text,
        "func publishObjectArray",
        "// ArrayProxy stages an ABI array",
        "windows-core ArrayProxy object array publisher",
    )
    for pattern in (
        "let slots = allocateUnitPointerSlots(values.size)",
        "try {",
        "catch (error: Exception)",
        "releasePublishedObjectSlots(values, slots, index)",
        "CoTaskMemFree(CPointer<Unit>(slots))",
        "throw error",
        "dataTarget.write(CPointer<Unit>(slots))",
    ):
        if pattern not in publish_object_array:
            fail("windows-core ArrayProxy object arrays must clean partial HSTRING/interface publication failures")

    winrt_generic_text = (workspace / "windows-core" / "src" / "winrt_generic.cj").read_text(encoding="utf-8")
    take_slot = section_between(
        winrt_generic_text,
        "static func takeWinrtHandleSlot",
        "static func releaseWinrtHandle",
        "windows-core HandleWinrtType.takeWinrtHandleSlot",
    )
    if "slot.write(CPointer<Unit>())" not in take_slot:
        fail("windows-core HandleWinrtType.takeWinrtHandleSlot must clear transferred raw slots")
    release_owned_slots = section_between(
        winrt_generic_text,
        "func releaseOwnedWinrtHandleSlots",
        "public open class WinrtOutputBridge",
        "windows-core releaseOwnedWinrtHandleSlots",
    )
    for pattern in (
        "releaseOwnedWinrtHandle<T>(raw)",
        "slot.write(CPointer<Unit>())",
        "firstError",
    ):
        if pattern not in release_owned_slots:
            fail("windows-core releaseOwnedWinrtHandleSlots must release and clear remaining raw slots")
    handle_bridge_section = section_between(
        winrt_generic_text,
        "class HandleWinrtOutputBridge<T>",
        "public func winrtCallGenericOut<T>",
        "windows-core HandleWinrtOutputBridge",
    )
    handle_take_array_out = section_between(
        handle_bridge_section,
        "public override func takeArrayOut(",
        "public override func storeOut(",
        "windows-core HandleWinrtOutputBridge.takeArrayOut",
    )
    for pattern in (
        "var valuesOption: Option<ArrayList<T>> = None",
        "var completed = false",
        "T.takeWinrtHandleSlot(slot)",
        "closeWinrtArrayValues<T>(values)",
        "releaseOwnedWinrtHandleSlots<T>(slots, length)",
        "coTaskMemFree(data)",
    ):
        if pattern not in handle_take_array_out:
            fail("windows-core HandleWinrtOutputBridge.takeArrayOut must clean partial materialization failures")
    for label, bridge_marker in (
        ("CopyWinrtOutputBridge", "class CopyWinrtOutputBridge<T>"),
        ("ProjectedCopyWinrtOutputBridge", "public class ProjectedCopyWinrtOutputBridge<T, A, D>"),
    ):
        bridge_section = section_between(
            winrt_generic_text,
            bridge_marker,
            "public override func storeOut(",
            f"windows-core {label}.takeArrayOut",
        )
        for pattern in (
            "if (length > 0u32 && data.isNull())",
            "var owned: Option<AbiArray",
            "array.close()",
            "coTaskMemFree(data)",
        ):
            if pattern not in bridge_section:
                fail(f"windows-core {label}.takeArrayOut must free CoTaskMem arrays on all paths")

    foundation_runtime_text = (workspace / "windows-runtime" / "src" / "foundation_runtime.cj").read_text(encoding="utf-8")
    string_projector = section_between(
        foundation_runtime_text,
        "func projectPropertyValueStringHandleArray",
        "func releasePropertyValueStringHandleArray",
        "windows-runtime PropertyValue string input projector",
    )
    for pattern in (
        "try {",
        "catch (error: Exception)",
        "releaseSystemHStringHandle(handles[releaseIndex])",
        "throw error",
    ):
        if pattern not in string_projector:
            fail("windows-runtime PropertyValue string array projection must release partially copied HSTRINGs")
    string_raw_release = section_between(
        foundation_runtime_text,
        "func releasePropertyValueStringRawSlots",
        "func releasePropertyValueInspectableRaw",
        "windows-runtime PropertyValue string raw slot cleanup",
    )
    for pattern in (
        "releaseSystemHStringHandle(raw)",
        "slot.write(CPointer<Unit>())",
    ):
        if pattern not in string_raw_release:
            fail("windows-runtime PropertyValue string raw slot cleanup must release and clear slots")
    string_take_array = section_between(
        foundation_runtime_text,
        "func takePropertyValueStringArray",
        "func releasePropertyValueInspectableRawSlots",
        "windows-runtime PropertyValue string array materializer",
    )
    for pattern in (
        "var result: Option<Array<windows_core.HString>> = None",
        "var pending: Option<windows_core.HString> = None",
        "slot.write(CPointer<Unit>())",
        "closePropertyValueStringArray(values)",
        "releasePropertyValueStringRawSlots(data, length)",
        "freePropertyValueHandleArraySlots(data)",
    ):
        if pattern not in string_take_array:
            fail("windows-runtime PropertyValue string array materializer must clean partial materialization failures")
    inspectable_raw_release = section_between(
        foundation_runtime_text,
        "func releasePropertyValueInspectableRawSlots",
        "func closePropertyValueInspectableArray",
        "windows-runtime PropertyValue inspectable raw slot cleanup",
    )
    for pattern in (
        "releasePropertyValueInspectableRaw(raw)",
        "slot.write(CPointer<Unit>())",
    ):
        if pattern not in inspectable_raw_release:
            fail("windows-runtime PropertyValue inspectable raw slot cleanup must release and clear slots")
    inspectable_take_array = section_between(
        foundation_runtime_text,
        "func takePropertyValueInspectableArray",
        "func takePropertyValueGuidArray",
        "windows-runtime PropertyValue inspectable array materializer",
    )
    for pattern in (
        "var result: Option<Array<Option<IInspectable>>> = None",
        "var pending: Option<IInspectable> = None",
        "IInspectable.fromAbiTake(raw)",
        "slot.write(CPointer<Unit>())",
        "closePropertyValueInspectableArray(values)",
        "releasePropertyValueInspectableRawSlots(data, length)",
        "freePropertyValueHandleArraySlots(data)",
    ):
        if pattern not in inspectable_take_array:
            fail("windows-runtime PropertyValue inspectable array materializer must clean partial materialization failures")


def is_ignored_generated_path(path: Path, root: Path) -> bool:
    return any(part in IGNORED_SHELL_SCRIPT_DIRS for part in path.relative_to(root).parts)


def check_no_shell_scripts(workspace: Path) -> None:
    forbidden_scripts: list[str] = []
    for path in sorted(workspace.rglob("*")):
        if not path.is_file() or is_ignored_generated_path(path, workspace):
            continue
        if path.suffix.lower() not in FORBIDDEN_SCRIPT_EXTENSIONS:
            continue
        relative = rel_posix(path, workspace)
        forbidden_scripts.append(relative)
    if forbidden_scripts:
        extensions = sorted(FORBIDDEN_SCRIPT_EXTENSIONS)
        fail(f"shell/PowerShell/batch scripts are not allowed in windows-cj; extensions={extensions}, found={forbidden_scripts}")


def check_workspace_members(workspace: Path) -> None:
    config = load_toml(workspace / "cjpm.toml")
    members = set(config.get("workspace", {}).get("members", []))
    if members != ACTIVE_WORKSPACE_MEMBERS:
        missing = sorted(ACTIVE_WORKSPACE_MEMBERS - members)
        extra = sorted(members - ACTIVE_WORKSPACE_MEMBERS)
        fail(f"workspace members mismatch; missing={missing}, extra={extra}")
    for member in sorted(members):
        root = workspace / member
        check_path_exists(root / "cjpm.toml", f"{member} cjpm.toml")
        check_path_exists(root / "src", f"{member} src/")

    package_roots = {
        child.name
        for child in workspace.iterdir()
        if child.is_dir() and (child / "cjpm.toml").exists()
    }
    extra_package_roots = sorted(package_roots - ACTIVE_WORKSPACE_MEMBERS)
    if extra_package_roots:
        fail(f"unexpected root package directories in windows-cj: {extra_package_roots}")


def check_reference_only_packages(workspace: Path) -> None:
    deprecated_root = workspace.parent / "deprecated_windows_cj"
    check_path_exists(deprecated_root, "deprecated_windows_cj root")
    for name in sorted(REFERENCE_ONLY_PACKAGES):
        active_root = workspace / name
        if active_root.exists():
            fail(f"{name} must be moved out of windows-cj; found {active_root}")
        archived_root = deprecated_root / name
        check_path_exists(archived_root, f"{name} deprecated reference root")
        check_path_exists(archived_root / "REFERENCE_ONLY.md", f"{name} REFERENCE_ONLY.md")


def check_generated_common_package(workspace: Path) -> None:
    generated = workspace / "windows-common"
    check_path_exists(generated / "cjpm.toml", "windows-common cjpm.toml")
    check_path_exists(generated / "codegen-manifest.json", "windows-common codegen-manifest.json")
    support_deps = generated / "src" / "support_deps.cj"
    check_path_exists(support_deps, "windows-common support_deps.cj")
    check_path_exists(generated / "src" / "mod.cj", "windows-common mod.cj")
    manifest = json.loads((generated / "codegen-manifest.json").read_text(encoding="utf-8"))
    if manifest.get("generated_by") != GENERATED_MANIFEST_HEADER:
        fail("windows-common codegen manifest must identify windows-bindgen as its source")
    manifest_file_list = manifest.get("files") or []
    if len(manifest_file_list) != len(set(manifest_file_list)):
        fail("windows-common codegen manifest must not contain duplicate file entries")
    manifest_files = set(manifest_file_list)
    if not manifest_files:
        fail("windows-common codegen manifest must list generated files")
    manifest_hashes = manifest.get("file_hashes")
    if not isinstance(manifest_hashes, dict):
        fail("windows-common codegen manifest must include per-file content hashes")
    manifest_hash_files = set(manifest_hashes.keys())
    if manifest_hash_files != manifest_files:
        missing = sorted(manifest_files - manifest_hash_files)
        extra = sorted(manifest_hash_files - manifest_files)
        fail(f"windows-common codegen manifest hash key mismatch; missing={missing}, extra={extra}")

    actual_files = set()
    for file in generated.rglob("*"):
        if not file.is_file():
            continue
        relative = rel_posix(file, generated)
        if relative.startswith("target/") or relative in GENERATED_COMMON_IGNORED_FILES:
            continue
        actual_files.add(relative)

    if actual_files != manifest_files:
        missing = sorted(manifest_files - actual_files)
        extra = sorted(actual_files - manifest_files)
        fail(f"windows-common generated file set mismatch; missing={missing}, extra={extra}")

    for relative in sorted(manifest_files):
        file = generated / relative
        actual_hash = hashlib.sha256(file.read_bytes()).hexdigest()
        expected_hash = manifest_hashes.get(relative)
        if expected_hash != actual_hash:
            fail(f"{relative} content hash does not match windows-common codegen manifest")
        if file.suffix == ".cj":
            text = file.read_text(encoding="utf-8")
            first_line = text.splitlines()[0]
            if first_line != GENERATED_HEADER:
                fail(f"{relative} must start with the generated-by header")
            for forbidden_import in GENERATED_COMMON_FORBIDDEN_IMPORTS:
                if forbidden_import in text:
                    fail(f"{relative} must use explicit imports instead of {forbidden_import}")
        elif file.suffix == ".toml":
            first_line = file.read_text(encoding="utf-8").splitlines()[0]
            if first_line != GENERATED_TOML_HEADER:
                fail(f"{relative} must start with the generated-by header")

    config = load_toml(generated / "cjpm.toml")
    package = config.get("package", {})
    if package.get("name") != "windows_common":
        fail(f"windows-common package name must be windows_common, got {package.get('name')!r}")
    if manifest.get("package_name") != "windows_common":
        fail(f"windows-common manifest package name must be windows_common, got {manifest.get('package_name')!r}")
    support_imports = set(WINDOWS_IMPORT_RE.findall(support_deps.read_text(encoding="utf-8")))
    expected_support_imports = PACKAGE_DEPENDENCIES["windows_common"]
    if support_imports != expected_support_imports:
        missing = sorted(expected_support_imports - support_imports)
        extra = sorted(support_imports - expected_support_imports)
        fail(f"windows-common support_deps imports mismatch; missing={missing}, extra={extra}")
    if "link-option" in (generated / "cjpm.toml").read_text(encoding="utf-8"):
        fail("windows-common must not emit static link options; native calls go through windows_libloading")

    check_generated_common_impl_invariants(generated)


def check_generated_common_impl_invariants(generated: Path) -> None:
    impl_dir = generated / "src" / "impl"
    check_path_exists(impl_dir, "windows-common impl symbol directory")
    impl_files = sorted(impl_dir.glob("symbols_*.cj"))
    if not impl_files:
        fail("windows-common impl symbol directory must contain symbols_*.cj chunks")
    impl_text = "\n".join(path.read_text(encoding="utf-8") for path in impl_files)
    if "func Start(callback: CPointer<Unit>): Int32" not in impl_text:
        fail("windows-common IApplicationStatics.Start must accept a raw WinRT delegate COM pointer")
    if "public type Microsoft_UI_Xaml_ApplicationInitializationCallback = CFunc" in impl_text:
        fail("windows-common must not render WinRT delegate projections as CFunc aliases")
    for _, header, body in iter_cj_class_blocks(impl_text):
        if "projectionKind()" not in body or "private let raw: CPointer<Unit>" not in body:
            continue
        if "<: Resource" in header or "& Resource" in header:
            match = re.search(r"\bclass\s+([A-Za-z_][A-Za-z0-9_]*)", header)
            class_name = match.group(1) if match is not None else header.strip()
            required_fragments = (
                "private var ownsHandle: Bool = false",
                "public init(raw: CPointer<Unit>, takeOwnership!: Bool)",
                "public func close(): Unit",
                "let shouldRelease = ownsHandle",
                "ownsHandle = false\n        closed = true\n        if (shouldRelease)",
                ".releaseRaw(raw)",
                "public static func addRefRaw(raw: CPointer<Unit>): Unit",
            )
            for fragment in required_fragments:
                if fragment not in body:
                    fail(
                        "windows-common raw handle Resource wrappers must preserve "
                        f"owned ABI cleanup; {class_name} is missing {fragment!r}"
                    )
            extension_fragments = (
                f"extend {class_name} <: windows_core.HandleWinrtType<{class_name}>",
                f"public static func intoOwnedWinrtHandle(value: {class_name}): CPointer<Unit>",
                f"public static func cloneWinrtValue(value: {class_name}): {class_name}",
            )
            for fragment in extension_fragments:
                if fragment not in impl_text:
                    fail(
                        "windows-common raw handle Resource wrappers must preserve "
                        f"owned ABI cleanup; {class_name} is missing {fragment!r}"
                    )
            continue
        match = re.search(r"\bclass\s+([A-Za-z_][A-Za-z0-9_]*)", header)
        class_name = match.group(1) if match is not None else header.strip()
        fail(f"windows-common raw handle classes must be owning Resource wrappers: {class_name}")
    if "extend Microsoft_UI_Xaml_ApplicationInitializationCallback <: windows_core.HandleWinrtType<Microsoft_UI_Xaml_ApplicationInitializationCallback>" not in impl_text:
        fail("windows-common raw WinRT delegate classes must implement HandleWinrtType")
    if "winrtBorrowGenericIn<Microsoft_UI_Xaml_ApplicationInitializationCallback>(callback)" not in impl_text:
        fail("windows-common Application.Start must borrow delegate handles through HandleWinrtType")
    if "Microsoft_UI_Xaml_IApplication.signature()" in impl_text:
        fail("windows-common runtime class signatures must not call ambiguous interface signature() members")
    if "let _ = hr__.ok()" in impl_text:
        fail("windows-common runtime class factory wrappers must throw on failed HRESULT values")


def check_cj_import_boundaries(workspace: Path, root: Path, allowed_imports: set[str]) -> None:
    if not root.exists():
        return
    for source in root.rglob("*.cj"):
        text = source.read_text(encoding="utf-8")
        for imported in WINDOWS_IMPORT_RE.findall(text):
            if imported not in allowed_imports:
                fail(f"{source.relative_to(workspace)} imports {imported} without a declared boundary")


def check_package_boundaries(workspace: Path) -> None:
    for member in sorted(ACTIVE_WORKSPACE_MEMBERS):
        root = workspace / member
        config = load_toml(root / "cjpm.toml")
        package_name = config.get("package", {}).get("name")
        if package_name not in PACKAGE_DEPENDENCIES:
            fail(f"{member} has no package dependency rule")

        expected_deps = PACKAGE_DEPENDENCIES[package_name]
        actual_deps = set((config.get("dependencies") or {}).keys())
        if actual_deps != expected_deps:
            missing = sorted(expected_deps - actual_deps)
            extra = sorted(actual_deps - expected_deps)
            fail(f"{member} dependencies mismatch; missing={missing}, extra={extra}")
        for dependency in sorted(actual_deps):
            dependency_config = config.get("dependencies", {}).get(dependency)
            if not isinstance(dependency_config, dict):
                fail(f"{member} dependency {dependency} must use a local path table")
            expected_path = expected_dependency_path(dependency)
            if dependency_config.get("path") != expected_path:
                fail(
                    f"{member} dependency {dependency} must point at {expected_path}, "
                    f"got {dependency_config.get('path')!r}"
                )

        src_root = root / "src"
        if not src_root.exists():
            continue

        allowed_imports = expected_deps | {package_name}
        check_cj_import_boundaries(workspace, src_root, allowed_imports)

    macro_tests = workspace / "windows-interface" / "tests"
    check_path_exists(macro_tests, "windows-interface macro tests")
    macro_fixtures = sorted((macro_tests / "macros").glob("*.cj"))
    if not macro_fixtures:
        fail("windows-interface macro tests must include at least one .cj fixture")
    check_cj_import_boundaries(
        workspace,
        macro_tests,
        PACKAGE_DEPENDENCIES["windows_interface"]
        | {"windows_interface"}
        | WINDOWS_INTERFACE_MACRO_TEST_IMPORTS,
    )
    macro_check = workspace / "windows-interface" / "scripts" / "check_macros.py"
    check_path_exists(macro_check, "windows-interface macro check script")
    macro_import_packages = set(load_python_string_list(macro_check, "IMPORT_PACKAGES"))
    if macro_import_packages != WINDOWS_INTERFACE_MACRO_TEST_LINK_CLOSURE:
        missing = sorted(WINDOWS_INTERFACE_MACRO_TEST_LINK_CLOSURE - macro_import_packages)
        extra = sorted(macro_import_packages - WINDOWS_INTERFACE_MACRO_TEST_LINK_CLOSURE)
        fail(f"windows-interface macro test link closure mismatch; missing={missing}, extra={extra}")

    interface_native = workspace / "windows-interface" / "src" / "native.cj"
    if interface_native.exists():
        fail("implementation native helpers must not live in windows-interface/src/native.cj")

    implement_native = workspace / "windows-implement" / "src" / "native.cj"
    check_path_exists(implement_native, "windows-implement native helper")
    implement_native_text = implement_native.read_text(encoding="utf-8")
    if "CoCreateFreeThreadedMarshaler" not in implement_native_text:
        fail("windows-implement native helper must own CoCreateFreeThreadedMarshaler")

    com_registry = workspace / "windows-implement" / "src" / "com_registry.cj"
    com_registry_text = com_registry.read_text(encoding="utf-8")
    if ".lock()" in com_registry_text or ".unlock()" in com_registry_text:
        fail("windows-implement COM registries must use synchronized blocks instead of manual lock/unlock")

    hstring_ref_count = workspace / "windows-strings" / "src" / "ref_count.cj"
    hstring_ref_count_text = hstring_ref_count.read_text(encoding="utf-8")
    if ".lock()" in hstring_ref_count_text or ".unlock()" in hstring_ref_count_text:
        fail("windows-strings HSTRING refcount state must use synchronized blocks")
    bstr_text = (workspace / "windows-strings" / "src" / "bstr.cj").read_text(encoding="utf-8")
    if "unsafeFromRaw" in bstr_text or "unsafeAttach" in bstr_text:
        fail("windows-strings BSTR raw constructors must describe ownership instead of using unsafe* names")
    for source in (workspace / "windows-strings" / "src").rglob("*.cj"):
        if "Unsafe:" in source.read_text(encoding="utf-8"):
            fail(f"{source.relative_to(workspace)} must document caller guarantees without unsafe-style API labels")
    strings_native = workspace / "windows-strings" / "src" / "native.cj"
    check_path_exists(strings_native, "windows-strings native helper")
    for source in (workspace / "windows-strings" / "src").rglob("*.cj"):
        text = source.read_text(encoding="utf-8")
        if source != strings_native and "windows_libloading" in text:
            fail(f"{source.relative_to(workspace)} must use windows-strings native helpers instead of loading symbols directly")

    threading_lib = workspace / "windows-threading" / "src" / "lib.cj"
    threading_lib_text = threading_lib.read_text(encoding="utf-8")
    if ".lock()" in threading_lib_text or ".unlock()" in threading_lib_text:
        fail("windows-threading state guards must use synchronized blocks")

    services_lib = workspace / "windows-services" / "src" / "lib.cj"
    services_lib_text = services_lib.read_text(encoding="utf-8")
    if ".lock()" in services_lib_text or ".unlock()" in services_lib_text:
        fail("windows-services state guards must use synchronized blocks")

    runtime_async = workspace / "windows-runtime" / "src" / "async_helpers.cj"
    runtime_async_text = runtime_async.read_text(encoding="utf-8")
    if ".lock()" in runtime_async_text or ".unlock()" in runtime_async_text:
        fail("windows-runtime async state guards must use synchronized blocks")

    core_type_impl = workspace / "windows-core" / "src" / "type_impl.cj"
    core_type_impl_text = core_type_impl.read_text(encoding="utf-8")
    if "fromAbiTakeWinrtHandle(raw: CPointer<Unit>): HString { HString.fromAbiTake(raw) }" in core_type_impl_text:
        fail("windows-core HString WinRT out handles must use system HSTRING ownership")
    if "viewWinrtHandle(raw: CPointer<Unit>): HString { HString.viewOf(raw) }" in core_type_impl_text:
        fail("windows-core HString WinRT input handles must copy borrowed system HSTRINGs")
    if "intoWinrtHandle(value: HString): CPointer<Unit> { value.asRaw() }" in core_type_impl_text:
        fail("windows-core HString WinRT handles must publish system HSTRING copies")
    core_ref_param_text = (workspace / "windows-core" / "src" / "ref_param.cj").read_text(encoding="utf-8")
    if "case hstring: HString" in core_ref_param_text and "hstring.asRaw()" in core_ref_param_text:
        fail("windows-core InParam<HString> must not publish project-managed HSTRING handles")
    winrt_generic_text = (workspace / "windows-core" / "src" / "winrt_generic.cj").read_text(encoding="utf-8")
    if "SystemHStringWinrtInputBorrow" not in winrt_generic_text or "borrowedWinrtInputHandle<T>(value)" not in winrt_generic_text:
        fail("windows-core HString generic input borrows must publish system HSTRING copies")
    hstring_borrow_section = section_between(
        winrt_generic_text,
        "class SystemHStringWinrtInputBorrow",
        "func borrowedWinrtInputHandle",
        "windows-core HString generic input borrow",
    )
    if "raw = value.toSystemHandleCopy()" not in hstring_borrow_section:
        fail("windows-core HString generic input borrow must create a system HSTRING copy")
    if "releaseSystemHStringHandle(handle)" not in hstring_borrow_section:
        fail("windows-core HString generic input borrow must release system HSTRING copies without allocating")
    if "HString.fromSystemHandleTake(raw).close()" in hstring_borrow_section:
        fail("windows-core HString generic input borrow release must not allocate while closing")
    owned_winrt_handle_section = section_between(
        winrt_generic_text,
        "func ownedWinrtOutHandle",
        "public open class WinrtOutputBridge",
        "windows-core HString generic output handle",
    )
    if "case hstring: HString" not in owned_winrt_handle_section or "hstring.toSystemHandleCopy()" not in owned_winrt_handle_section:
        fail("windows-core HString generic output handles must publish system HSTRING copies")
    if "hstring.asRaw()" in owned_winrt_handle_section or "hstring.clone().intoRaw()" in owned_winrt_handle_section:
        fail("windows-core HString generic output handles must not publish project-managed HSTRING storage")
    array_proxy_text = (workspace / "windows-core" / "src" / "array_proxy.cj").read_text(encoding="utf-8")
    if "value.intoRaw()" in array_proxy_text or "value.clone().intoRaw()" in array_proxy_text:
        fail("windows-core ArrayProxy must publish HString elements as system HSTRING copies")
    array_proxy_release_section = section_between(
        array_proxy_text,
        "func releasePublishedObjectSlots",
        "func publishCopyArray",
        "windows-core ArrayProxy object cleanup",
    )
    if "releaseSystemHStringHandle(raw)" not in array_proxy_release_section:
        fail("windows-core ArrayProxy must release system HSTRING slots without allocating")
    if "HString.fromSystemHandleTake(raw).close()" in array_proxy_release_section:
        fail("windows-core ArrayProxy cleanup must not allocate while releasing system HSTRING slots")
    interface_impl_surface_text = (workspace / "windows-implement" / "src" / "interface_impl_surface.cj").read_text(encoding="utf-8")
    runtime_name_section = section_between(
        interface_impl_surface_text,
        "public func getRuntimeClassNameBase",
        "public func getTrustLevelBase",
        "windows-implement GetRuntimeClassNameBase",
    )
    if "intoRaw" in runtime_name_section:
        fail("windows-implement GetRuntimeClassName must publish system HSTRING copies")
    if "toSystemHandleCopy()" not in runtime_name_section:
        fail("windows-implement GetRuntimeClassName must publish system HSTRING copies")
    implement_surface_text = interface_impl_surface_text
    descriptor_schema_text = (workspace / "windows-implement" / "src" / "descriptor_schema.cj").read_text(encoding="utf-8")
    if "public let vtableAncestorIids: Array<GUID>" not in descriptor_schema_text:
        fail("windows-implement descriptors must distinguish QI metadata from vtable inheritance metadata")
    if "func resolvedDescriptorVtableAncestorDepth(" not in descriptor_schema_text:
        fail("windows-implement slot assignment must compute effective vtable inheritance depth")
    if "func resolvedDescriptorIsComInterface(" not in descriptor_schema_text:
        fail("windows-implement slot assignment must infer COM inheritance through descriptor chains")
    if "func findDeepestDescendantIndex(" not in descriptor_schema_text or "descriptorContainsVtableAncestor(values, index, parent.iid)" not in descriptor_schema_text:
        fail("windows-implement slot assignment must group inherited slots through full ancestor chains")
    if "func explicitCustomVtblArray(" not in implement_surface_text:
        fail("windows-implement must map explicit custom vtables through resolved schema slots")
    if "func requiredDescriptorIndicesForCustomSlots(" not in implement_surface_text:
        fail("windows-implement explicit custom vtable mapping must require the deepest descriptor per slot")
    if "func requireExplicitSchemaCustomVtbls(" not in implement_surface_text:
        fail("windows-implement schema-only factories must reject custom interfaces without vtables")
    if "func requireCompleteCustomVtbls(" not in implement_surface_text:
        fail("windows-implement explicit schema vtable arrays must reject missing custom slots")
    if "explicitCustomVtblArray(resolvedDescriptors, vtblPtrs)" not in implement_surface_text:
        fail("windows-implement schema vtable arrays must be normalized before runtime attachment")
    if "fallbackCustomVtbl" in implement_surface_text:
        fail("windows-implement must not silently fallback missing custom vtables to IUnknown")
    schema_vtable_test = workspace / "windows-implement" / "src" / "schema_vtable_test.cj"
    check_path_exists(schema_vtable_test, "windows-implement schema vtable guard test")
    if "testSchemaOnlyCustomInterfacesRequireExplicitVtables" not in schema_vtable_test.read_text(encoding="utf-8"):
        fail("windows-implement must test schema-only custom interface rejection")
    if "Array<CPointer<Unit>>(0" not in schema_vtable_test.read_text(encoding="utf-8") or "[CPointer<Unit>()]" not in schema_vtable_test.read_text(encoding="utf-8"):
        fail("windows-implement must test missing explicit schema vtable rejection")
    if "testInheritedCustomInterfacesRequireLeafVtable" not in schema_vtable_test.read_text(encoding="utf-8"):
        fail("windows-implement must test that inherited custom slots require leaf vtables")
    if "testQueryInterfacePrefersExactDescriptorBeforeAncestorMatch" not in schema_vtable_test.read_text(encoding="utf-8"):
        fail("windows-implement must test exact QueryInterface matching before ancestor fallback")
    if "testInheritedCustomInterfacesGroupThroughOmittedIntermediate" not in schema_vtable_test.read_text(encoding="utf-8"):
        fail("windows-implement must test inherited slot grouping when intermediate descriptors are omitted")
    if "testDirectBaseIidSchemasGroupThroughListedIntermediate" not in schema_vtable_test.read_text(encoding="utf-8"):
        fail("windows-implement must test direct-base-IID inheritance slot grouping")
    macro_inherited_fixture = (workspace / "windows-interface" / "tests" / "macros" / "interface_implement_fixture.cj").read_text(encoding="utf-8")
    if "@Implement[IFixtureBase, IFixtureDerived]" not in macro_inherited_fixture:
        fail("windows-interface macro fixtures must cover inherited @Implement vtable slot mapping")
    if "inheritedDerived.DerivedValue" not in macro_inherited_fixture:
        fail("windows-interface inherited macro fixture must dispatch through the derived interface")
    if "@Implement[IFixtureSecondDerived]" not in macro_inherited_fixture:
        fail("windows-interface macro fixtures must cover inherited default thunk dispatch")
    if "SecondBaseValue" not in macro_inherited_fixture or "__winrtThunk_SecondBaseValue" in macro_inherited_fixture:
        fail("windows-interface inherited macro fixture must rely on the generated default base thunk")
    factory_cache_text = (workspace / "windows-core" / "src" / "factory_cache.cj").read_text(encoding="utf-8")
    if "classId.asRaw()" in factory_cache_text:
        fail("windows-core activation factory loading must publish class IDs as system HSTRING copies")
    if "callRoGetActivationFactoryWithClassId" not in factory_cache_text or "callDllGetActivationFactory" not in factory_cache_text:
        fail("windows-core activation factory loading must centralize HSTRING input projection")
    if "winrtBorrowGenericIn<HString>(classId)" not in factory_cache_text:
        fail("windows-core activation factory loading must borrow class IDs as system HSTRING copies")
    winui_xaml_text = (workspace / "windows-winui3" / "src" / "xaml" / "mod.cj").read_text(encoding="utf-8")
    for pattern in (
        "table.SetTitle(raw, title.asRaw())",
        "table.FindName(framework, text.asRaw(),",
        "table.Load(statics.asRaw(), xaml.asRaw(),",
    ):
        if pattern in winui_xaml_text:
            fail("windows-winui3 manual WinRT HSTRING inputs must use system HSTRING input borrows")
    for pattern in (
        "winrtBorrowGenericIn<HString>(title)",
        "winrtBorrowGenericIn<HString>(text)",
        "winrtBorrowGenericIn<HString>(xaml)",
    ):
        if pattern not in winui_xaml_text:
            fail("windows-winui3 manual WinRT HSTRING inputs must borrow system HSTRING copies")
    for pattern in (
        "ApplicationInitializationCallbackObject",
        "IUnknownVtbl",
        "IID_APPLICATION_INITIALIZATION_CALLBACK",
        "applicationInitializationCallbackInvoke",
        "table.Start(statics.asRaw(), callback.asRaw())",
        "deactivateApplicationInitializationCallbackObject(raw)",
        "applicationInitializationCallbackRelease(raw)",
    ):
        if pattern not in winui_xaml_text:
            fail("windows-winui3 Application.Start must pass a real WinRT delegate COM object")
    if "let _ = HRESULT(unsafe { table.RemoveClick" in winui_xaml_text:
        fail("windows-winui3 ClickSubscription.close must propagate RemoveClick HRESULT failures")
    click_subscription_close = section_between(
        winui_xaml_text,
        "public class ClickSubscription",
        "public func startApplication",
        "windows-winui3 ClickSubscription",
    )
    for pattern in (
        "checkHRESULT(HRESULT(unsafe { table.RemoveClick",
        "} finally {",
        "routed.close()",
        "ownedTarget.close()",
        "closed = true",
    ):
        if pattern not in click_subscription_close:
            fail("windows-winui3 ClickSubscription.close must clean local owners even when RemoveClick fails")
    for pattern in (
        "ApplicationInitializationCallback({",
        "CFunc<(CPointer<Unit>) -> Unit>",
        "table.Start(statics.asRaw(), callback.handler)",
    ):
        if pattern in winui_xaml_text:
            fail("windows-winui3 Application.Start must not use function-pointer delegate shims")
    check_winui_xaml_failed_out_cleanup(workspace)
    foundation_runtime_text = (workspace / "windows-runtime" / "src" / "foundation_runtime.cj").read_text(encoding="utf-8")
    for pattern in (
        "v.GetActivationFactory(asRaw(), activatableClassId.asRaw(),",
        "v.UnescapeComponent(asRaw(), toUnescape.asRaw(),",
        "v.EscapeComponent(asRaw(), toEscape.asRaw(),",
        "v.GetFirstValueByName(asRaw(), name.asRaw(),",
        "v.CreateString(asRaw(), value.asRaw(),",
        "v.CombineUri(asRaw(), relativeUri.asRaw(),",
        "v.CreateUri(asRaw(), uri.asRaw(),",
        "v.CreateWithRelativeUri(asRaw(), baseUri.asRaw(), relativeUri.asRaw(),",
        "v.CreateWwwFormUrlDecoder(asRaw(), query.asRaw(),",
    ):
        if pattern in foundation_runtime_text:
            fail("windows-runtime direct HSTRING inputs must use system HSTRING input borrows")
    for source in (workspace / "windows-runtime" / "src").rglob("*.cj"):
        text = source.read_text(encoding="utf-8")
        if "windows_core.HString.fromAbiTake(result__)" in text:
            fail(f"{source.relative_to(workspace)} must consume returned HSTRING handles with fromSystemHandleTake")
        if "windows_core.HString.viewOf(arg" in text:
            fail(f"{source.relative_to(workspace)} must project borrowed HSTRING inputs with fromSystemHandleCopy")
        if "let raw = value.intoRaw()" in text:
            fail(f"{source.relative_to(workspace)} must publish HSTRING out parameters as system HSTRING copies")

    common_com_helpers = workspace / "windows-common" / "src" / "Win32" / "System" / "Com" / "native_helpers.cj"
    if common_com_helpers.exists():
        common_com_text = common_com_helpers.read_text(encoding="utf-8")
        for pattern in (
            r"CoCreateInstance\([^\n]*ppv: CPointer<Unit>\)",
            r"CreateDataCache\([^\n]*ppv: CPointer<Unit>\)",
            r"BindMoniker\([^\n]*ppvResult: CPointer<Unit>\)",
            r"CoGetClassObject\([^\n]*ppv: CPointer<Unit>\)",
        ):
            if re.search(pattern, common_com_text):
                fail("windows-common COM native helpers must preserve pointer-to-pointer out slots")

    interface_src = workspace / "windows-interface" / "src"
    for source in interface_src.rglob("*.cj"):
        text = source.read_text(encoding="utf-8")
        if "windows_libloading" in text or "resolveProc(" in text:
            fail(f"{source.relative_to(workspace)} must stay free of native symbol loading")

    for member in sorted(ACTIVE_WORKSPACE_MEMBERS):
        src_root = workspace / member / "src"
        if not src_root.exists():
            continue
        for source in src_root.rglob("*.cj"):
            text = source.read_text(encoding="utf-8")
            if "windows_libloading" in text and "resolveProc" in text and LOCAL_NATIVE_PROC_CACHE_RE.search(text):
                fail(f"{source.relative_to(workspace)} must rely on windows_libloading proc caching")

    libloading = workspace / "windows-libloading" / "src" / "lib.cj"
    libloading_text = libloading.read_text(encoding="utf-8")
    if "LoadLibraryA" in libloading_text:
        fail("windows-libloading must use LoadLibraryExA with an explicit system DLL search policy")
    if "LOAD_LIBRARY_SEARCH_SYSTEM32" not in libloading_text:
        fail("windows-libloading must use a System32-only search policy for system DLLs")
    if "LOAD_LIBRARY_SEARCH_DEFAULT_DIRS" not in libloading_text or "resolveProcFromSearchPath" not in libloading_text:
        fail("windows-libloading must expose an explicit search-path API for app-local DLL loading")
    if "LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR" not in libloading_text or "searchPathLoadFlags(moduleName)" not in libloading_text:
        fail("windows-libloading explicit search-path loads must preserve absolute DLL directories for dependencies")
    if "ensureSystemModuleNameBytes(moduleNameBytes)" not in libloading_text or "isPathLikeModuleName(moduleName)" not in libloading_text:
        fail("windows-libloading system DLL loading must reject path-like module names")
    load_library_section = section_between(
        libloading_text,
        "public func loadLibrary(",
        "public func resolveProc(",
        "windows-libloading loadLibrary",
    )
    if "loadSystemLibraryUncached(moduleNameBytes)" not in load_library_section:
        fail("windows-libloading loadLibrary must load bare system DLLs from System32")
    load_library_locked_section = section_between(
        libloading_text,
        "func loadLibraryLocked(",
        "func loadLibraryFromSearchPathLocked(",
        "windows-libloading loadLibraryLocked",
    )
    if "loadSystemLibraryUncached(moduleNameBytes)" not in load_library_locked_section:
        fail("windows-libloading resolveProc must load bare system DLLs from System32")
    native_helpers_text = (workspace / "windows-bindgen" / "src" / "native_helpers.cj").read_text(encoding="utf-8")
    if "resolveProc(${spec.dynamicModuleParameterName}" in native_helpers_text:
        fail("windows-bindgen dynamic native helpers must use the explicit search-path resolver")
    app_runtime_helpers = workspace / "windows-common" / "src" / "Native" / "AppRuntime" / "native_helpers.cj"
    check_path_exists(app_runtime_helpers, "windows-common AppRuntime native helpers")
    app_runtime_text = app_runtime_helpers.read_text(encoding="utf-8")
    if "resolveProc(bootstrapDllPath" in app_runtime_text:
        fail("windows-common AppRuntime helpers must use the explicit search-path resolver")
    if app_runtime_text.count("resolveProcFromSearchPath(bootstrapDllPath") < 2:
        fail("windows-common AppRuntime helpers must resolve bootstrap exports via the explicit search-path resolver")
    if "MddBootstrapInitialize2" not in app_runtime_text or "MddBootstrapShutdown" not in app_runtime_text:
        fail("windows-common AppRuntime helpers must include both bootstrap exports")
    common_com_helpers = workspace / "windows-common" / "src" / "Win32" / "System" / "Com" / "native_helpers.cj"
    common_com_helpers_text = common_com_helpers.read_text(encoding="utf-8")
    if "public func CoTaskMemAlloc(cb: UIntNative): CPointer<Unit>" not in common_com_helpers_text:
        fail("windows-common CoTaskMemAlloc helper must expose SIZE_T byte count as UIntNative")
    if "public func CoTaskMemRealloc(pv: CPointer<Unit>, cb: UIntNative): CPointer<Unit>" not in common_com_helpers_text:
        fail("windows-common CoTaskMemRealloc helper must expose SIZE_T byte count as UIntNative")

    core_native = workspace / "windows-core" / "src" / "native.cj"
    core_native_text = core_native.read_text(encoding="utf-8")
    for primitive in ("GetProcAddress", "LoadLibraryExA", "FreeLibrary"):
        if f"func {primitive}(" in core_native_text:
            fail(f"windows-core native helpers must not wrap {primitive}; use windows-libloading")

    result_bindings = workspace / "windows-result" / "src" / "bindings.cj"
    result_bindings_text = result_bindings.read_text(encoding="utf-8")
    if "func LoadLibraryExA(" in result_bindings_text:
        fail("windows-result must reuse windows-libloading for module loading")


def check_active_tools(workspace: Path) -> None:
    generator_main = workspace / "windows-bindgen" / "src" / "main.cj"
    check_path_exists(generator_main, "Cangjie bindgen CLI")
    generator_main_text = generator_main.read_text(encoding="utf-8")
    if "writer.fileHashes()" not in generator_main_text or "file_hashes" not in generator_main_text:
        fail("windows-bindgen must generate manifest file_hashes for reproducible windows-common output")
    check_path_exists(workspace / "windows-bindgen" / "src" / "json_loader.cj", "JSON loader")
    check_path_exists(workspace / "winmd-to-json" / "Program.cs", "winmd-to-json source")
    check_path_exists(workspace / "windows-winui3" / "src" / "xaml" / "mod.cj", "WinUI3 XAML helper")
    runtime_runner = workspace / "scripts" / "run_windows_runtime_tests.py"
    check_path_exists(runtime_runner, "windows-runtime watchdog test runner")
    workspace_runner = workspace / "scripts" / "run_windows_workspace_tests.py"
    check_path_exists(workspace_runner, "workspace direct-binary test runner")
    workspace_runner_text = workspace_runner.read_text(encoding="utf-8")
    if "cjv\", \"exec\"" not in workspace_runner_text or "--no-run" not in workspace_runner_text:
        fail("workspace test runner must build with cjpm --no-run and execute binaries through cjv exec")
    if "cjHeapSize" not in workspace_runner_text or "32GB" not in workspace_runner_text:
        fail("workspace test runner must force cjHeapSize=32GB")
    if "FAILED" not in workspace_runner_text or "ERROR" not in workspace_runner_text or "summary_counts" not in workspace_runner_text:
        fail("workspace test runner must fail on unittest FAILED/ERROR summary counts")
    if "test_package_names" not in workspace_runner_text or "remove_expected_test_binaries" not in workspace_runner_text:
        fail("workspace test runner must execute exact package unittest binaries without stale prefix matches")
    demo_root = workspace.parent / "windows-cj-demo"
    if demo_root.exists():
        demo_cjpm = (demo_root / "cjpm.toml").read_text(encoding="utf-8")
        removed_generated_dep = "windows" + '_gen = { path = "../windows-cj/.generated/windows" }'
        if removed_generated_dep in demo_cjpm:
            fail("windows-cj-demo must not depend on the removed .generated/windows package")
        if 'windows_winui3 = { path = "../windows-cj/windows-winui3" }' not in demo_cjpm:
            fail("windows-cj-demo must depend on the maintained windows_winui3 package")
        smoke = demo_root / "tools" / "smoke_winui3.py"
        check_path_exists(smoke, "windows-cj-demo WinUI smoke script")
        smoke_text = smoke.read_text(encoding="utf-8")
        if '"cjv", "exec", "+mem"' not in smoke_text:
            fail("windows-cj-demo smoke script must execute the demo through cjv exec")
        if "[demo] Window activated" not in smoke_text or "timed out before window activation" not in smoke_text:
            fail("windows-cj-demo smoke script must fail if Application.Start never activates a window")
        if "def report_result" not in smoke_text or "missing window activation marker" not in smoke_text:
            fail("windows-cj-demo smoke script must check window activation even when the process exits successfully")


def check_windows_targets_payload(workspace: Path) -> None:
    targets_root = workspace / "windows-targets"
    lib_source = (targets_root / "src" / "lib.cj").read_text(encoding="utf-8")
    version_match = re.search(r'private let bundledVersion = "([^"]+)"', lib_source)
    archive_match = re.search(r'private let bundledGnuArchive = "([^"]+)"', lib_source)
    if version_match is None or archive_match is None:
        fail("windows-targets must publish bundled version and GNU archive metadata")
    version = version_match.group(1)
    archive_name = archive_match.group(1)
    if archive_name != f"libwindows.{version}.a":
        fail("windows-targets default GNU archive name must match bundled version")
    entry_re = re.compile(
        r'importLibTarget\(\s*"(?P<name>[^"]+)",\s*"(?P<arch>[^"]+)",\s*'
        r'"(?P<toolchain>[^"]+)",\s*"(?P<env>[^"]*)",\s*"(?P<directory>[^"]+)",\s*'
        r'(?P<archive>Some\((?P<archive_value>bundledGnuArchive|"[^"]+")\)|None),\s*'
        r'(?P<supported>true|false)\s*\)',
        re.DOTALL,
    )
    entries = []
    for match in entry_re.finditer(lib_source):
        archive_expr = match.group("archive")
        parsed_archive_name = None
        if archive_expr != "None":
            archive_value = match.group("archive_value")
            parsed_archive_name = archive_name if archive_value == "bundledGnuArchive" else archive_value.strip('"')
        entries.append(
            {
                "name": match.group("name"),
                "directory": match.group("directory"),
                "archive": parsed_archive_name,
                "supported": match.group("supported") == "true",
            }
        )

    expected_targets = {
        "x86_64_gnu",
        "i686_gnu",
        "aarch64_gnu",
        "x86_64_msvc",
        "i686_msvc",
        "aarch64_msvc",
    }
    actual_targets = {entry["name"] for entry in entries}
    if actual_targets != expected_targets:
        missing = sorted(expected_targets - actual_targets)
        extra = sorted(actual_targets - expected_targets)
        fail(f"windows-targets import library matrix mismatch; missing={missing}, extra={extra}")

    declared_payloads: set[Path] = set()
    for entry in entries:
        if entry["supported"]:
            if entry["archive"] is None:
                fail(f"windows-targets supported target lacks archive metadata: {entry['name']}")
            archive_path = targets_root / entry["directory"] / entry["archive"]
            declared_payloads.add(Path(entry["directory"]) / entry["archive"])
            if not archive_path.exists():
                fail(f"windows-targets bundled archive is missing: {archive_path.relative_to(workspace)}")
            if archive_path.stat().st_size == 0:
                fail(f"windows-targets bundled archive is empty: {archive_path.relative_to(workspace)}")
        elif entry["archive"] is not None:
            fail(f"windows-targets planned target must not claim a missing archive: {entry['name']}")

    actual_payloads = {
        path.relative_to(targets_root)
        for path in targets_root.glob("*/lib/*")
        if path.is_file()
    }
    unexpected_payloads = sorted(actual_payloads - declared_payloads)
    if unexpected_payloads:
        rendered = ", ".join(path.as_posix() for path in unexpected_payloads)
        fail(f"windows-targets archive payload exists outside supported matrix: {rendered}")


def check_ignored_results(workspace: Path) -> None:
    script = workspace / "scripts" / "check_ignored_results.py"
    check_path_exists(script, "ignored-results audit script")
    result = subprocess.run(
        [sys.executable, str(script)],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        fail(f"check_ignored_results.py failed:\n{result.stdout}{result.stderr}")


def check_abi_ownership(workspace: Path) -> None:
    script = workspace / "scripts" / "check_abi_ownership.py"
    check_path_exists(script, "ABI ownership audit script")
    result = subprocess.run(
        [sys.executable, str(script)],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        fail(f"check_abi_ownership.py failed:\n{result.stdout}{result.stderr}")


def main() -> None:
    workspace = Path(__file__).resolve().parent.parent
    print(f"workspace = {workspace}")
    check_no_shell_scripts(workspace)
    print("OK: automation gate rejects shell/PowerShell/batch scripts")
    check_workspace_members(workspace)
    print("OK: active workspace members match JSON-backed layout")
    check_reference_only_packages(workspace)
    print("OK: reference-only packages live under deprecated_windows_cj")
    check_generated_common_package(workspace)
    print("OK: generated windows-common package is present and marked DO NOT EDIT")
    check_package_boundaries(workspace)
    print("OK: package dependency and native helper boundaries are explicit")
    check_active_tools(workspace)
    print("OK: active Cangjie generator and WinUI helper files are present")
    check_windows_targets_payload(workspace)
    print("OK: windows-targets import library matrix matches payload")
    check_test_com_object_owners_released(workspace)
    print("OK: test COM object owners release their base references")
    check_temporary_com_object_projection_ownership(workspace)
    print("OK: temporary COM object projections consume or release owner references")
    check_threading_pools_use_scope_or_explicit_close(workspace)
    print("OK: thread pools use scope or explicit close in production sources")
    check_finalizers_do_not_block_on_locks(workspace)
    print("OK: finalizers do not use blocking cleanup paths")
    check_windows_string_finalizer_paths_are_lock_free(workspace)
    print("OK: windows-strings finalizer release paths are lock-free")
    check_long_lived_vtables_are_unmanaged(workspace)
    print("OK: long-lived vtables use unmanaged native storage")
    check_native_allocations_have_deterministic_owner(workspace)
    print("OK: native allocated class storage has deterministic owners")
    check_collection_indexof_thunks_reject_null_index(workspace)
    print("OK: collection IndexOf thunks reject null index out pointers")
    check_array_materialization_cleanup(workspace)
    print("OK: array materialization cleanup paths are statically covered")
    check_ignored_results(workspace)
    print("OK: no ignored HRESULT/Result.ok() values in active .cj sources")
    check_abi_ownership(workspace)
    print("OK: ABI ownership and QueryInterface result invariants hold")


if __name__ == "__main__":
    main()
