#!/usr/bin/env python3
"""Verify the active windows-cj workspace layout.

This script intentionally checks the current JSON-backed Cangjie generator
layout. Legacy cfg-era and Python bindgen packages must live outside this
workspace under the sibling deprecated_windows_cj directory.
"""

from __future__ import annotations

import sys
import tomllib
import ast
import hashlib
import json
import re
from pathlib import Path


ACTIVE_WORKSPACE_MEMBERS = {
    "windows-metadata",
    "windows-libloading",
    "windows-result",
    "windows-strings",
    "windows-interface",
    "windows-implement",
    "windows-core",
    "windows-polyfill",
    "windows-runtime",
    "windows-threading",
    "windows-version",
    "windows-targets",
    "windows-registry",
    "windows-services",
    "windows-common",
    "windows-winui3",
    "windows",
}

REFERENCE_ONLY_PACKAGES = {
    "windows-sys",
    "windows-webview2-sys",
    "windows-appsdk-sys",
    "windows-webview2",
    "windows-appsdk",
    "windows-bindgen",
    "windows-bindgen-legacy",
    "windows-cfggen",
    "windows-cfggen-legacy",
    "windows-cj-bindgen-py",
    "windows-cj-cfggen-py",
}

PACKAGE_DEPENDENCIES = {
    "windows": set(),
    "windows_common": {
        "windows_core",
        "windows_interface",
        "windows_libloading",
        "windows_polyfill",
        "windows_strings",
    },
    "windows_core": {
        "windows_implement",
        "windows_interface",
        "windows_libloading",
        "windows_result",
        "windows_strings",
    },
    "windows_implement": {
        "windows_interface",
        "windows_libloading",
        "windows_result",
        "windows_strings",
    },
    "windows_interface": {
        "windows_result",
        "windows_strings",
    },
    "windows_libloading": set(),
    "windows_metadata": set(),
    "windows_polyfill": set(),
    "windows_registry": {
        "windows_common",
        "windows_result",
        "windows_strings",
    },
    "windows_result": {"windows_libloading"},
    "windows_runtime": {
        "windows_common",
        "windows_core",
        "windows_interface",
        "windows_strings",
    },
    "windows_services": {
        "windows_common",
        "windows_strings",
    },
    "windows_strings": {"windows_libloading"},
    "windows_targets": set(),
    "windows_threading": {"windows_common"},
    "windows_version": {
        "windows_common",
        "windows_strings",
    },
    "windows_winui3": {
        "windows_common",
        "windows_core",
    },
}

WINDOWS_IMPORT_RE = re.compile(
    r"^\s*(?:(?:public|private|internal|protected)\s+)?import\s+(windows_[A-Za-z0-9_]+)",
    re.MULTILINE,
)
LOCAL_NATIVE_PROC_CACHE_RE = re.compile(r"\bcached[A-Za-z0-9_]*\s*[:=].*CPointer<Unit>")
GENERATED_HEADER = "// Generated by windows-gen. DO NOT EDIT."
GENERATED_TOML_HEADER = "# Generated by windows-gen. DO NOT EDIT."
GENERATED_MANIFEST_HEADER = "Generated by windows-gen. DO NOT EDIT."
GENERATED_COMMON_IGNORED_FILES = {
    "cjpm.lock",
    "codegen-manifest.json",
}
GENERATED_COMMON_FORBIDDEN_IMPORTS = {
    "import windows_core.*",
    "import windows_interface.*",
    "import windows_interface.macros.*",
}
WINDOWS_INTERFACE_MACRO_TEST_IMPORTS = {"windows_core"}
WINDOWS_INTERFACE_MACRO_TEST_LINK_CLOSURE = {
    "windows_interface",
    "windows_implement",
    "windows_core",
    "windows_result",
    "windows_strings",
    "windows_libloading",
}
IGNORED_SHELL_SCRIPT_DIRS = {".git", "target"}


def fail(message: str) -> None:
    print(f"FAIL: {message}", file=sys.stderr)
    sys.exit(1)


def check_path_exists(path: Path, kind: str) -> None:
    if not path.exists():
        fail(f"missing {kind}: {path}")


def load_toml(path: Path) -> dict:
    with path.open("rb") as f:
        return tomllib.load(f)


def expected_dependency_path(dependency: str) -> str:
    return "../" + dependency.replace("_", "-")


def load_python_string_list(path: Path, name: str) -> list[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        for target in node.targets:
            if isinstance(target, ast.Name) and target.id == name:
                value = ast.literal_eval(node.value)
                if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
                    fail(f"{path.relative_to(path.parent.parent)} {name} must be a literal string list")
                return value
    fail(f"{path} must define {name}")


def rel_posix(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def section_between(text: str, start: str, end: str, label: str) -> str:
    start_index = text.find(start)
    if start_index < 0:
        fail(f"missing {label} start marker")
    end_index = text.find(end, start_index + len(start))
    if end_index < 0:
        fail(f"missing {label} end marker")
    return text[start_index:end_index]


def is_ignored_generated_path(path: Path, root: Path) -> bool:
    return any(part in IGNORED_SHELL_SCRIPT_DIRS for part in path.relative_to(root).parts)


def check_no_shell_scripts(workspace: Path) -> None:
    shell_scripts = sorted(
        rel_posix(path, workspace)
        for path in workspace.rglob("*.sh")
        if path.is_file() and not is_ignored_generated_path(path, workspace)
    )
    if shell_scripts:
        fail(f"shell scripts are not allowed in windows-cj; found={shell_scripts}")


def check_workspace_members(workspace: Path) -> None:
    config = load_toml(workspace / "cjpm.toml")
    members = set(config.get("workspace", {}).get("members", []))
    if members != ACTIVE_WORKSPACE_MEMBERS:
        missing = sorted(ACTIVE_WORKSPACE_MEMBERS - members)
        extra = sorted(members - ACTIVE_WORKSPACE_MEMBERS)
        fail(f"workspace members mismatch; missing={missing}, extra={extra}")
    for member in sorted(members):
        root = workspace / member
        check_path_exists(root / "cjpm.toml", f"{member} cjpm.toml")
        check_path_exists(root / "src", f"{member} src/")

    package_roots = {
        child.name
        for child in workspace.iterdir()
        if child.is_dir() and (child / "cjpm.toml").exists()
    }
    extra_package_roots = sorted(package_roots - ACTIVE_WORKSPACE_MEMBERS)
    if extra_package_roots:
        fail(f"unexpected root package directories in windows-cj: {extra_package_roots}")


def check_reference_only_packages(workspace: Path) -> None:
    deprecated_root = workspace.parent / "deprecated_windows_cj"
    check_path_exists(deprecated_root, "deprecated_windows_cj root")
    for name in sorted(REFERENCE_ONLY_PACKAGES):
        active_root = workspace / name
        if active_root.exists():
            fail(f"{name} must be moved out of windows-cj; found {active_root}")
        archived_root = deprecated_root / name
        check_path_exists(archived_root, f"{name} deprecated reference root")
        check_path_exists(archived_root / "REFERENCE_ONLY.md", f"{name} REFERENCE_ONLY.md")


def check_generated_common_package(workspace: Path) -> None:
    generated = workspace / "windows-common"
    check_path_exists(generated / "cjpm.toml", "windows-common cjpm.toml")
    check_path_exists(generated / "codegen-manifest.json", "windows-common codegen-manifest.json")
    support_deps = generated / "src" / "support_deps.cj"
    check_path_exists(support_deps, "windows-common support_deps.cj")
    check_path_exists(generated / "src" / "mod.cj", "windows-common mod.cj")
    manifest = json.loads((generated / "codegen-manifest.json").read_text(encoding="utf-8"))
    if manifest.get("generated_by") != GENERATED_MANIFEST_HEADER:
        fail("windows-common codegen manifest must identify windows-gen as its source")
    manifest_file_list = manifest.get("files") or []
    if len(manifest_file_list) != len(set(manifest_file_list)):
        fail("windows-common codegen manifest must not contain duplicate file entries")
    manifest_files = set(manifest_file_list)
    if not manifest_files:
        fail("windows-common codegen manifest must list generated files")
    manifest_hashes = manifest.get("file_hashes")
    if not isinstance(manifest_hashes, dict):
        fail("windows-common codegen manifest must include per-file content hashes")
    manifest_hash_files = set(manifest_hashes.keys())
    if manifest_hash_files != manifest_files:
        missing = sorted(manifest_files - manifest_hash_files)
        extra = sorted(manifest_hash_files - manifest_files)
        fail(f"windows-common codegen manifest hash key mismatch; missing={missing}, extra={extra}")

    actual_files = set()
    for file in generated.rglob("*"):
        if not file.is_file():
            continue
        relative = rel_posix(file, generated)
        if relative.startswith("target/") or relative in GENERATED_COMMON_IGNORED_FILES:
            continue
        actual_files.add(relative)

    if actual_files != manifest_files:
        missing = sorted(manifest_files - actual_files)
        extra = sorted(actual_files - manifest_files)
        fail(f"windows-common generated file set mismatch; missing={missing}, extra={extra}")

    for relative in sorted(manifest_files):
        file = generated / relative
        actual_hash = hashlib.sha256(file.read_bytes()).hexdigest()
        expected_hash = manifest_hashes.get(relative)
        if expected_hash != actual_hash:
            fail(f"{relative} content hash does not match windows-common codegen manifest")
        if file.suffix == ".cj":
            text = file.read_text(encoding="utf-8")
            first_line = text.splitlines()[0]
            if first_line != GENERATED_HEADER:
                fail(f"{relative} must start with the generated-by header")
            for forbidden_import in GENERATED_COMMON_FORBIDDEN_IMPORTS:
                if forbidden_import in text:
                    fail(f"{relative} must use explicit imports instead of {forbidden_import}")
        elif file.suffix == ".toml":
            first_line = file.read_text(encoding="utf-8").splitlines()[0]
            if first_line != GENERATED_TOML_HEADER:
                fail(f"{relative} must start with the generated-by header")

    config = load_toml(generated / "cjpm.toml")
    package = config.get("package", {})
    if package.get("name") != "windows_common":
        fail(f"windows-common package name must be windows_common, got {package.get('name')!r}")
    if manifest.get("package_name") != "windows_common":
        fail(f"windows-common manifest package name must be windows_common, got {manifest.get('package_name')!r}")
    support_imports = set(WINDOWS_IMPORT_RE.findall(support_deps.read_text(encoding="utf-8")))
    expected_support_imports = PACKAGE_DEPENDENCIES["windows_common"]
    if support_imports != expected_support_imports:
        missing = sorted(expected_support_imports - support_imports)
        extra = sorted(support_imports - expected_support_imports)
        fail(f"windows-common support_deps imports mismatch; missing={missing}, extra={extra}")
    if "link-option" in (generated / "cjpm.toml").read_text(encoding="utf-8"):
        fail("windows-common must not emit static link options; native calls go through windows_libloading")


def check_cj_import_boundaries(workspace: Path, root: Path, allowed_imports: set[str]) -> None:
    if not root.exists():
        return
    for source in root.rglob("*.cj"):
        text = source.read_text(encoding="utf-8")
        for imported in WINDOWS_IMPORT_RE.findall(text):
            if imported not in allowed_imports:
                fail(f"{source.relative_to(workspace)} imports {imported} without a declared boundary")


def check_package_boundaries(workspace: Path) -> None:
    for member in sorted(ACTIVE_WORKSPACE_MEMBERS):
        root = workspace / member
        config = load_toml(root / "cjpm.toml")
        package_name = config.get("package", {}).get("name")
        if package_name not in PACKAGE_DEPENDENCIES:
            fail(f"{member} has no package dependency rule")

        expected_deps = PACKAGE_DEPENDENCIES[package_name]
        actual_deps = set((config.get("dependencies") or {}).keys())
        if actual_deps != expected_deps:
            missing = sorted(expected_deps - actual_deps)
            extra = sorted(actual_deps - expected_deps)
            fail(f"{member} dependencies mismatch; missing={missing}, extra={extra}")
        for dependency in sorted(actual_deps):
            dependency_config = config.get("dependencies", {}).get(dependency)
            if not isinstance(dependency_config, dict):
                fail(f"{member} dependency {dependency} must use a local path table")
            expected_path = expected_dependency_path(dependency)
            if dependency_config.get("path") != expected_path:
                fail(
                    f"{member} dependency {dependency} must point at {expected_path}, "
                    f"got {dependency_config.get('path')!r}"
                )

        src_root = root / "src"
        if not src_root.exists():
            continue

        allowed_imports = expected_deps | {package_name}
        check_cj_import_boundaries(workspace, src_root, allowed_imports)

    macro_tests = workspace / "windows-interface" / "tests"
    check_path_exists(macro_tests, "windows-interface macro tests")
    macro_fixtures = sorted((macro_tests / "macros").glob("*.cj"))
    if not macro_fixtures:
        fail("windows-interface macro tests must include at least one .cj fixture")
    check_cj_import_boundaries(
        workspace,
        macro_tests,
        PACKAGE_DEPENDENCIES["windows_interface"]
        | {"windows_interface"}
        | WINDOWS_INTERFACE_MACRO_TEST_IMPORTS,
    )
    macro_check = workspace / "windows-interface" / "scripts" / "check_macros.py"
    check_path_exists(macro_check, "windows-interface macro check script")
    macro_import_packages = set(load_python_string_list(macro_check, "IMPORT_PACKAGES"))
    if macro_import_packages != WINDOWS_INTERFACE_MACRO_TEST_LINK_CLOSURE:
        missing = sorted(WINDOWS_INTERFACE_MACRO_TEST_LINK_CLOSURE - macro_import_packages)
        extra = sorted(macro_import_packages - WINDOWS_INTERFACE_MACRO_TEST_LINK_CLOSURE)
        fail(f"windows-interface macro test link closure mismatch; missing={missing}, extra={extra}")

    interface_native = workspace / "windows-interface" / "src" / "native.cj"
    if interface_native.exists():
        fail("implementation native helpers must not live in windows-interface/src/native.cj")

    implement_native = workspace / "windows-implement" / "src" / "native.cj"
    check_path_exists(implement_native, "windows-implement native helper")
    implement_native_text = implement_native.read_text(encoding="utf-8")
    if "CoCreateFreeThreadedMarshaler" not in implement_native_text:
        fail("windows-implement native helper must own CoCreateFreeThreadedMarshaler")

    com_registry = workspace / "windows-implement" / "src" / "com_registry.cj"
    com_registry_text = com_registry.read_text(encoding="utf-8")
    if ".lock()" in com_registry_text or ".unlock()" in com_registry_text:
        fail("windows-implement COM registries must use synchronized blocks instead of manual lock/unlock")

    hstring_ref_count = workspace / "windows-strings" / "src" / "ref_count.cj"
    hstring_ref_count_text = hstring_ref_count.read_text(encoding="utf-8")
    if ".lock()" in hstring_ref_count_text or ".unlock()" in hstring_ref_count_text:
        fail("windows-strings HSTRING refcount state must use synchronized blocks")
    bstr_text = (workspace / "windows-strings" / "src" / "bstr.cj").read_text(encoding="utf-8")
    if "unsafeFromRaw" in bstr_text or "unsafeAttach" in bstr_text:
        fail("windows-strings BSTR raw constructors must describe ownership instead of using unsafe* names")
    for source in (workspace / "windows-strings" / "src").rglob("*.cj"):
        if "Unsafe:" in source.read_text(encoding="utf-8"):
            fail(f"{source.relative_to(workspace)} must document caller guarantees without unsafe-style API labels")
    strings_native = workspace / "windows-strings" / "src" / "native.cj"
    check_path_exists(strings_native, "windows-strings native helper")
    for source in (workspace / "windows-strings" / "src").rglob("*.cj"):
        text = source.read_text(encoding="utf-8")
        if source != strings_native and "windows_libloading" in text:
            fail(f"{source.relative_to(workspace)} must use windows-strings native helpers instead of loading symbols directly")

    threading_lib = workspace / "windows-threading" / "src" / "lib.cj"
    threading_lib_text = threading_lib.read_text(encoding="utf-8")
    if ".lock()" in threading_lib_text or ".unlock()" in threading_lib_text:
        fail("windows-threading state guards must use synchronized blocks")

    services_lib = workspace / "windows-services" / "src" / "lib.cj"
    services_lib_text = services_lib.read_text(encoding="utf-8")
    if ".lock()" in services_lib_text or ".unlock()" in services_lib_text:
        fail("windows-services state guards must use synchronized blocks")

    runtime_async = workspace / "windows-runtime" / "src" / "async_helpers.cj"
    runtime_async_text = runtime_async.read_text(encoding="utf-8")
    if ".lock()" in runtime_async_text or ".unlock()" in runtime_async_text:
        fail("windows-runtime async state guards must use synchronized blocks")

    core_type_impl = workspace / "windows-core" / "src" / "type_impl.cj"
    core_type_impl_text = core_type_impl.read_text(encoding="utf-8")
    if "fromAbiTakeWinrtHandle(raw: CPointer<Unit>): HString { HString.fromAbiTake(raw) }" in core_type_impl_text:
        fail("windows-core HString WinRT out handles must use system HSTRING ownership")
    if "viewWinrtHandle(raw: CPointer<Unit>): HString { HString.viewOf(raw) }" in core_type_impl_text:
        fail("windows-core HString WinRT input handles must copy borrowed system HSTRINGs")
    if "intoWinrtHandle(value: HString): CPointer<Unit> { value.asRaw() }" in core_type_impl_text:
        fail("windows-core HString WinRT handles must publish system HSTRING copies")
    core_ref_param_text = (workspace / "windows-core" / "src" / "ref_param.cj").read_text(encoding="utf-8")
    if "case hstring: HString" in core_ref_param_text and "hstring.asRaw()" in core_ref_param_text:
        fail("windows-core InParam<HString> must not publish project-managed HSTRING handles")
    winrt_generic_text = (workspace / "windows-core" / "src" / "winrt_generic.cj").read_text(encoding="utf-8")
    if "SystemHStringWinrtInputBorrow" not in winrt_generic_text or "borrowedWinrtInputHandle<T>(value)" not in winrt_generic_text:
        fail("windows-core HString generic input borrows must publish system HSTRING copies")
    hstring_borrow_section = section_between(
        winrt_generic_text,
        "class SystemHStringWinrtInputBorrow",
        "func borrowedWinrtInputHandle",
        "windows-core HString generic input borrow",
    )
    if "raw = value.toSystemHandleCopy()" not in hstring_borrow_section:
        fail("windows-core HString generic input borrow must create a system HSTRING copy")
    if "releaseSystemHStringHandle(handle)" not in hstring_borrow_section:
        fail("windows-core HString generic input borrow must release system HSTRING copies without allocating")
    if "HString.fromSystemHandleTake(raw).close()" in hstring_borrow_section:
        fail("windows-core HString generic input borrow release must not allocate while closing")
    owned_winrt_handle_section = section_between(
        winrt_generic_text,
        "func ownedWinrtOutHandle",
        "public open class WinrtOutputBridge",
        "windows-core HString generic output handle",
    )
    if "case hstring: HString" not in owned_winrt_handle_section or "hstring.toSystemHandleCopy()" not in owned_winrt_handle_section:
        fail("windows-core HString generic output handles must publish system HSTRING copies")
    if "hstring.asRaw()" in owned_winrt_handle_section or "hstring.clone().intoRaw()" in owned_winrt_handle_section:
        fail("windows-core HString generic output handles must not publish project-managed HSTRING storage")
    array_proxy_text = (workspace / "windows-core" / "src" / "array_proxy.cj").read_text(encoding="utf-8")
    if "value.intoRaw()" in array_proxy_text or "value.clone().intoRaw()" in array_proxy_text:
        fail("windows-core ArrayProxy must publish HString elements as system HSTRING copies")
    array_proxy_release_section = section_between(
        array_proxy_text,
        "func releasePublishedObjectSlots",
        "func publishCopyArray",
        "windows-core ArrayProxy object cleanup",
    )
    if "releaseSystemHStringHandle(raw)" not in array_proxy_release_section:
        fail("windows-core ArrayProxy must release system HSTRING slots without allocating")
    if "HString.fromSystemHandleTake(raw).close()" in array_proxy_release_section:
        fail("windows-core ArrayProxy cleanup must not allocate while releasing system HSTRING slots")
    interface_impl_surface_text = (workspace / "windows-implement" / "src" / "interface_impl_surface.cj").read_text(encoding="utf-8")
    runtime_name_section = section_between(
        interface_impl_surface_text,
        "public func getRuntimeClassNameBase",
        "public func getTrustLevelBase",
        "windows-implement GetRuntimeClassNameBase",
    )
    if "intoRaw" in runtime_name_section:
        fail("windows-implement GetRuntimeClassName must publish system HSTRING copies")
    if "toSystemHandleCopy()" not in runtime_name_section:
        fail("windows-implement GetRuntimeClassName must publish system HSTRING copies")
    implement_surface_text = interface_impl_surface_text
    descriptor_schema_text = (workspace / "windows-implement" / "src" / "descriptor_schema.cj").read_text(encoding="utf-8")
    if "public let vtableAncestorIids: Array<GUID>" not in descriptor_schema_text:
        fail("windows-implement descriptors must distinguish QI metadata from vtable inheritance metadata")
    if "func resolvedDescriptorVtableAncestorDepth(" not in descriptor_schema_text:
        fail("windows-implement slot assignment must compute effective vtable inheritance depth")
    if "func resolvedDescriptorIsComInterface(" not in descriptor_schema_text:
        fail("windows-implement slot assignment must infer COM inheritance through descriptor chains")
    if "func findDeepestDescendantIndex(" not in descriptor_schema_text or "descriptorContainsVtableAncestor(values, index, parent.iid)" not in descriptor_schema_text:
        fail("windows-implement slot assignment must group inherited slots through full ancestor chains")
    if "func explicitCustomVtblArray(" not in implement_surface_text:
        fail("windows-implement must map explicit custom vtables through resolved schema slots")
    if "func requiredDescriptorIndicesForCustomSlots(" not in implement_surface_text:
        fail("windows-implement explicit custom vtable mapping must require the deepest descriptor per slot")
    if "func requireExplicitSchemaCustomVtbls(" not in implement_surface_text:
        fail("windows-implement schema-only factories must reject custom interfaces without vtables")
    if "func requireCompleteCustomVtbls(" not in implement_surface_text:
        fail("windows-implement explicit schema vtable arrays must reject missing custom slots")
    if "explicitCustomVtblArray(resolvedDescriptors, vtblPtrs)" not in implement_surface_text:
        fail("windows-implement schema vtable arrays must be normalized before runtime attachment")
    if "fallbackCustomVtbl" in implement_surface_text:
        fail("windows-implement must not silently fallback missing custom vtables to IUnknown")
    schema_vtable_test = workspace / "windows-implement" / "src" / "schema_vtable_test.cj"
    check_path_exists(schema_vtable_test, "windows-implement schema vtable guard test")
    if "testSchemaOnlyCustomInterfacesRequireExplicitVtables" not in schema_vtable_test.read_text(encoding="utf-8"):
        fail("windows-implement must test schema-only custom interface rejection")
    if "Array<CPointer<Unit>>(0" not in schema_vtable_test.read_text(encoding="utf-8") or "[CPointer<Unit>()]" not in schema_vtable_test.read_text(encoding="utf-8"):
        fail("windows-implement must test missing explicit schema vtable rejection")
    if "testInheritedCustomInterfacesRequireLeafVtable" not in schema_vtable_test.read_text(encoding="utf-8"):
        fail("windows-implement must test that inherited custom slots require leaf vtables")
    if "testQueryInterfacePrefersExactDescriptorBeforeAncestorMatch" not in schema_vtable_test.read_text(encoding="utf-8"):
        fail("windows-implement must test exact QueryInterface matching before ancestor fallback")
    if "testInheritedCustomInterfacesGroupThroughOmittedIntermediate" not in schema_vtable_test.read_text(encoding="utf-8"):
        fail("windows-implement must test inherited slot grouping when intermediate descriptors are omitted")
    if "testDirectBaseIidSchemasGroupThroughListedIntermediate" not in schema_vtable_test.read_text(encoding="utf-8"):
        fail("windows-implement must test direct-base-IID inheritance slot grouping")
    macro_inherited_fixture = (workspace / "windows-interface" / "tests" / "macros" / "interface_implement_fixture.cj").read_text(encoding="utf-8")
    if "@Implement[IFixtureBase, IFixtureDerived]" not in macro_inherited_fixture:
        fail("windows-interface macro fixtures must cover inherited @Implement vtable slot mapping")
    if "inheritedDerived.DerivedValue" not in macro_inherited_fixture:
        fail("windows-interface inherited macro fixture must dispatch through the derived interface")
    if "@Implement[IFixtureSecondDerived]" not in macro_inherited_fixture:
        fail("windows-interface macro fixtures must cover inherited default thunk dispatch")
    if "SecondBaseValue" not in macro_inherited_fixture or "__winrtThunk_SecondBaseValue" in macro_inherited_fixture:
        fail("windows-interface inherited macro fixture must rely on the generated default base thunk")
    factory_cache_text = (workspace / "windows-core" / "src" / "factory_cache.cj").read_text(encoding="utf-8")
    if "classId.asRaw()" in factory_cache_text:
        fail("windows-core activation factory loading must publish class IDs as system HSTRING copies")
    if "callRoGetActivationFactoryWithClassId" not in factory_cache_text or "callDllGetActivationFactory" not in factory_cache_text:
        fail("windows-core activation factory loading must centralize HSTRING input projection")
    if "winrtBorrowGenericIn<HString>(classId)" not in factory_cache_text:
        fail("windows-core activation factory loading must borrow class IDs as system HSTRING copies")
    winui_xaml_text = (workspace / "windows-winui3" / "src" / "xaml" / "mod.cj").read_text(encoding="utf-8")
    for pattern in (
        "table.SetTitle(raw, title.asRaw())",
        "table.FindName(framework, text.asRaw(),",
        "table.Load(statics.asRaw(), xaml.asRaw(),",
    ):
        if pattern in winui_xaml_text:
            fail("windows-winui3 manual WinRT HSTRING inputs must use system HSTRING input borrows")
    for pattern in (
        "winrtBorrowGenericIn<HString>(title)",
        "winrtBorrowGenericIn<HString>(text)",
        "winrtBorrowGenericIn<HString>(xaml)",
    ):
        if pattern not in winui_xaml_text:
            fail("windows-winui3 manual WinRT HSTRING inputs must borrow system HSTRING copies")
    foundation_runtime_text = (workspace / "windows-runtime" / "src" / "foundation_runtime.cj").read_text(encoding="utf-8")
    for pattern in (
        "v.GetActivationFactory(asRaw(), activatableClassId.asRaw(),",
        "v.UnescapeComponent(asRaw(), toUnescape.asRaw(),",
        "v.EscapeComponent(asRaw(), toEscape.asRaw(),",
        "v.GetFirstValueByName(asRaw(), name.asRaw(),",
        "v.CreateString(asRaw(), value.asRaw(),",
        "v.CombineUri(asRaw(), relativeUri.asRaw(),",
        "v.CreateUri(asRaw(), uri.asRaw(),",
        "v.CreateWithRelativeUri(asRaw(), baseUri.asRaw(), relativeUri.asRaw(),",
        "v.CreateWwwFormUrlDecoder(asRaw(), query.asRaw(),",
    ):
        if pattern in foundation_runtime_text:
            fail("windows-runtime direct HSTRING inputs must use system HSTRING input borrows")
    for source in (workspace / "windows-runtime" / "src").rglob("*.cj"):
        text = source.read_text(encoding="utf-8")
        if "windows_core.HString.fromAbiTake(result__)" in text:
            fail(f"{source.relative_to(workspace)} must consume returned HSTRING handles with fromSystemHandleTake")
        if "windows_core.HString.viewOf(arg" in text:
            fail(f"{source.relative_to(workspace)} must project borrowed HSTRING inputs with fromSystemHandleCopy")
        if "let raw = value.intoRaw()" in text:
            fail(f"{source.relative_to(workspace)} must publish HSTRING out parameters as system HSTRING copies")

    common_com_helpers = workspace / "windows-common" / "src" / "Win32" / "System" / "Com" / "native_helpers.cj"
    if common_com_helpers.exists():
        common_com_text = common_com_helpers.read_text(encoding="utf-8")
        for pattern in (
            r"CoCreateInstance\([^\n]*ppv: CPointer<Unit>\)",
            r"CreateDataCache\([^\n]*ppv: CPointer<Unit>\)",
            r"BindMoniker\([^\n]*ppvResult: CPointer<Unit>\)",
            r"CoGetClassObject\([^\n]*ppv: CPointer<Unit>\)",
        ):
            if re.search(pattern, common_com_text):
                fail("windows-common COM native helpers must preserve pointer-to-pointer out slots")

    interface_src = workspace / "windows-interface" / "src"
    for source in interface_src.rglob("*.cj"):
        text = source.read_text(encoding="utf-8")
        if "windows_libloading" in text or "resolveProc(" in text:
            fail(f"{source.relative_to(workspace)} must stay free of native symbol loading")

    for member in sorted(ACTIVE_WORKSPACE_MEMBERS):
        src_root = workspace / member / "src"
        if not src_root.exists():
            continue
        for source in src_root.rglob("*.cj"):
            text = source.read_text(encoding="utf-8")
            if "windows_libloading" in text and "resolveProc" in text and LOCAL_NATIVE_PROC_CACHE_RE.search(text):
                fail(f"{source.relative_to(workspace)} must rely on windows_libloading proc caching")

    libloading = workspace / "windows-libloading" / "src" / "lib.cj"
    libloading_text = libloading.read_text(encoding="utf-8")
    if "LoadLibraryA" in libloading_text:
        fail("windows-libloading must use LoadLibraryExA with an explicit system DLL search policy")
    if "LOAD_LIBRARY_SEARCH_SYSTEM32" not in libloading_text:
        fail("windows-libloading must use a System32-only search policy for system DLLs")
    if "LOAD_LIBRARY_SEARCH_DEFAULT_DIRS" not in libloading_text or "resolveProcFromSearchPath" not in libloading_text:
        fail("windows-libloading must expose an explicit search-path API for app-local DLL loading")
    if "LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR" not in libloading_text or "searchPathLoadFlags(moduleName)" not in libloading_text:
        fail("windows-libloading explicit search-path loads must preserve absolute DLL directories for dependencies")
    if "ensureSystemModuleNameBytes(moduleNameBytes)" not in libloading_text or "isPathLikeModuleName(moduleName)" not in libloading_text:
        fail("windows-libloading system DLL loading must reject path-like module names")
    load_library_section = section_between(
        libloading_text,
        "public func loadLibrary(",
        "public func resolveProc(",
        "windows-libloading loadLibrary",
    )
    if "loadSystemLibraryUncached(moduleNameBytes)" not in load_library_section:
        fail("windows-libloading loadLibrary must load bare system DLLs from System32")
    load_library_locked_section = section_between(
        libloading_text,
        "func loadLibraryLocked(",
        "func loadLibraryFromSearchPathLocked(",
        "windows-libloading loadLibraryLocked",
    )
    if "loadSystemLibraryUncached(moduleNameBytes)" not in load_library_locked_section:
        fail("windows-libloading resolveProc must load bare system DLLs from System32")
    native_helpers_text = (workspace / "windows" / "src" / "native_helpers.cj").read_text(encoding="utf-8")
    if "resolveProc(${spec.dynamicModuleParameterName}" in native_helpers_text:
        fail("windows-gen dynamic native helpers must use the explicit search-path resolver")
    app_runtime_helpers = workspace / "windows-common" / "src" / "Native" / "AppRuntime" / "native_helpers.cj"
    check_path_exists(app_runtime_helpers, "windows-common AppRuntime native helpers")
    app_runtime_text = app_runtime_helpers.read_text(encoding="utf-8")
    if "resolveProc(bootstrapDllPath" in app_runtime_text:
        fail("windows-common AppRuntime helpers must use the explicit search-path resolver")
    if app_runtime_text.count("resolveProcFromSearchPath(bootstrapDllPath") < 2:
        fail("windows-common AppRuntime helpers must resolve bootstrap exports via the explicit search-path resolver")
    if "MddBootstrapInitialize2" not in app_runtime_text or "MddBootstrapShutdown" not in app_runtime_text:
        fail("windows-common AppRuntime helpers must include both bootstrap exports")
    common_com_helpers = workspace / "windows-common" / "src" / "Win32" / "System" / "Com" / "native_helpers.cj"
    common_com_helpers_text = common_com_helpers.read_text(encoding="utf-8")
    if "public func CoTaskMemAlloc(cb: UIntNative): CPointer<Unit>" not in common_com_helpers_text:
        fail("windows-common CoTaskMemAlloc helper must expose SIZE_T byte count as UIntNative")
    if "public func CoTaskMemRealloc(pv: CPointer<Unit>, cb: UIntNative): CPointer<Unit>" not in common_com_helpers_text:
        fail("windows-common CoTaskMemRealloc helper must expose SIZE_T byte count as UIntNative")

    core_native = workspace / "windows-core" / "src" / "native.cj"
    core_native_text = core_native.read_text(encoding="utf-8")
    for primitive in ("GetProcAddress", "LoadLibraryExA", "FreeLibrary"):
        if f"func {primitive}(" in core_native_text:
            fail(f"windows-core native helpers must not wrap {primitive}; use windows-libloading")

    result_bindings = workspace / "windows-result" / "src" / "bindings.cj"
    result_bindings_text = result_bindings.read_text(encoding="utf-8")
    if "func LoadLibraryExA(" in result_bindings_text:
        fail("windows-result must reuse windows-libloading for module loading")


def check_active_tools(workspace: Path) -> None:
    generator_main = workspace / "windows" / "src" / "main.cj"
    check_path_exists(generator_main, "Cangjie bindgen CLI")
    generator_main_text = generator_main.read_text(encoding="utf-8")
    if "writer.fileHashes()" not in generator_main_text or "file_hashes" not in generator_main_text:
        fail("windows-gen must generate manifest file_hashes for reproducible windows-common output")
    check_path_exists(workspace / "windows" / "src" / "json_loader.cj", "JSON loader")
    check_path_exists(workspace / "winmd-to-json" / "Program.cs", "winmd-to-json source")
    check_path_exists(workspace / "windows-winui3" / "src" / "xaml" / "mod.cj", "WinUI3 XAML helper")


def main() -> None:
    workspace = Path(__file__).resolve().parent.parent
    print(f"workspace = {workspace}")
    check_no_shell_scripts(workspace)
    print("OK: automation uses Python instead of shell scripts")
    check_workspace_members(workspace)
    print("OK: active workspace members match JSON-backed layout")
    check_reference_only_packages(workspace)
    print("OK: reference-only packages live under deprecated_windows_cj")
    check_generated_common_package(workspace)
    print("OK: generated windows-common package is present and marked DO NOT EDIT")
    check_package_boundaries(workspace)
    print("OK: package dependency and native helper boundaries are explicit")
    check_active_tools(workspace)
    print("OK: active Cangjie generator and WinUI helper files are present")


if __name__ == "__main__":
    main()
