#!/usr/bin/env python3
"""End-to-end guard for the checked-in windows-common generated package.

Quick mode verifies the checked-in manifest, the real WinMD JSON source hashes,
and the windows-common build entry. Full mode additionally rebuilds the
generator and regenerates windows-common into a temporary directory for a
non-destructive manifest/file diff.
"""

from __future__ import annotations

import argparse
from collections import Counter
import difflib
import hashlib
import json
import os
import re
import signal
import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence


ROOT = Path(__file__).resolve().parents[1]
WINDOWS_COMMON = ROOT / "windows-common"
WINMD_ROOT = ROOT / "winmd"
DEFAULT_WINMD_JSON_DIR = ROOT / ".generated" / "winmd-json"
WINMD_CONVERSION_HELPER = ROOT / "scripts" / "convert_winmd_to_json.py"
GENERATOR_BINARY = ROOT / "target" / "release" / "bin" / "windows_bindgen.exe"
DEFAULT_TIMEOUT_SECONDS = 300
GENERATED_BY = "Generated by windows-bindgen. DO NOT EDIT."
IGNORED_GENERATED_FILES = {"codegen-manifest.json", "cjpm.lock"}
WINUI_FEATURE_PREFIXES = ("Microsoft.UI.", "Microsoft.Windows.")
WINUI_WINMD_JSON_DIRS_ENV = "WINDOWS_CJ_WINUI_WINMD_JSON_DIRS"
WINUI_WINMD_ROOTS_ENV = "WINDOWS_CJ_WINUI_WINMD_ROOTS"
IMPL_SYMBOLS_FILE_RE = re.compile(r"src/impl/symbols_\d+\.cj$")
SYMBOL_SECTION_RE = re.compile(r"^// (.+?) \((?:0x|synthetic:)")
FACADE_FILE_RE = re.compile(r"(^|/)facade_\d+\.cj$")
JSON_HEADER_RE = {
    "winmd_file": re.compile(r'"winmd_file"\s*:\s*"([^"]+)"'),
    "winmd_sha256": re.compile(r'"winmd_sha256"\s*:\s*"([0-9a-fA-F]+)"'),
}


@dataclass(frozen=True)
class CommandResult:
    returncode: int
    output: str


@dataclass(frozen=True)
class FeaturePlan:
    available: list[str]
    blocked_winui: list[str]


@dataclass(frozen=True)
class WinmdSourceIndex:
    hashes_by_name: dict[str, set[str]]
    paths_by_name: dict[str, list[Path]]


@dataclass(frozen=True)
class ImplSymbolScan:
    sections: dict[str, str]
    duplicate_symbols: list[str]
    preamble_payload: dict[str, list[str]]


def rel_posix(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def display_path(path: Path, root: Path = ROOT) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return str(path)


def fail(message: str) -> None:
    raise RuntimeError(message)


def positive_int(value: str) -> int:
    parsed = int(value)
    if parsed <= 0:
        raise argparse.ArgumentTypeError("must be greater than zero")
    return parsed


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    helper = display_path(WINMD_CONVERSION_HELPER)
    parser = argparse.ArgumentParser(description="Verify checked-in windows-common codegen state.")
    parser.add_argument(
        "--mode",
        choices=("quick", "full"),
        default="quick",
        help="quick checks manifest/source hashes/build; full also regenerates into a temp dir and diffs.",
    )
    parser.add_argument(
        "--winmd-json-dir",
        action="append",
        type=Path,
        default=[],
        metavar="DIR",
        help="Directory containing split winmd-to-json output. Defaults to .generated/winmd-json.",
    )
    parser.add_argument(
        "--winui-winmd-json-dir",
        action="append",
        type=Path,
        default=[],
        metavar="DIR",
        help=(
            "Optional converted WinUI/WindowsAppSDK winmd-to-json directory. "
            f"Create it with {helper}; can also be supplied as an {WINUI_WINMD_JSON_DIRS_ENV} path list."
        ),
    )
    parser.add_argument(
        "--winui-winmd-root",
        action="append",
        type=Path,
        default=[],
        metavar="PATH",
        help=(
            "Raw WinUI/WindowsAppSDK .winmd file or directory used to validate "
            "optional WinUI JSON hashes. Pass the same root used with "
            f"{helper}; can also be supplied as an {WINUI_WINMD_ROOTS_ENV} path list."
        ),
    )
    parser.add_argument(
        "--skip-build",
        action="store_true",
        help="Skip cjpm builds. In full mode this requires an existing windows-bindgen binary.",
    )
    parser.add_argument(
        "--skip-regenerate",
        action="store_true",
        help="In full mode, skip the temporary generator rerun/diff.",
    )
    parser.add_argument(
        "--timeout-seconds",
        type=positive_int,
        default=DEFAULT_TIMEOUT_SECONDS,
        help="External process-tree watchdog for each cjpm/cjv command.",
    )
    parser.add_argument(
        "--self-test",
        action="store_true",
        help=argparse.SUPPRESS,
    )
    return parser.parse_args(argv)


def load_manifest(root: Path = WINDOWS_COMMON) -> dict:
    path = root / "codegen-manifest.json"
    if not path.exists():
        fail(f"missing windows-common manifest: {path}")
    with path.open("r", encoding="utf-8") as f:
        manifest = json.load(f)
    if manifest.get("generated_by") != GENERATED_BY:
        fail("windows-common manifest generated_by marker is missing or wrong")
    if manifest.get("package_name") != "windows_common":
        fail(f"windows-common manifest package_name mismatch: {manifest.get('package_name')!r}")
    return manifest


def manifest_files(manifest: dict) -> list[str]:
    files = manifest.get("files")
    if not isinstance(files, list) or not all(isinstance(entry, str) for entry in files):
        fail("windows-common manifest files must be a string array")
    if not files:
        fail("windows-common manifest must list generated files")
    if len(files) != len(set(files)):
        fail("windows-common manifest files contain duplicates")
    return files


def manifest_hashes(manifest: dict) -> dict[str, str]:
    hashes = manifest.get("file_hashes")
    if not isinstance(hashes, dict) or not all(isinstance(k, str) and isinstance(v, str) for k, v in hashes.items()):
        fail("windows-common manifest file_hashes must be a string map")
    files = set(manifest_files(manifest))
    keys = set(hashes)
    if keys != files:
        fail(f"windows-common manifest hash key mismatch; missing={sorted(files - keys)}, extra={sorted(keys - files)}")
    return dict(hashes)


def generated_tree_files(root: Path) -> set[str]:
    files: set[str] = set()
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        relative = rel_posix(path, root)
        if relative.startswith("target/") or relative in IGNORED_GENERATED_FILES:
            continue
        files.add(relative)
    return files


def check_manifest_hashes(root: Path = WINDOWS_COMMON) -> dict:
    manifest = load_manifest(root)
    files = set(manifest_files(manifest))
    hashes = manifest_hashes(manifest)
    actual_files = generated_tree_files(root)
    if actual_files != files:
        fail(f"windows-common generated file set mismatch; missing={sorted(files - actual_files)}, extra={sorted(actual_files - files)}")

    mismatches: list[str] = []
    for relative in sorted(files):
        actual_hash = hashlib.sha256((root / relative).read_bytes()).hexdigest()
        if hashes[relative] != actual_hash:
            mismatches.append(relative)
    if mismatches:
        fail(f"windows-common manifest hash mismatch: {mismatches[:10]}")

    print(f"OK: windows-common manifest hashes match {len(files)} generated files")
    return manifest


def env_path_list(name: str) -> list[Path]:
    raw = os.environ.get(name)
    if raw is None or raw.strip() == "":
        return []
    return [Path(part.strip().strip('"')) for part in raw.split(os.pathsep) if part.strip()]


def root_relative(path: Path) -> Path:
    return path if path.is_absolute() else ROOT / path


def unique_paths(paths: Sequence[Path]) -> list[Path]:
    unique: list[Path] = []
    seen: set[str] = set()
    for path in paths:
        key = os.path.normcase(str(path.resolve(strict=False)))
        if key in seen:
            continue
        seen.add(key)
        unique.append(path)
    return unique


def resolve_winmd_json_dirs(base_paths: Sequence[Path], winui_paths: Sequence[Path]) -> list[Path]:
    resolved = [root_relative(path) for path in base_paths]
    if not resolved:
        resolved = [DEFAULT_WINMD_JSON_DIR]
    resolved.extend(root_relative(path) for path in winui_paths)
    resolved = unique_paths(resolved)
    for path in resolved:
        if not path.exists():
            fail(f"missing winmd-json directory: {path}")
        if not path.is_dir():
            fail(f"winmd-json path is not a directory: {path}")
    return resolved


def resolve_winui_winmd_roots(paths: Sequence[Path]) -> list[Path]:
    resolved = unique_paths([root_relative(path) for path in paths])
    for path in resolved:
        if not path.exists():
            fail(f"missing WinUI/WindowsAppSDK WinMD path: {path}")
        if path.is_file() and path.suffix.lower() != ".winmd":
            fail(f"WinUI/WindowsAppSDK WinMD file path must end with .winmd: {path}")
        if path.is_dir() and not any(path.rglob("*.winmd")):
            fail(f"WinUI/WindowsAppSDK WinMD directory contains no .winmd files: {path}")
    return resolved


def resolve_metadata_inputs(args: argparse.Namespace) -> tuple[list[Path], list[Path]]:
    winui_json_dirs = [*args.winui_winmd_json_dir, *env_path_list(WINUI_WINMD_JSON_DIRS_ENV)]
    winui_winmd_roots = resolve_winui_winmd_roots(
        [*args.winui_winmd_root, *env_path_list(WINUI_WINMD_ROOTS_ENV)]
    )
    if winui_json_dirs and not winui_winmd_roots:
        helper = display_path(WINMD_CONVERSION_HELPER)
        fail(
            "WinUI metadata JSON requires matching raw .winmd roots for checksum validation; "
            f"add --winui-winmd-root or set {WINUI_WINMD_ROOTS_ENV}. "
            f"Convert both from one explicit source with {helper}."
        )
    return resolve_winmd_json_dirs(args.winmd_json_dir, winui_json_dirs), winui_winmd_roots


def extract_json_header(path: Path) -> tuple[str, str]:
    with path.open("r", encoding="utf-8", errors="replace") as f:
        prefix = f.read(4096)
    values: dict[str, str] = {}
    for name, pattern in JSON_HEADER_RE.items():
        match = pattern.search(prefix)
        if match is None:
            fail(f"{display_path(path)} is missing top-level {name}")
        values[name] = match.group(1)
    return values["winmd_file"], values["winmd_sha256"].lower()


def add_winmd_source(index: WinmdSourceIndex, path: Path) -> None:
    name = path.name
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    index.hashes_by_name.setdefault(name, set()).add(digest)
    index.paths_by_name.setdefault(name, []).append(path)


def iter_winmd_sources(paths: Sequence[Path]) -> list[Path]:
    sources: list[Path] = []
    for path in paths:
        if path.is_file():
            sources.append(path)
        else:
            sources.extend(sorted(path.rglob("*.winmd")))
    return unique_paths(sources)


def winmd_sources(extra_roots: Sequence[Path]) -> WinmdSourceIndex:
    if not WINMD_ROOT.exists():
        fail(f"missing WinMD source directory: {WINMD_ROOT}")
    index = WinmdSourceIndex({}, {})
    default_sources = sorted(WINMD_ROOT.glob("*.winmd"))
    for path in default_sources:
        add_winmd_source(index, path)
    if not default_sources:
        fail(f"no .winmd files found under {WINMD_ROOT}")
    for path in iter_winmd_sources(extra_roots):
        add_winmd_source(index, path)
    return index


def unknown_winmd_source_message(json_path: Path, winmd_file: str) -> str:
    helper = display_path(WINMD_CONVERSION_HELPER)
    return (
        f"{display_path(json_path)} references unknown WinMD source {winmd_file!r}. "
        "For optional WinUI/WindowsAppSDK metadata, pass the raw source with "
        f"--winui-winmd-root or {WINUI_WINMD_ROOTS_ENV} so the gate can validate JSON hashes. "
        f"Use {helper} for conversion and keep its --winmd-root as the gate root."
    )


def mismatched_winmd_hash_message(json_path: Path, winmd_file: str, index: WinmdSourceIndex) -> str:
    helper = display_path(WINMD_CONVERSION_HELPER)
    sources = index.paths_by_name.get(winmd_file, [])
    sample = ", ".join(display_path(path) for path in sources[:3])
    suffix = f" Registered source(s): {sample}" if sample else ""
    return (
        f"{display_path(json_path)} winmd_sha256 does not match any registered source for {winmd_file}. "
        "Use the same explicit WinUI/WindowsAppSDK package version for conversion and --winui-winmd-root. "
        f"{helper} prints the matching gate arguments."
        f"{suffix}"
    )


def check_winmd_json_sources(dirs: Sequence[Path], source_index: WinmdSourceIndex) -> None:
    checked = 0
    seen_sources: set[str] = set()
    for root in dirs:
        json_files = sorted(root.glob("*.json"))
        if not json_files:
            fail(f"winmd-json directory contains no JSON files: {root}")
        for path in json_files:
            winmd_file, winmd_sha256 = extract_json_header(path)
            expected_hashes = source_index.hashes_by_name.get(winmd_file)
            if expected_hashes is None:
                fail(unknown_winmd_source_message(path, winmd_file))
            if winmd_sha256 not in expected_hashes:
                fail(mismatched_winmd_hash_message(path, winmd_file, source_index))
            checked += 1
            seen_sources.add(winmd_file)
    print(f"OK: {checked} winmd-json files match real WinMD source hashes ({', '.join(sorted(seen_sources))})")


def print_winui_metadata_guidance() -> None:
    helper = display_path(WINMD_CONVERSION_HELPER)
    print(
        "HINT: provide converted WinUI/WindowsAppSDK metadata with "
        "--winui-winmd-json-dir <json-dir> and --winui-winmd-root <raw-winmd-file-or-dir>, "
        f"or set {WINUI_WINMD_JSON_DIRS_ENV} and {WINUI_WINMD_ROOTS_ENV}."
    )
    print(
        "HINT: convert an explicit root first with "
        f"python {helper} --winmd-root <raw-root> --json-dir <json-dir>."
    )
    print(
        "HINT: candidate cache roots are only listed on request: "
        f"python {helper} --list-candidates"
    )
    print("HINT: native .winmd parsing is not supported by this generator or gate.")


def winmd_json_names(dirs: Sequence[Path]) -> set[str]:
    names: set[str] = set()
    for root in dirs:
        names.update(path.stem for path in root.glob("*.json"))
    if not names:
        fail("no winmd-json names available after source validation")
    return names


def feature_has_metadata(feature: str, names: set[str]) -> bool:
    if feature in names:
        return True
    for name in names:
        if feature.startswith(f"{name}.") or name.startswith(f"{feature}."):
            return True
    return False


def is_winui_feature(feature: str) -> bool:
    return feature.startswith(WINUI_FEATURE_PREFIXES)


def manifest_requested_features(manifest: dict) -> list[str]:
    features = manifest.get("requested_features")
    if not isinstance(features, list) or not all(isinstance(feature, str) for feature in features):
        fail("windows-common manifest requested_features must be a string array")
    if not features:
        fail("windows-common manifest requested_features is empty")
    return list(features)


def manifest_selected_symbols(manifest: dict) -> list[str]:
    symbols = manifest.get("selected_symbols")
    if not isinstance(symbols, list) or not all(isinstance(symbol, str) for symbol in symbols):
        fail("windows-common manifest selected_symbols must be a string array")
    return list(symbols)


def symbol_matches_requested_feature(symbol: str, feature: str) -> bool:
    return symbol == feature or symbol.startswith(feature + ".")


def selected_symbols_for_requested_features(symbols: Sequence[str], requested_features: Sequence[str]) -> set[str]:
    return {
        symbol
        for symbol in symbols
        if any(symbol_matches_requested_feature(symbol, feature) for feature in requested_features)
    }


def namespace_for_manifest_file(relative: str) -> str | None:
    path = Path(relative)
    parts = path.parts
    if not parts or parts[0] != "src":
        return None
    namespace_parts = list(parts[1:-1])
    if not namespace_parts:
        return "Windows"
    if namespace_parts[0] == "Microsoft":
        return ".".join(namespace_parts)
    return "Windows." + ".".join(namespace_parts)


def file_matches_requested_feature(relative: str, feature: str) -> bool:
    namespace = namespace_for_manifest_file(relative)
    if namespace is None:
        return False
    return namespace == feature or namespace.startswith(feature + ".") or feature.startswith(namespace + ".")


def files_for_requested_features(files: Sequence[str], requested_features: Sequence[str]) -> set[str]:
    return {
        relative
        for relative in files
        if any(file_matches_requested_feature(relative, feature) for feature in requested_features)
    }


def plan_features(manifest: dict, input_dirs: Sequence[Path]) -> FeaturePlan:
    names = winmd_json_names(input_dirs)
    available: list[str] = []
    blocked_winui: list[str] = []
    missing: list[str] = []
    for feature in manifest_requested_features(manifest):
        if feature_has_metadata(feature, names):
            available.append(feature)
        elif is_winui_feature(feature):
            blocked_winui.append(feature)
        else:
            missing.append(feature)

    if missing:
        fail(f"requested features missing winmd-json metadata: {missing}")
    if not available:
        fail("no requested features can be checked with the available winmd-json metadata")
    for symbol in manifest_selected_symbols(manifest):
        if any(symbol_matches_requested_feature(symbol, feature) for feature in available):
            continue
        if feature_has_metadata(symbol, names):
            available.append(symbol)
    return FeaturePlan(available, blocked_winui)


def display_command(command: Sequence[str]) -> str:
    if os.name == "nt":
        return subprocess.list2cmdline(list(command))
    return " ".join(subprocess.list2cmdline([part]) for part in command)


def kill_process_tree(process: subprocess.Popen[str]) -> None:
    if process.poll() is not None:
        return
    if os.name == "nt":
        subprocess.run(
            ["taskkill", "/F", "/T", "/PID", str(process.pid)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        return
    try:
        os.killpg(process.pid, signal.SIGKILL)
    except ProcessLookupError:
        pass


def command_env() -> dict[str, str]:
    env = os.environ.copy()
    env["cjHeapSize"] = "32GB"
    return env


def run_command(command: list[str], *, timeout_seconds: int) -> CommandResult:
    print(f"+ {display_command(command)}", flush=True)
    creationflags = subprocess.CREATE_NEW_PROCESS_GROUP if os.name == "nt" else 0
    process = subprocess.Popen(
        command,
        cwd=ROOT,
        env=command_env(),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        creationflags=creationflags,
        start_new_session=(os.name != "nt"),
    )
    try:
        output, _ = process.communicate(timeout=timeout_seconds)
    except subprocess.TimeoutExpired:
        kill_process_tree(process)
        output, _ = process.communicate()
        if output:
            print(output, end="")
        print(f"command watchdog expired after {timeout_seconds}s: {display_command(command)}", file=sys.stderr)
        return CommandResult(124, output or "")
    if output:
        print(output, end="")
    return CommandResult(process.returncode, output or "")


def require_success(result: CommandResult, step: str) -> None:
    if result.returncode != 0:
        fail(f"{step} failed with exit code {result.returncode}")


def build_windows_common(timeout_seconds: int) -> None:
    result = run_command(
        ["cjpm", "build", "-m", "windows-common"],
        timeout_seconds=timeout_seconds,
    )
    require_success(result, "windows-common build")
    print("OK: windows-common build completed")


def build_generator(timeout_seconds: int) -> None:
    result = run_command(
        ["cjpm", "build", "-m", "windows-bindgen"],
        timeout_seconds=timeout_seconds,
    )
    require_success(result, "windows-bindgen generator build")
    if not GENERATOR_BINARY.exists():
        fail(f"windows-bindgen generator binary was not produced: {GENERATOR_BINARY}")
    print("OK: windows-bindgen generator build completed")


def require_existing_generator() -> None:
    if not GENERATOR_BINARY.exists():
        fail(f"windows-bindgen generator binary is required when --skip-build is used: {GENERATOR_BINARY}")


def generator_command(features: Sequence[str], input_dirs: Sequence[Path], output_dir: Path) -> list[str]:
    if not features:
        fail("windows-bindgen requested feature list is empty")
    command = ["cjv", "exec", str(GENERATOR_BINARY), "--common", "--clean", "--out", str(output_dir)]
    for input_dir in input_dirs:
        command.extend(["--input-dir", str(input_dir)])
    for feature in features:
        command.extend(["--feature", feature])
    return command


def compare_manifest_values(checked: dict, regenerated: dict) -> list[str]:
    mismatches: list[str] = []
    for key in ("generated_by", "package_name", "requested_features", "selected_symbols", "files", "file_hashes"):
        if checked.get(key) != regenerated.get(key):
            mismatches.append(key)
    return mismatches


def comparable_tree_files(root: Path) -> set[str]:
    files = generated_tree_files(root)
    manifest_path = root / "codegen-manifest.json"
    if manifest_path.exists():
        files.add("codegen-manifest.json")
    return files


def first_text_diff(left: Path, right: Path, relative: str) -> str:
    try:
        left_text = left.read_text(encoding="utf-8").splitlines(keepends=True)
        right_text = right.read_text(encoding="utf-8").splitlines(keepends=True)
    except UnicodeDecodeError:
        return f"binary file differs: {relative}"
    diff = difflib.unified_diff(
        left_text,
        right_text,
        fromfile=f"checked-in/{relative}",
        tofile=f"regenerated/{relative}",
        n=3,
    )
    return "".join(list(diff)[:80]).rstrip()


def normalize_impl_symbol_section(text: str) -> str:
    return text.rstrip(" \t\r\n")


def compare_generated_tree(checked_root: Path, regenerated_root: Path) -> None:
    checked_files = comparable_tree_files(checked_root)
    regenerated_files = comparable_tree_files(regenerated_root)
    if checked_files != regenerated_files:
        fail(
            "regenerated windows-common file set mismatch; "
            f"missing={sorted(checked_files - regenerated_files)[:20]}, "
            f"extra={sorted(regenerated_files - checked_files)[:20]}"
        )

    differing: list[str] = []
    for relative in sorted(checked_files):
        checked = checked_root / relative
        regenerated = regenerated_root / relative
        if hashlib.sha256(checked.read_bytes()).digest() != hashlib.sha256(regenerated.read_bytes()).digest():
            differing.append(relative)
    if differing:
        sample = differing[0]
        diff = first_text_diff(checked_root / sample, regenerated_root / sample, sample)
        fail(f"regenerated windows-common content differs: {differing[:20]}\n{diff}")


def impl_preamble_payload(lines: Sequence[str]) -> list[str]:
    payload: list[str] = []
    for line in lines:
        if not line.strip():
            continue
        if line.startswith("// Generated by "):
            continue
        if line.startswith("package "):
            continue
        if line.startswith("import "):
            continue
        payload.append(line)
    return payload


def impl_symbol_scan(root: Path) -> ImplSymbolScan:
    sections: dict[str, str] = {}
    duplicate_symbols: list[str] = []
    preamble_payload: dict[str, list[str]] = {}
    seen_symbols: set[str] = set()
    duplicate_set: set[str] = set()
    for path in sorted((root / "src" / "impl").glob("symbols_*.cj")):
        lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
        relative = rel_posix(path, root)
        current_symbol: str | None = None
        current_start = 0
        for index, line in enumerate(lines):
            match = SYMBOL_SECTION_RE.match(line)
            if match is None:
                continue
            if current_symbol is not None:
                sections[current_symbol] = "".join(lines[current_start:index])
            else:
                payload = impl_preamble_payload([entry.rstrip("\r\n") for entry in lines[current_start:index]])
                if payload:
                    preamble_payload[relative] = payload
            current_symbol = match.group(1)
            if current_symbol in seen_symbols:
                duplicate_set.add(f"{relative}:{current_symbol}")
            seen_symbols.add(current_symbol)
            current_start = index
        if current_symbol is not None:
            sections[current_symbol] = "".join(lines[current_start:])
        else:
            payload = impl_preamble_payload([entry.rstrip("\r\n") for entry in lines])
            if payload:
                preamble_payload[relative] = payload
    duplicate_symbols = sorted(duplicate_set)
    return ImplSymbolScan(sections, duplicate_symbols, preamble_payload)


def impl_symbol_sections(root: Path) -> dict[str, str]:
    return impl_symbol_scan(root).sections


def self_test_normalization() -> None:
    assert normalize_impl_symbol_section("body\n\n") == normalize_impl_symbol_section("body\n")
    assert normalize_impl_symbol_section("body \t\r\n") == normalize_impl_symbol_section("body")
    assert normalize_impl_symbol_section("body \nnext\n") != normalize_impl_symbol_section("body\nnext\n")
    assert normalize_impl_symbol_section("body\nnext\n") != normalize_impl_symbol_section("body\nother\n")
    assert env_path_list("__WINDOWS_CJ_DOES_NOT_EXIST__") == []
    print("OK: windows-common codegen normalization self-test completed")


def subset_payload_lines(path: Path, relative: str) -> list[str]:
    lines = path.read_text(encoding="utf-8").splitlines()
    if not (FACADE_FILE_RE.search(relative) or relative.endswith("/native_helpers.cj")):
        return lines
    payload: list[str] = []
    for line in lines:
        if not line.strip():
            continue
        if line.startswith("// Generated by "):
            continue
        if line.startswith("package "):
            continue
        if line.startswith("import "):
            continue
        payload.append(line)
    return payload


def subset_payload_identifiers(lines: Sequence[str]) -> set[str]:
    identifiers: set[str] = set()
    for line in lines:
        stripped = line.strip()
        type_match = re.match(r"public type [A-Za-z_][A-Za-z0-9_]* = ([A-Za-z_][A-Za-z0-9_]*)$", stripped)
        if type_match is not None:
            identifiers.add(type_match.group(1))
            continue
        decl_match = re.match(r"public (?:class|struct|enum|interface|func) ([A-Za-z_][A-Za-z0-9_]*)\b", stripped)
        if decl_match is not None:
            identifiers.add(decl_match.group(1))
    return identifiers


def subset_public_decl_names(lines: Sequence[str]) -> set[str]:
    names: set[str] = set()
    for line in lines:
        match = re.match(r"\s*public (?:class|struct|enum|interface|func|type) ([A-Za-z_][A-Za-z0-9_]*)\b", line)
        if match is not None:
            names.add(match.group(1))
    return names


def subset_internal_public_decl_names(lines: Sequence[str]) -> set[str]:
    names: set[str] = set()
    for line in lines:
        type_match = re.match(
            r"\s*public type ([A-Za-z_][A-Za-z0-9_]*) = ([A-Za-z_][A-Za-z0-9_]*)\b",
            line,
        )
        if type_match is not None and type_match.group(1) == type_match.group(2) and "_" in type_match.group(1):
            names.add(type_match.group(1))
            continue
        decl_match = re.match(r"\s*public (?:class|struct|enum|interface|func) ([A-Za-z_][A-Za-z0-9_]*)\b", line)
        if decl_match is not None and "_" in decl_match.group(1):
            names.add(decl_match.group(1))
    return names


def facade_public_alias_targets(lines: Sequence[str]) -> dict[str, str]:
    targets: dict[str, str] = {}
    for line in lines:
        match = re.match(
            r"\s*public type ([A-Za-z_][A-Za-z0-9_]*) = ((?:Windows|Microsoft)(?:_[A-Za-z0-9]+)+)\b",
            line,
        )
        if match is not None:
            targets[match.group(1)] = match.group(2)
    return targets


def internal_target_symbol(target: str) -> str:
    return target.replace("_", ".")


def alias_matches_requested_feature(target: str, requested_features: Sequence[str] | None) -> bool:
    if requested_features is None:
        return True
    symbol = internal_target_symbol(target)
    return any(symbol_matches_requested_feature(symbol, feature) for feature in requested_features)


def references_subset_identifier(line: str, identifiers: set[str]) -> bool:
    for identifier in identifiers:
        if re.search(rf"\b{re.escape(identifier)}\b", line):
            return True
    return False


def compare_subset_file(
    checked: Path,
    regenerated: Path,
    relative: str,
    requested_features: Sequence[str] | None = None,
) -> str | None:
    if IMPL_SYMBOLS_FILE_RE.fullmatch(relative):
        return None
    if FACADE_FILE_RE.search(relative) or relative.endswith("/native_helpers.cj"):
        checked_payload = subset_payload_lines(checked, relative)
        regenerated_payload = subset_payload_lines(regenerated, relative)
        checked_lines = set(checked_payload)
        missing_lines = [line for line in regenerated_payload if line not in checked_lines]
        if missing_lines:
            return f"{relative} contains regenerated subset lines absent from checked-in file: {missing_lines[:8]}"
        regenerated_lines = set(regenerated_payload)
        regenerated_identifiers = subset_payload_identifiers(regenerated_payload)
        if relative.endswith("/native_helpers.cj"):
            extra_public_names = sorted(subset_public_decl_names(checked_payload) - subset_public_decl_names(regenerated_payload))
            if extra_public_names:
                return f"{relative} contains checked-in public declarations absent from regenerated subset: {extra_public_names[:8]}"
        if FACADE_FILE_RE.search(relative):
            extra_internal_names = sorted(
                subset_internal_public_decl_names(checked_payload) - subset_internal_public_decl_names(regenerated_payload)
            )
            if extra_internal_names:
                return f"{relative} contains checked-in internal public declarations absent from regenerated subset: {extra_internal_names[:8]}"
            checked_alias_targets = facade_public_alias_targets(checked_payload)
            regenerated_alias_targets = facade_public_alias_targets(regenerated_payload)
            extra_available_aliases = sorted(
                alias
                for alias, target in checked_alias_targets.items()
                if regenerated_alias_targets.get(alias) != target
                and alias_matches_requested_feature(target, requested_features)
            )
            if extra_available_aliases:
                return (
                    f"{relative} contains checked-in facade aliases absent from regenerated subset: "
                    f"{extra_available_aliases[:8]}"
                )
        extra_lines = [
            line for line in checked_payload
            if line not in regenerated_lines and references_subset_identifier(line, regenerated_identifiers)
        ]
        if extra_lines:
            return f"{relative} contains checked-in lines absent from regenerated subset: {extra_lines[:8]}"
        checked_counts = Counter(checked_payload)
        regenerated_counts = Counter(regenerated_payload)
        extra_regenerated_lines = [
            line for line, count in regenerated_counts.items()
            if count > checked_counts[line] and references_subset_identifier(line, regenerated_identifiers)
        ]
        if extra_regenerated_lines:
            return f"{relative} contains regenerated duplicate subset lines absent from checked-in file: {extra_regenerated_lines[:8]}"
        duplicate_lines = [
            line for line, count in checked_counts.items()
            if count > regenerated_counts[line] and references_subset_identifier(line, regenerated_identifiers)
        ]
        if duplicate_lines:
            return f"{relative} contains checked-in lines absent from regenerated subset: {duplicate_lines[:8]}"
        return None
    if hashlib.sha256(checked.read_bytes()).digest() != hashlib.sha256(regenerated.read_bytes()).digest():
        diff = first_text_diff(checked, regenerated, relative)
        return f"{relative} differs\n{diff}"
    return None


def compare_subset_impl_symbols(checked_root: Path, regenerated_root: Path, regenerated_manifest: dict) -> list[str]:
    checked_scan = impl_symbol_scan(checked_root)
    regenerated_scan = impl_symbol_scan(regenerated_root)
    checked_sections = checked_scan.sections
    regenerated_sections = regenerated_scan.sections
    requested_features = manifest_requested_features(regenerated_manifest)
    regenerated_symbols = manifest_selected_symbols(regenerated_manifest)
    issues: list[str] = []

    if checked_scan.duplicate_symbols:
        issues.append(f"checked-in impl symbol sections contain duplicate headers: {checked_scan.duplicate_symbols[:20]}")
    if regenerated_scan.duplicate_symbols:
        issues.append(f"regenerated impl symbol sections contain duplicate headers: {regenerated_scan.duplicate_symbols[:20]}")

    for relative, checked_payload in sorted(checked_scan.preamble_payload.items()):
        regenerated_payload = regenerated_scan.preamble_payload.get(relative, [])
        extra_preamble = [line for line in checked_payload if line not in regenerated_payload]
        if extra_preamble:
            issues.append(f"{relative} contains checked-in impl preamble payload absent from regenerated subset: {extra_preamble[:8]}")
            break

    missing_sections = [symbol for symbol in regenerated_symbols if symbol not in checked_sections]
    if missing_sections:
        issues.append(f"regenerated subset selected symbols absent from checked-in manifest/output: {missing_sections[:20]}")

    extra_checked_available_sections = sorted(
        selected_symbols_for_requested_features(checked_sections.keys(), requested_features)
        - set(regenerated_sections.keys())
    )
    if extra_checked_available_sections:
        issues.append(
            "checked-in available impl symbols absent from regenerated subset: "
            f"{extra_checked_available_sections[:20]}"
        )

    for symbol in regenerated_symbols:
        checked = checked_sections.get(symbol)
        regenerated = regenerated_sections.get(symbol)
        if checked is None or regenerated is None:
            continue
        checked_normalized = normalize_impl_symbol_section(checked)
        regenerated_normalized = normalize_impl_symbol_section(regenerated)
        if checked_normalized == regenerated_normalized:
            continue
        diff = difflib.unified_diff(
            checked_normalized.splitlines(keepends=True),
            regenerated_normalized.splitlines(keepends=True),
            fromfile=f"checked-in/{symbol}",
            tofile=f"regenerated/{symbol}",
            n=3,
        )
        issues.append(f"regenerated subset symbol differs: {symbol}\n{''.join(list(diff)[:80]).rstrip()}")
        break
    return issues


def compare_generated_subset(checked_manifest: dict, regenerated_root: Path, requested_features: Sequence[str]) -> None:
    regenerated_manifest = load_manifest(regenerated_root)
    issues: list[str] = []
    if manifest_requested_features(regenerated_manifest) != list(requested_features):
        issues.append("regenerated subset manifest requested_features does not match the planned available subset")

    checked_symbols = set(manifest_selected_symbols(checked_manifest))
    regenerated_symbols = set(manifest_selected_symbols(regenerated_manifest))
    extra_symbols = sorted(regenerated_symbols - checked_symbols)
    if extra_symbols:
        issues.append(f"regenerated subset selected extra symbols not present checked-in: {extra_symbols[:20]}")
    expected_available_symbols = selected_symbols_for_requested_features(checked_symbols, requested_features)
    missing_available_symbols = sorted(expected_available_symbols - regenerated_symbols)
    if missing_available_symbols:
        issues.append(f"checked-in available selected symbols absent from regenerated subset: {missing_available_symbols[:20]}")

    checked_files = set(manifest_files(checked_manifest))
    regenerated_files = set(manifest_files(regenerated_manifest))
    extra_files = sorted(regenerated_files - checked_files)
    if extra_files:
        issues.append(f"regenerated subset produced files absent from checked-in windows-common: {extra_files[:20]}")
    expected_available_files = files_for_requested_features(checked_files, requested_features)
    missing_available_files = sorted(expected_available_files - regenerated_files)
    if missing_available_files:
        issues.append(f"checked-in available generated files absent from regenerated subset: {missing_available_files[:20]}")

    for relative in sorted(regenerated_files & checked_files):
        issue = compare_subset_file(
            WINDOWS_COMMON / relative,
            regenerated_root / relative,
            relative,
            requested_features,
        )
        if issue is not None:
            issues.append(issue)
            break

    issues.extend(compare_subset_impl_symbols(WINDOWS_COMMON, regenerated_root, regenerated_manifest))
    if issues:
        fail("regenerated available-metadata subset differs from checked-in windows-common:\n" + "\n".join(issues))


def regenerate_and_diff(manifest: dict, input_dirs: Sequence[Path], timeout_seconds: int) -> None:
    plan = plan_features(manifest, input_dirs)
    if plan.blocked_winui:
        print(
            "BLOCKED/SKIPPED: WinUI metadata is unavailable for "
            f"{len(plan.blocked_winui)} requested feature(s): {', '.join(plan.blocked_winui)}"
        )
        print_winui_metadata_guidance()
        print(f"OK: regenerating available metadata subset with {len(plan.available)} requested feature(s)")
    with tempfile.TemporaryDirectory(prefix="windows-common-codegen-") as temp:
        output_dir = Path(temp) / "windows-common"
        result = run_command(generator_command(plan.available, input_dirs, output_dir), timeout_seconds=timeout_seconds)
        require_success(result, "windows-bindgen regeneration")

        if plan.blocked_winui:
            compare_generated_subset(manifest, output_dir, plan.available)
        else:
            regenerated_manifest = load_manifest(output_dir)
            mismatches = compare_manifest_values(manifest, regenerated_manifest)
            if mismatches:
                fail(f"regenerated windows-common manifest differs in keys: {mismatches}")
            compare_generated_tree(WINDOWS_COMMON, output_dir)
    if plan.blocked_winui:
        print("OK: generator output matches checked-in windows-common for the available metadata subset")
    else:
        print("OK: generator output matches checked-in windows-common")


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    if args.self_test:
        self_test_normalization()
        return 0

    started = time.perf_counter()
    try:
        input_dirs, extra_winmd_roots = resolve_metadata_inputs(args)
        manifest = check_manifest_hashes()
        check_winmd_json_sources(input_dirs, winmd_sources(extra_winmd_roots))
        if args.mode == "full" and not args.skip_regenerate:
            if args.skip_build:
                require_existing_generator()
            else:
                build_generator(args.timeout_seconds)
            regenerate_and_diff(manifest, input_dirs, args.timeout_seconds)
        if not args.skip_build:
            build_windows_common(args.timeout_seconds)
    except RuntimeError as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1

    elapsed = time.perf_counter() - started
    print(f"OK: windows-common codegen gate completed in {elapsed:.2f}s ({args.mode})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
