#!/usr/bin/env python
"""Semantic diff of generated Cangjie code between two bindgen runs.

Used for the native-.winmd vs C#-JSON parity verdict. The two inputs are two
output directories produced by `windows_bindgen` from the *same* metadata source
(same .winmd as the C# golden JSON) and the *same* feature filter, but via the
two different front-ends:

    Path A (C# pipeline representative):  --input-json <converted JSON>
    Path B (native reader):               <input .winmd>

Both front-ends feed the identical render pipeline, so byte-for-byte equality is
expected unless the native reader recovers different metadata than the JSON.

This script compares the set of generated .cj (and codegen-manifest.json /
cjpm.toml) files between the two trees and reports semantic differences,
normalizing only cosmetic noise:

  - the "Generated by windows_bindgen" banner (identical anyway, but tolerated)
  - trailing whitespace and blank-line runs
  - import-list member ordering inside `import pkg.{...}` blocks (the renderer
    sorts these, so this is normally already stable; tolerated for safety)

Anything else (different type bodies, different members, missing/extra files,
different file content) is reported as a real difference.

Usage:
    python diff_generated_cj.py DIR_A DIR_B [--label-a A] [--label-b B]
                                            [--max-files N] [--show-diff-lines N]
                                            [--quiet]

Exit code 0 when the two trees are semantically identical, 1 otherwise.
"""

import argparse
import difflib
import os
import re
import sys


SRC_GLOB_SUFFIXES = (".cj",)
EXTRA_FILES = ("codegen-manifest.json", "cjpm.toml")

BANNER_RE = re.compile(r"^//\s*Generated by windows_bindgen.*$", re.MULTILINE)
MANIFEST_NOISE_KEYS = ("generatedAt", "generated_at", "timestamp", "toolVersion",
                       "tool_version")


def collect_files(root):
    """Return {relpath -> abspath} for every comparable file under root."""
    out = {}
    for dirpath, _dirs, files in os.walk(root):
        for f in files:
            if f.endswith(SRC_GLOB_SUFFIXES) or f in EXTRA_FILES:
                ap = os.path.join(dirpath, f)
                rel = os.path.relpath(ap, root).replace(os.sep, "/")
                out[rel] = ap
    return out


def read_text(path):
    with open(path, "r", encoding="utf-8") as fh:
        return fh.read()


def normalize_import_lines(text):
    """Sort the member list inside `import pkg.{a, b, c}` so that import member
    ordering differences (should not occur, but be safe) are not flagged."""
    def repl(m):
        prefix = m.group(1)
        members = m.group(2)
        parts = [p.strip() for p in members.split(",") if p.strip()]
        parts.sort()
        return f"{prefix}{{{', '.join(parts)}}}"

    return re.sub(r"(import\s+[\w.]+\.)\{([^}]*)\}", repl, text)


def normalize(text, is_manifest=False):
    # Strip the banner line entirely.
    text = BANNER_RE.sub("", text)
    if is_manifest:
        # Drop volatile keys (timestamps / tool version) line-wise.
        lines = []
        for ln in text.splitlines():
            stripped = ln.strip().strip(",")
            key = stripped.split(":", 1)[0].strip().strip('"') if ":" in stripped else ""
            if key in MANIFEST_NOISE_KEYS:
                continue
            lines.append(ln.rstrip())
        return "\n".join(l for l in lines if l.strip() != "")
    text = normalize_import_lines(text)
    # Normalize whitespace: rstrip each line, collapse blank-line runs, drop
    # leading/trailing blank lines.
    lines = [ln.rstrip() for ln in text.splitlines()]
    out = []
    blank = False
    for ln in lines:
        if ln == "":
            if blank:
                continue
            blank = True
        else:
            blank = False
        out.append(ln)
    # trim leading/trailing blanks
    while out and out[0] == "":
        out.pop(0)
    while out and out[-1] == "":
        out.pop()
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("dir_a")
    ap.add_argument("dir_b")
    ap.add_argument("--label-a", default="A (json)")
    ap.add_argument("--label-b", default="B (native winmd)")
    ap.add_argument("--max-files", type=int, default=40,
                    help="max differing files to show in detail")
    ap.add_argument("--show-diff-lines", type=int, default=40,
                    help="max diff lines per differing file")
    ap.add_argument("--quiet", action="store_true",
                    help="only print the final summary")
    opts = ap.parse_args()

    files_a = collect_files(opts.dir_a)
    files_b = collect_files(opts.dir_b)

    keys_a = set(files_a)
    keys_b = set(files_b)

    only_a = sorted(keys_a - keys_b)
    only_b = sorted(keys_b - keys_a)
    shared = sorted(keys_a & keys_b)

    if only_a:
        print(f"== {len(only_a)} files only in {opts.label_a} ==")
        for k in only_a:
            print(f"  {k}")
    if only_b:
        print(f"== {len(only_b)} files only in {opts.label_b} ==")
        for k in only_b:
            print(f"  {k}")

    differing = []
    for rel in shared:
        is_manifest = rel.endswith("codegen-manifest.json")
        a = normalize(read_text(files_a[rel]), is_manifest)
        b = normalize(read_text(files_b[rel]), is_manifest)
        if a != b:
            differing.append((rel, a, b))

    shown = 0
    for rel, a, b in differing:
        if opts.quiet:
            break
        if shown >= opts.max_files:
            break
        shown += 1
        print(f"\n== DIFF {rel} ==")
        diff = list(difflib.unified_diff(
            a.splitlines(), b.splitlines(),
            fromfile=opts.label_a, tofile=opts.label_b, lineterm=""))
        for ln in diff[:opts.show_diff_lines]:
            print(ln)
        if len(diff) > opts.show_diff_lines:
            print(f"  ... ({len(diff) - opts.show_diff_lines} more diff lines)")

    print("\n================ SUMMARY ================")
    print(f"{opts.label_a} files:   {len(keys_a)}")
    print(f"{opts.label_b} files:   {len(keys_b)}")
    print(f"only in A:        {len(only_a)}")
    print(f"only in B:        {len(only_b)}")
    print(f"shared files:     {len(shared)}")
    print(f"differing files:  {len(differing)}")

    if only_a or only_b or differing:
        sys.exit(1)
    sys.exit(0)


if __name__ == "__main__":
    main()
