#!/usr/bin/env python3
"""Generate and optionally link WinMD metadata as PE RCDATA resources."""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Mapping, Sequence


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CJ_HEAP_SIZE = "32GB"
DEFAULT_OUTPUT_DIR = Path("windows_bindgen/build/embedded_winmd")
DEFAULT_RC_NAME = "winmd_resources.rc"
DEFAULT_OBJ_NAME = "winmd_resources.obj"
LINK_OPTION_MARKER = "# injected by scripts/embed_winmd_resources.py"

WINMD_RESOURCE_IDS: tuple[tuple[str, int], ...] = (
    ("Microsoft.Foundation.winmd", 1000),
    ("Microsoft.Graphics.winmd", 1001),
    ("Microsoft.UI.Text.winmd", 1002),
    ("Microsoft.UI.winmd", 1003),
    ("Microsoft.UI.Xaml.winmd", 1004),
    ("Microsoft.Windows.ApplicationModel.Resources.winmd", 1005),
    ("Windows.Wdk.winmd", 1006),
    ("Windows.Win32.winmd", 1007),
    ("Windows.winmd", 1008),
)

Run = Callable[..., subprocess.CompletedProcess[str]]


@dataclass(frozen=True)
class ResourceObject:
    rc_path: Path
    obj_path: Path
    command: list[str]


def require_winmd_files(winmd_dir: Path) -> list[Path]:
    missing = [name for name, _ in WINMD_RESOURCE_IDS if not (winmd_dir / name).is_file()]
    if missing:
        joined = ", ".join(missing)
        raise RuntimeError(f"missing WinMD metadata under {winmd_dir}: {joined}")
    return [winmd_dir / name for name, _ in WINMD_RESOURCE_IDS]


def rc_quote(path: Path) -> str:
    return '"' + str(path.resolve()).replace("\\", "\\\\").replace('"', '\\"') + '"'


def resource_script_text(winmd_dir: Path) -> str:
    lines = [
        "// Generated by scripts/embed_winmd_resources.py. DO NOT EDIT.",
        "",
    ]
    for name, resource_id in WINMD_RESOURCE_IDS:
        lines.append(f"{resource_id} RCDATA {rc_quote(winmd_dir / name)}")
    lines.append("")
    return "\n".join(lines)


def find_resource_compiler(env: Mapping[str, str] | None = None) -> str:
    source_env = os.environ if env is None else env
    explicit = source_env.get("WINDRES")
    if explicit:
        return explicit
    for name in ("llvm-windres", "windres"):
        found = shutil.which(name)
        if found:
            return found
    raise RuntimeError("could not find llvm-windres or windres; set WINDRES to the resource compiler path")


def generate_resource_object(
    root: Path = ROOT,
    *,
    winmd_dir: Path | None = None,
    output_dir: Path | None = None,
    resource_compiler: str | None = None,
    run: Run = subprocess.run,
    dry_run: bool = False,
) -> ResourceObject:
    resolved_root = root.resolve()
    resolved_winmd_dir = (resolved_root / "winmd" if winmd_dir is None else winmd_dir).resolve()
    resolved_output_dir = (resolved_root / DEFAULT_OUTPUT_DIR if output_dir is None else output_dir).resolve()
    require_winmd_files(resolved_winmd_dir)

    rc_path = resolved_output_dir / DEFAULT_RC_NAME
    obj_path = resolved_output_dir / DEFAULT_OBJ_NAME
    compiler = resource_compiler if resource_compiler is not None else find_resource_compiler()
    command = [compiler, "-O", "coff", str(rc_path), "-o", str(obj_path)]
    if dry_run:
        return ResourceObject(rc_path=rc_path, obj_path=obj_path, command=command)

    resolved_output_dir.mkdir(parents=True, exist_ok=True)
    rc_path.write_text(resource_script_text(resolved_winmd_dir), encoding="utf-8")
    run(command, cwd=resolved_root, check=True, text=True)
    return ResourceObject(rc_path=rc_path, obj_path=obj_path, command=command)


def toml_link_option_for(path: Path) -> str:
    return path.resolve().as_posix()


def detect_newline(text: str) -> str:
    return "\r\n" if "\r\n" in text else "\n"


def inject_link_option(toml_text: str, link_option: str) -> str:
    newline = detect_newline(toml_text)
    escaped = link_option.replace("\\", "\\\\").replace('"', '\\"')
    line = f'  link-option = "{escaped}" {LINK_OPTION_MARKER}'
    if LINK_OPTION_MARKER in toml_text:
        return toml_text
    if re.search(r"^\s*link-option\s*=", toml_text, flags=re.MULTILINE):
        raise RuntimeError("windows_bindgen/cjpm.toml already has link-option; refusing to overwrite it")

    for key in ("compile-option", "output-type"):
        patched = insert_after_toml_string_assignment(toml_text, key, line, newline)
        if patched is not None:
            return patched
    raise RuntimeError("could not find insertion point for link-option in windows_bindgen/cjpm.toml")


def insert_after_toml_string_assignment(toml_text: str, key: str, inserted_line: str, fallback_newline: str) -> str | None:
    pattern = re.compile(rf"^[ \t]*{re.escape(key)}[ \t]*=[ \t]*\"[^\"]*\"[ \t]*$")
    lines = toml_text.splitlines(keepends=True)
    for index, line in enumerate(lines):
        body = line.rstrip("\r\n")
        ending = line[len(body):]
        if pattern.match(body):
            newline = ending if ending else fallback_newline
            lines.insert(index + 1, inserted_line + newline)
            return "".join(lines)
    return None


def build_env(base: Mapping[str, str] | None = None) -> dict[str, str]:
    env = dict(os.environ if base is None else base)
    env["cjHeapSize"] = DEFAULT_CJ_HEAP_SIZE
    return env


def build_windows_bindgen_with_embedded_winmd(
    root: Path = ROOT,
    *,
    winmd_dir: Path | None = None,
    output_dir: Path | None = None,
    resource_compiler: str | None = None,
    run: Run = subprocess.run,
) -> ResourceObject:
    resource = generate_resource_object(
        root,
        winmd_dir=winmd_dir,
        output_dir=output_dir,
        resource_compiler=resource_compiler,
        run=run,
    )
    toml_path = root / "windows_bindgen" / "cjpm.toml"
    original_bytes = toml_path.read_bytes()
    original = original_bytes.decode("utf-8")
    patched = inject_link_option(original, toml_link_option_for(resource.obj_path))
    try:
        toml_path.write_text(patched, encoding="utf-8", newline="")
        run(["cjpm", "build", "-m", "windows_bindgen"], cwd=root, check=True, text=True, env=build_env())
    finally:
        toml_path.write_bytes(original_bytes)
    return resource


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT, help="workspace root; defaults to this script's repository")
    parser.add_argument("--winmd-dir", type=Path, default=None, help="directory containing the bundled .winmd files")
    parser.add_argument("--output-dir", type=Path, default=None, help="directory for generated .rc/.obj files")
    parser.add_argument("--resource-compiler", default=None, help="path to llvm-windres or windres")
    parser.add_argument("--build", action="store_true", help="temporarily link the object and build windows_bindgen")
    parser.add_argument("--dry-run", action="store_true", help="validate inputs and print the command without writing files")
    parser.add_argument("--print-link-option", action="store_true", help="print the link-option value for the generated object")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    if args.build and args.dry_run:
        raise RuntimeError("--build and --dry-run cannot be used together")

    if args.build:
        resource = build_windows_bindgen_with_embedded_winmd(
            args.root,
            winmd_dir=args.winmd_dir,
            output_dir=args.output_dir,
            resource_compiler=args.resource_compiler,
        )
    else:
        resource = generate_resource_object(
            args.root,
            winmd_dir=args.winmd_dir,
            output_dir=args.output_dir,
            resource_compiler=args.resource_compiler,
            dry_run=args.dry_run,
        )
        if not args.dry_run:
            print(f"generated {resource.obj_path}")

    if args.dry_run:
        print(" ".join(resource.command))
    if args.print_link_option:
        print(toml_link_option_for(resource.obj_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
