#!/usr/bin/env python3
from __future__ import annotations

import contextlib
import io
import tempfile
import unittest
from pathlib import Path

import check_abi_ownership as abi
import check_ignored_results as ignored
import check_windows_common_codegen as codegen
import check_workspace_setup as setup


def write_file(root: Path, relative: str) -> None:
    path = root / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("placeholder\n", encoding="utf-8")


class ActiveWorkspaceLayoutTests(unittest.TestCase):
    def test_setup_tracks_bindgen_generator_without_active_sys_package(self) -> None:
        removed_sys_member = "windows" + "-sys"
        removed_sys_module = "windows" + "_sys"

        self.assertIn("windows-bindgen", setup.ACTIVE_WORKSPACE_MEMBERS)
        self.assertNotIn(removed_sys_member, setup.ACTIVE_WORKSPACE_MEMBERS)
        self.assertIn("windows_bindgen", setup.PACKAGE_DEPENDENCIES)
        self.assertNotIn(removed_sys_module, setup.PACKAGE_DEPENDENCIES)
        self.assertNotIn("windows-bindgen", setup.REFERENCE_ONLY_PACKAGES)
        self.assertEqual(setup.GENERATED_MANIFEST_HEADER, "Generated by windows-bindgen. DO NOT EDIT.")
        self.assertEqual(codegen.GENERATOR_BINARY.name, "windows_bindgen.exe")

    def test_script_audits_read_active_members_from_workspace_manifest(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            (workspace / "cjpm.toml").write_text(
                "[workspace]\nmembers = [\"windows-bindgen\"]\n",
                encoding="utf-8",
            )

            self.assertEqual(ignored.workspace_members(workspace), ["windows-bindgen"])
            self.assertEqual(abi.workspace_members(workspace), ["windows-bindgen"])


class WorkspaceSetupParserTests(unittest.TestCase):
    def test_finalizer_scan_ignores_block_comment_braces(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            source = workspace / "blocked_finalizer.cj"
            source.write_text(
                (
                    "package test\n"
                    "class BlockedFinalizer {\n"
                    "    ~init() {\n"
                    "        /* } */\n"
                    "        CloseHandle(raw)\n"
                    "    }\n"
                    "}\n"
                ),
                encoding="utf-8",
            )

            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr), self.assertRaises(SystemExit):
                setup.check_finalizers_do_not_block_on_locks(workspace)

            self.assertIn("CloseHandle", stderr.getvalue())


class CollectionThunkGateTests(unittest.TestCase):
    def write_runtime_source(self, workspace: Path, text: str) -> None:
        path = workspace / "windows-runtime" / "src" / "collections_runtime.cj"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")

    def test_rejects_indexof_thunk_without_null_index_guard(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            self.write_runtime_source(
                workspace,
                (
                    "public func __winrtThunk_IndexOf(arg0: CPointer<Unit>, arg1: CPointer<UInt32>, result__: CPointer<Bool>): Int32 {\n"
                    "    if (result__.isNull()) { return E_POINTER.value }\n"
                    "    match (this.IndexOf(value, arg1)) { case _ => S_OK.value }\n"
                    "}\n"
                    "public func __winrtThunk_IndexOf(arg0: CPointer<Unit>, arg1: CPointer<UInt32>, result__: CPointer<Bool>): Int32 {\n"
                    "    if (result__.isNull()) { return E_POINTER.value }\n"
                    "    if (arg1.isNull()) { return E_POINTER.value }\n"
                    "    match (this.IndexOf(value, arg1)) { case _ => S_OK.value }\n"
                    "}\n"
                    "public func __winrtThunk_IndexOf(arg0: CPointer<Unit>, arg1: CPointer<UInt32>, result__: CPointer<Bool>): Int32 {\n"
                    "    if (result__.isNull()) { return E_POINTER.value }\n"
                    "    if (arg1.isNull()) { return E_POINTER.value }\n"
                    "    match (this.IndexOf(value, arg1)) { case _ => S_OK.value }\n"
                    "}\n"
                ),
            )

            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                with self.assertRaises(SystemExit) as raised:
                    setup.check_collection_indexof_thunks_reject_null_index(workspace)

            self.assertEqual(raised.exception.code, 1)
            self.assertIn("IndexOf thunk must reject null index out pointer", stderr.getvalue())

    def test_accepts_indexof_thunks_with_null_index_guard(self) -> None:
        body = (
            "public func __winrtThunk_IndexOf(arg0: CPointer<Unit>, arg1: CPointer<UInt32>, result__: CPointer<Bool>): Int32 {\n"
            "    if (result__.isNull()) { return E_POINTER.value }\n"
            "    if (arg1.isNull()) { return E_POINTER.value }\n"
            "    match (this.IndexOf(value, arg1)) { case _ => S_OK.value }\n"
            "}\n"
        )
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            self.write_runtime_source(workspace, body + body + body)

            setup.check_collection_indexof_thunks_reject_null_index(workspace)

    def test_accepts_indexof_thunks_with_combined_null_index_guard(self) -> None:
        body = (
            "public func __winrtThunk_IndexOf(arg0: CPointer<Unit>, arg1: CPointer<UInt32>, result__: CPointer<Bool>): Int32 {\n"
            "    if (result__.isNull() || arg1.isNull()) { return E_POINTER.value }\n"
            "    match (this.IndexOf(value, arg1)) { case _ => S_OK.value }\n"
            "}\n"
        )
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            self.write_runtime_source(workspace, body + body + body)

            setup.check_collection_indexof_thunks_reject_null_index(workspace)


class GeneratedCommonImplInvariantTests(unittest.TestCase):
    def write_impl_chunk(self, root: Path, name: str, text: str) -> None:
        path = root / "windows-common" / "src" / "impl" / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")

    def required_delegate_impl_text(self) -> str:
        return (
            "func Start(callback: CPointer<Unit>): Int32 { 0 }\n"
            "extend Microsoft_UI_Xaml_ApplicationInitializationCallback <: "
            "windows_core.HandleWinrtType<Microsoft_UI_Xaml_ApplicationInitializationCallback> {}\n"
            "winrtBorrowGenericIn<Microsoft_UI_Xaml_ApplicationInitializationCallback>(callback)\n"
        )

    def test_delegate_invariant_scan_covers_later_impl_chunks(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            self.write_impl_chunk(root, "symbols_0.cj", self.required_delegate_impl_text())
            self.write_impl_chunk(
                root,
                "symbols_1.cj",
                "public type Microsoft_UI_Xaml_ApplicationInitializationCallback = CFunc<() -> Unit>\n",
            )

            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                with self.assertRaises(SystemExit) as raised:
                    setup.check_generated_common_impl_invariants(root / "windows-common")

            self.assertEqual(raised.exception.code, 1)
            self.assertIn("WinRT delegate projections as CFunc aliases", stderr.getvalue())

    def test_rejects_stale_raw_handle_without_resource_ownership(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            stale_handle = (
                "public class Windows_Win32_System_Com_IStream {\n"
                "    private let raw: CPointer<Unit>\n"
                "    public init(raw: CPointer<Unit>) { this.raw = raw }\n"
                "    public func asRaw(): CPointer<Unit> { raw }\n"
                "    public static func projectionKind(): String { return \"interface\" }\n"
                "}\n"
            )
            self.write_impl_chunk(root, "symbols_0.cj", self.required_delegate_impl_text() + stale_handle)

            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                with self.assertRaises(SystemExit) as raised:
                    setup.check_generated_common_impl_invariants(root / "windows-common")

            self.assertEqual(raised.exception.code, 1)
            self.assertIn("raw handle classes must be owning Resource wrappers", stderr.getvalue())

    def test_rejects_raw_handle_resource_without_owned_cleanup_surface(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            stale_handle = (
                "public class Windows_Win32_System_Com_IStream <: Resource {\n"
                "    private let raw: CPointer<Unit>\n"
                "    public init(raw: CPointer<Unit>) { this.raw = raw }\n"
                "    public func asRaw(): CPointer<Unit> { raw }\n"
                "    public func close(): Unit { () }\n"
                "    public static func projectionKind(): String { return \"interface\" }\n"
                "}\n"
            )
            self.write_impl_chunk(root, "symbols_0.cj", self.required_delegate_impl_text() + stale_handle)

            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                with self.assertRaises(SystemExit) as raised:
                    setup.check_generated_common_impl_invariants(root / "windows-common")

            self.assertEqual(raised.exception.code, 1)
            self.assertIn("raw handle Resource wrappers must preserve owned ABI cleanup", stderr.getvalue())


class WindowsCommonCodegenSubsetTests(unittest.TestCase):
    def write_text(self, root: Path, relative: str, text: str) -> Path:
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        return path

    def test_subset_compare_rejects_extra_checked_facade_payload(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            relative = "src/Win32/Foundation/facade_0.cj"
            checked = self.write_text(
                root,
                "checked/" + relative,
                (
                    "// Generated by windows-bindgen. DO NOT EDIT.\n"
                    "package windows_common.Win32.Foundation\n"
                    "import windows_core.*\n"
                    "public type Kept = Windows_Win32_Foundation_Kept\n"
                    "public type StaleAlias = Windows_Win32_Foundation_Kept\n"
                ),
            )
            regenerated = self.write_text(
                root,
                "regenerated/" + relative,
                (
                    "// Generated by windows-bindgen. DO NOT EDIT.\n"
                    "package windows_common.Win32.Foundation\n"
                    "import windows_core.*\n"
                    "public type Kept = Windows_Win32_Foundation_Kept\n"
                ),
            )

            issue = codegen.compare_subset_file(checked, regenerated, relative)

            self.assertIsNotNone(issue)
            self.assertIn("facade aliases absent from regenerated subset", issue or "")
            self.assertIn("StaleAlias", issue or "")

    def test_subset_compare_rejects_duplicate_checked_facade_payload(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            relative = "src/Win32/Foundation/facade_0.cj"
            checked = self.write_text(
                root,
                "checked/" + relative,
                (
                    "// Generated by windows-bindgen. DO NOT EDIT.\n"
                    "package windows_common.Win32.Foundation\n"
                    "import windows_core.*\n"
                    "public type Kept = Windows_Win32_Foundation_Kept\n"
                    "public type Kept = Windows_Win32_Foundation_Kept\n"
                ),
            )
            regenerated = self.write_text(
                root,
                "regenerated/" + relative,
                (
                    "// Generated by windows-bindgen. DO NOT EDIT.\n"
                    "package windows_common.Win32.Foundation\n"
                    "import windows_core.*\n"
                    "public type Kept = Windows_Win32_Foundation_Kept\n"
                ),
            )

            issue = codegen.compare_subset_file(checked, regenerated, relative)

            self.assertIsNotNone(issue)
            self.assertIn("checked-in lines absent from regenerated subset", issue or "")
            self.assertIn("public type Kept = Windows_Win32_Foundation_Kept", issue or "")

    def test_subset_compare_rejects_extra_checked_facade_internal_self_alias(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            relative = "src/Foundation/facade_0.cj"
            checked = self.write_text(
                root,
                "checked/" + relative,
                (
                    "// Generated by windows-bindgen. DO NOT EDIT.\n"
                    "package windows_common.Foundation\n"
                    "import windows_common.impl.{Windows_Foundation_Kept}\n"
                    "public type Kept = Windows_Foundation_Kept\n"
                    "public type Windows_Foundation_Stale = Windows_Foundation_Stale\n"
                ),
            )
            regenerated = self.write_text(
                root,
                "regenerated/" + relative,
                (
                    "// Generated by windows-bindgen. DO NOT EDIT.\n"
                    "package windows_common.Foundation\n"
                    "import windows_common.impl.{Windows_Foundation_Kept}\n"
                    "public type Kept = Windows_Foundation_Kept\n"
                ),
            )

            issue = codegen.compare_subset_file(checked, regenerated, relative)

            self.assertIsNotNone(issue)
            self.assertIn("internal public declarations absent from regenerated subset", issue or "")
            self.assertIn("Windows_Foundation_Stale", issue or "")

    def test_subset_compare_rejects_extra_checked_facade_alias_for_available_feature(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            relative = "src/Foundation/facade_0.cj"
            checked = self.write_text(
                root,
                "checked/" + relative,
                (
                    "// Generated by windows-bindgen. DO NOT EDIT.\n"
                    "package windows_common.Foundation\n"
                    "import windows_common.impl.{Windows_Foundation_Kept}\n"
                    "public type Kept = Windows_Foundation_Kept\n"
                    "public type Stale = Windows_Foundation_Stale\n"
                ),
            )
            regenerated = self.write_text(
                root,
                "regenerated/" + relative,
                (
                    "// Generated by windows-bindgen. DO NOT EDIT.\n"
                    "package windows_common.Foundation\n"
                    "import windows_common.impl.{Windows_Foundation_Kept}\n"
                    "public type Kept = Windows_Foundation_Kept\n"
                ),
            )

            issue = codegen.compare_subset_file(
                checked,
                regenerated,
                relative,
                requested_features=["Windows.Foundation"],
            )

            self.assertIsNotNone(issue)
            self.assertIn("facade aliases absent from regenerated subset", issue or "")
            self.assertIn("Stale", issue or "")

    def test_subset_compare_allows_extra_checked_facade_payload_for_skipped_symbols(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            relative = "src/Foundation/facade_0.cj"
            checked = self.write_text(
                root,
                "checked/" + relative,
                (
                    "// Generated by windows-bindgen. DO NOT EDIT.\n"
                    "package windows_common.Foundation\n"
                    "import windows_core.*\n"
                    "public type EventRegistrationToken = Windows_Foundation_EventRegistrationToken\n"
                    "public type AsyncStatus = Windows_Foundation_AsyncStatus\n"
                ),
            )
            regenerated = self.write_text(
                root,
                "regenerated/" + relative,
                (
                    "// Generated by windows-bindgen. DO NOT EDIT.\n"
                    "package windows_common.Foundation\n"
                    "import windows_core.*\n"
                    "public type EventRegistrationToken = Windows_Foundation_EventRegistrationToken\n"
                ),
            )

            self.assertIsNone(
                codegen.compare_subset_file(
                    checked,
                    regenerated,
                    relative,
                    requested_features=["Windows.Foundation.EventRegistrationToken"],
                )
            )

    def test_subset_compare_rejects_missing_native_checked_wrapper(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            relative = "src/Win32/Foundation/native_helpers.cj"
            checked = self.write_text(
                root,
                "checked/" + relative,
                (
                    "package windows_common.Win32.Foundation\n"
                    "public func CreateThing(): Bool {\n"
                    "    true\n"
                    "}\n"
                ),
            )
            regenerated = self.write_text(
                root,
                "regenerated/" + relative,
                (
                    "package windows_common.Win32.Foundation\n"
                    "public func CreateThing(): Bool {\n"
                    "    true\n"
                    "}\n"
                    "public func CreateThingChecked(): windows_core.Result<Unit> {\n"
                    "    if (CreateThing()) {\n"
                    "        return windows_core.Result<Unit>.Ok(())\n"
                    "    }\n"
                    "    windows_core.Result<Unit>.Err(windows_core.errorFromThread())\n"
                    "}\n"
                ),
            )

            issue = codegen.compare_subset_file(checked, regenerated, relative)

            self.assertIsNotNone(issue)
            self.assertIn("regenerated subset lines absent from checked-in file", issue or "")
            self.assertIn("CreateThingChecked", issue or "")

    def test_subset_compare_rejects_regenerated_duplicate_facade_payload(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            relative = "src/Win32/Foundation/facade_0.cj"
            checked = self.write_text(
                root,
                "checked/" + relative,
                (
                    "// Generated by windows-bindgen. DO NOT EDIT.\n"
                    "package windows_common.Win32.Foundation\n"
                    "public type Kept = Windows_Win32_Foundation_Kept\n"
                ),
            )
            regenerated = self.write_text(
                root,
                "regenerated/" + relative,
                (
                    "// Generated by windows-bindgen. DO NOT EDIT.\n"
                    "package windows_common.Win32.Foundation\n"
                    "public type Kept = Windows_Win32_Foundation_Kept\n"
                    "public type Kept = Windows_Win32_Foundation_Kept\n"
                ),
            )

            issue = codegen.compare_subset_file(checked, regenerated, relative)

            self.assertIsNotNone(issue)
            self.assertIn("regenerated duplicate subset lines", issue or "")

    def test_subset_compare_rejects_extra_native_helper_public_declaration(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            relative = "src/Win32/Foundation/native_helpers.cj"
            checked = self.write_text(
                root,
                "checked/" + relative,
                (
                    "package windows_common.Win32.Foundation\n"
                    "public func Kept(): Bool {\n"
                    "    true\n"
                    "}\n"
                    "public func StaleChecked(): windows_core.Result<Unit> {\n"
                    "    windows_core.Result<Unit>.Ok(())\n"
                    "}\n"
                ),
            )
            regenerated = self.write_text(
                root,
                "regenerated/" + relative,
                (
                    "package windows_common.Win32.Foundation\n"
                    "public func Kept(): Bool {\n"
                    "    true\n"
                    "}\n"
                ),
            )

            issue = codegen.compare_subset_file(checked, regenerated, relative)

            self.assertIsNotNone(issue)
            self.assertIn("public declarations absent from regenerated subset", issue or "")
            self.assertIn("StaleChecked", issue or "")

    def test_subset_symbol_filter_identifies_checked_available_symbols(self) -> None:
        symbols = {
            "Microsoft.UI.Xaml.Application",
            "Windows.Foundation.EventRegistrationToken",
            "Windows.Win32.Foundation.HRESULT",
            "Windows.Win32.FoundationExtra.NotAMatch",
            "Windows.Win32.Security.SECURITY_ATTRIBUTES",
        }
        available = ["Windows.Foundation.EventRegistrationToken", "Windows.Win32.Foundation"]

        self.assertEqual(
            codegen.selected_symbols_for_requested_features(symbols, available),
            {
                "Windows.Foundation.EventRegistrationToken",
                "Windows.Win32.Foundation.HRESULT",
            },
        )

    def test_subset_file_filter_identifies_checked_available_files(self) -> None:
        files = {
            "src/Win32/Foo/native_helpers.cj",
            "src/Win32/Foo/mod.cj",
            "src/Win32/Bar/native_helpers.cj",
            "src/Microsoft/UI/Xaml/mod.cj",
        }
        available = ["Windows.Win32.Foo", "Microsoft.UI.Xaml.Application"]

        self.assertEqual(
            codegen.files_for_requested_features(files, available),
            {
                "src/Win32/Foo/native_helpers.cj",
                "src/Win32/Foo/mod.cj",
                "src/Microsoft/UI/Xaml/mod.cj",
            },
        )
        self.assertEqual(codegen.namespace_for_manifest_file("src/Microsoft/UI/Xaml/mod.cj"), "Microsoft.UI.Xaml")

    def test_plan_features_includes_available_selected_symbols_outside_requested_roots(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            write_file(root, "Windows.Foundation.json")
            manifest = {
                "requested_features": [
                    "Microsoft.UI.Xaml.Application",
                    "Windows.Foundation.EventRegistrationToken",
                ],
                "selected_symbols": [
                    "Microsoft.UI.Xaml.Application",
                    "Windows.Foundation.EventRegistrationToken",
                    "Windows.Foundation.Uri",
                ],
            }

            plan = codegen.plan_features(manifest, [root])

            self.assertEqual(plan.blocked_winui, ["Microsoft.UI.Xaml.Application"])
            self.assertEqual(
                plan.available,
                ["Windows.Foundation.EventRegistrationToken", "Windows.Foundation.Uri"],
            )

    def test_codegen_command_env_forces_cj_heap_size(self) -> None:
        self.assertEqual(codegen.command_env()["cjHeapSize"], "32GB")

    def test_subset_compare_rejects_extra_checked_impl_symbol_for_available_feature(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            self.write_text(
                root,
                "checked/src/impl/symbols_0.cj",
                (
                    "// Windows.Foundation.Kept (0x1)\n"
                    "public class Windows_Foundation_Kept {}\n"
                    "// Windows.Foundation.Stale (0x2)\n"
                    "public class Windows_Foundation_Stale {}\n"
                ),
            )
            self.write_text(
                root,
                "regenerated/src/impl/symbols_0.cj",
                (
                    "// Windows.Foundation.Kept (0x1)\n"
                    "public class Windows_Foundation_Kept {}\n"
                ),
            )
            manifest = {
                "requested_features": ["Windows.Foundation"],
                "selected_symbols": ["Windows.Foundation.Kept"],
            }

            issues = codegen.compare_subset_impl_symbols(root / "checked", root / "regenerated", manifest)

            self.assertEqual(len(issues), 1)
            self.assertIn("checked-in available impl symbols absent from regenerated subset", issues[0])
            self.assertIn("Windows.Foundation.Stale", issues[0])

    def test_subset_compare_rejects_checked_impl_preamble_payload(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            self.write_text(
                root,
                "checked/src/impl/symbols_0.cj",
                (
                    "// Generated by windows-bindgen. DO NOT EDIT.\n"
                    "package windows_common.impl\n"
                    "public class Windows_Foundation_Stale {}\n"
                    "// Windows.Foundation.Kept (0x1)\n"
                    "public class Windows_Foundation_Kept {}\n"
                ),
            )
            self.write_text(
                root,
                "regenerated/src/impl/symbols_0.cj",
                (
                    "// Generated by windows-bindgen. DO NOT EDIT.\n"
                    "package windows_common.impl\n"
                    "// Windows.Foundation.Kept (0x1)\n"
                    "public class Windows_Foundation_Kept {}\n"
                ),
            )
            manifest = {
                "requested_features": ["Windows.Foundation"],
                "selected_symbols": ["Windows.Foundation.Kept"],
            }

            issues = codegen.compare_subset_impl_symbols(root / "checked", root / "regenerated", manifest)

            self.assertEqual(len(issues), 1)
            self.assertIn("impl preamble payload absent from regenerated subset", issues[0])
            self.assertIn("Windows_Foundation_Stale", issues[0])

    def test_subset_compare_rejects_duplicate_checked_impl_symbol_section(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            self.write_text(
                root,
                "checked/src/impl/symbols_0.cj",
                (
                    "// Windows.Foundation.Kept (0x1)\n"
                    "public class Windows_Foundation_Stale {}\n"
                    "// Windows.Foundation.Kept (0x1)\n"
                    "public class Windows_Foundation_Kept {}\n"
                ),
            )
            self.write_text(
                root,
                "regenerated/src/impl/symbols_0.cj",
                (
                    "// Windows.Foundation.Kept (0x1)\n"
                    "public class Windows_Foundation_Kept {}\n"
                ),
            )
            manifest = {
                "requested_features": ["Windows.Foundation"],
                "selected_symbols": ["Windows.Foundation.Kept"],
            }

            issues = codegen.compare_subset_impl_symbols(root / "checked", root / "regenerated", manifest)

            self.assertTrue(any("duplicate headers" in issue for issue in issues))
            self.assertTrue(any("Windows.Foundation.Kept" in issue for issue in issues))


class AbiOwnershipAuditTests(unittest.TestCase):
    def test_query_interface_raw_wrapped_in_local_is_not_consumed(self) -> None:
        body = (
            "\n"
            "    let leaked = Some(raw)\n"
            "    println(\"after\")\n"
        )

        self.assertFalse(abi.query_result_consumed(body, "raw"))

    def test_query_interface_raw_discarded_wrapper_is_not_consumed(self) -> None:
        body = (
            "\n"
            "    let _ = Ok(raw)\n"
            "    println(\"after\")\n"
        )

        self.assertFalse(abi.query_result_consumed(body, "raw"))

    def test_query_interface_raw_tail_wrapper_is_consumed(self) -> None:
        self.assertTrue(abi.query_result_consumed(" Some(descriptor.takeFromAbi(raw)) // tail\n", "raw"))
        self.assertTrue(abi.query_result_consumed(" Result<I>.Ok(raw)\n", "raw"))
        self.assertTrue(abi.query_result_consumed(" owner.close()\n Result<I>.Ok(raw)\n", "raw"))

    def test_query_interface_raw_direct_tail_value_is_consumed(self) -> None:
        self.assertTrue(abi.query_result_consumed(" raw\n", "raw"))

    def test_query_interface_raw_unknown_tail_wrapper_is_not_consumed(self) -> None:
        self.assertFalse(abi.query_result_consumed(" Some(debugWrap(raw))\n", "raw"))

    def test_query_interface_raw_unknown_return_wrapper_is_not_consumed(self) -> None:
        self.assertFalse(abi.query_result_consumed(" return Some(debugWrap(raw))\n", "raw"))
        self.assertFalse(abi.query_result_consumed(" return Ok(debugWrap(raw))\n", "raw"))
        self.assertFalse(abi.query_result_consumed(" return Result<I>.Ok(debugWrap(raw))\n", "raw"))

    def test_query_interface_raw_known_return_wrapper_is_consumed(self) -> None:
        self.assertTrue(abi.query_result_consumed(" return Some(descriptor.takeFromAbi(raw))\n", "raw"))
        self.assertTrue(abi.query_result_consumed(" return Ok(InterfaceHandle<I>.fromAbiTake(raw))\n", "raw"))
        self.assertTrue(abi.query_result_consumed(" return Result<I>.Ok(raw)\n", "raw"))
        self.assertTrue(abi.query_result_consumed(" return InterfaceHandle<I>.fromAbiTake(raw)\n", "raw"))

    def test_query_interface_raw_direct_tail_owned_wrapper_is_consumed(self) -> None:
        self.assertTrue(abi.query_result_consumed(" descriptor.takeFromAbi(raw)\n", "raw"))
        self.assertTrue(abi.query_result_consumed(" InterfaceHandle<I>.fromAbiTake(raw)\n", "raw"))
        self.assertTrue(abi.query_result_consumed(" windows_interface.IUnknown.fromAbiTake(raw)\n", "raw"))

    def test_query_interface_raw_discarded_owned_wrapper_is_not_consumed(self) -> None:
        self.assertFalse(abi.query_result_consumed(" let _ = descriptor.takeFromAbi(raw)\n", "raw"))
        self.assertFalse(abi.query_result_consumed(" let _ = IUnknown.fromAbiTake(raw)\n", "raw"))

    def test_generic_owned_constructor_routes_from_abi_take_to_guard(self) -> None:
        self.assertIsNotNone(abi.OWNED_CONSTRUCTOR_RE.search("OwnedHandler<TResult>(raw)"))

    def test_query_interface_raw_direct_return_is_consumed(self) -> None:
        self.assertTrue(abi.query_result_consumed(" return raw // transfers ownership\n", "raw"))

    def test_query_interface_raw_predicate_return_is_not_consumed(self) -> None:
        self.assertFalse(abi.query_result_consumed(" return raw.isNull()\n", "raw"))

    def test_query_interface_raw_predicate_tail_wrapper_is_not_consumed(self) -> None:
        self.assertFalse(abi.query_result_consumed(" Some(raw.isNull())\n", "raw"))

    def test_query_interface_raw_string_fake_release_is_not_consumed(self) -> None:
        body = (
            "\n"
            "    println(\"raw.close()\")\n"
            "    return None\n"
        )

        self.assertFalse(abi.query_result_consumed(body, "raw"))

    def test_query_interface_raw_raw_string_fake_release_is_not_consumed(self) -> None:
        body = (
            "\n"
            "    println(#\"descriptor.releasePointer(raw)\"#)\n"
            "    return None\n"
        )

        self.assertFalse(abi.query_result_consumed(body, "raw"))

    def test_query_interface_raw_block_comment_fake_release_is_not_consumed(self) -> None:
        body = (
            "\n"
            "    /* raw.close() */\n"
            "    return None\n"
        )

        self.assertFalse(abi.query_result_consumed(body, "raw"))

    def test_query_interface_raw_wrapper_before_statement_is_not_consumed(self) -> None:
        body = (
            "\n"
            "    Some(raw)\n"
            "    println(\"after\")\n"
        )

        self.assertFalse(abi.query_result_consumed(body, "raw"))

    def test_query_interface_raw_same_line_wrapper_before_statement_is_not_consumed(self) -> None:
        self.assertFalse(abi.query_result_consumed(" Some(raw); println(\"after\")\n", "raw"))
        self.assertFalse(abi.query_result_consumed(" Ok(raw); println(\"after\")\n", "raw"))

    def test_query_interface_raw_explicit_release_is_consumed(self) -> None:
        body = (
            "\n"
            "    let view = descriptor.viewOf(raw)\n"
            "    let _ = descriptor.releasePointer(raw)\n"
            "    view\n"
        )

        self.assertTrue(abi.query_result_consumed(body, "raw"))

    def test_query_interface_raw_one_branch_release_is_not_consumed(self) -> None:
        body = (
            "\n"
            "    if (shouldRelease) {\n"
            "        let _ = descriptor.releasePointer(raw)\n"
            "    }\n"
            "    println(\"after\")\n"
        )

        self.assertFalse(abi.query_result_consumed(body, "raw"))

    def test_query_interface_raw_catch_release_is_not_consumed(self) -> None:
        body = (
            "\n"
            "    try { risky() } catch (e: Exception) { raw.close() }\n"
            "    return None\n"
        )

        self.assertFalse(abi.query_result_consumed(body, "raw"))

    def test_query_interface_raw_lambda_release_is_not_consumed(self) -> None:
        body = (
            "\n"
            "    let cleanup = { => raw.close() }\n"
            "    return None\n"
        )

        self.assertFalse(abi.query_result_consumed(body, "raw"))

    def test_query_interface_raw_nested_function_release_is_not_consumed(self) -> None:
        body = (
            "\n"
            "    func cleanup(): Unit { raw.close() }\n"
            "    return None\n"
        )

        self.assertFalse(abi.query_result_consumed(body, "raw"))

    def test_query_interface_raw_finally_release_is_consumed(self) -> None:
        body = (
            "\n"
            "    try { risky() } finally { raw.close() }\n"
            "    return None\n"
        )

        self.assertTrue(abi.query_result_consumed(body, "raw"))

    def test_query_interface_raw_newline_braced_one_branch_release_is_not_consumed(self) -> None:
        body = (
            "\n"
            "    if (shouldRelease)\n"
            "    {\n"
            "        let _ = descriptor.releasePointer(raw)\n"
            "    }\n"
            "    println(\"after\")\n"
        )

        self.assertFalse(abi.query_result_consumed(body, "raw"))

    def test_query_interface_raw_nested_match_all_cases_release_is_consumed(self) -> None:
        body = (
            "\n"
            "    match (other()) {\n"
            "        case Some(value) =>\n"
            "            descriptor.releasePointer(raw)\n"
            "            Some(value)\n"
            "        case None =>\n"
            "            descriptor.releasePointer(raw)\n"
            "            None\n"
            "    }\n"
        )

        self.assertTrue(abi.query_result_consumed(body, "raw"))

    def test_query_interface_raw_unconditional_unsafe_release_is_consumed(self) -> None:
        body = (
            "\n"
            "    unsafe {\n"
            "        releasePointer(raw)\n"
            "    }\n"
            "    println(\"after\")\n"
        )

        self.assertTrue(abi.query_result_consumed(body, "raw"))

    def test_query_interface_raw_multiline_match_is_audited(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            (workspace / "cjpm.toml").write_text(
                "[workspace]\nmembers = [\"pkg\"]\n",
                encoding="utf-8",
            )
            source = workspace / "pkg" / "src" / "lib.cj"
            source.parent.mkdir(parents=True, exist_ok=True)
            source.write_text(
                (
                    "package pkg\n"
                    "func leak(): Unit {\n"
                    "    match (\n"
                    "        queryInterfaceRaw(source, iid)\n"
                    "    ) {\n"
                    "        case Some(raw) =>\n"
                    "            println(\"leaked\")\n"
                    "        case None => ()\n"
                    "    }\n"
                    "}\n"
                ),
                encoding="utf-8",
            )

            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                with self.assertRaises(SystemExit) as raised:
                    abi.check_query_interface_results_consumed(workspace)

            self.assertEqual(raised.exception.code, 1)
            self.assertIn("QueryInterface result 'raw'", stderr.getvalue())

    def test_query_interface_raw_inline_unsafe_match_is_audited(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            (workspace / "cjpm.toml").write_text(
                "[workspace]\nmembers = [\"pkg\"]\n",
                encoding="utf-8",
            )
            source = workspace / "pkg" / "src" / "lib.cj"
            source.parent.mkdir(parents=True, exist_ok=True)
            source.write_text(
                (
                    "package pkg\n"
                    "func leak(): Unit {\n"
                    "    match (unsafe { queryInterfaceRaw(source, iid) }) {\n"
                    "        case Some(raw) =>\n"
                    "            println(\"leaked\")\n"
                    "        case None => ()\n"
                    "    }\n"
                    "}\n"
                ),
                encoding="utf-8",
            )

            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                with self.assertRaises(SystemExit) as raised:
                    abi.check_query_interface_results_consumed(workspace)

            self.assertEqual(raised.exception.code, 1)
            self.assertIn("QueryInterface result 'raw'", stderr.getvalue())

    def test_query_interface_raw_stored_before_match_is_audited(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            (workspace / "cjpm.toml").write_text(
                "[workspace]\nmembers = [\"pkg\"]\n",
                encoding="utf-8",
            )
            source = workspace / "pkg" / "src" / "lib.cj"
            source.parent.mkdir(parents=True, exist_ok=True)
            source.write_text(
                (
                    "package pkg\n"
                    "func leak(): Unit {\n"
                    "    let result = unsafe { queryInterfaceRaw(source, iid) }\n"
                    "    match (result) {\n"
                    "        case Some(raw) =>\n"
                    "            println(\"leaked\")\n"
                    "        case None => ()\n"
                    "    }\n"
                    "}\n"
                ),
                encoding="utf-8",
            )

            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                with self.assertRaises(SystemExit) as raised:
                    abi.check_query_interface_results_consumed(workspace)

            self.assertEqual(raised.exception.code, 1)
            self.assertIn("QueryInterface result 'raw'", stderr.getvalue())

    def test_query_interface_raw_typed_stored_before_match_is_audited(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            (workspace / "cjpm.toml").write_text(
                "[workspace]\nmembers = [\"pkg\"]\n",
                encoding="utf-8",
            )
            source = workspace / "pkg" / "src" / "lib.cj"
            source.parent.mkdir(parents=True, exist_ok=True)
            source.write_text(
                (
                    "package pkg\n"
                    "func leak(): Unit {\n"
                    "    let result: Option<CPointer<Unit>> = unsafe { queryInterfaceRaw(source, iid) }\n"
                    "    match (result) {\n"
                    "        case Some(raw) =>\n"
                    "            println(\"leaked\")\n"
                    "        case None => ()\n"
                    "    }\n"
                    "}\n"
                ),
                encoding="utf-8",
            )

            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                with self.assertRaises(SystemExit) as raised:
                    abi.check_query_interface_results_consumed(workspace)

            self.assertEqual(raised.exception.code, 1)
            self.assertIn("QueryInterface result 'raw'", stderr.getvalue())

    def test_query_interface_raw_qualified_stored_before_match_is_audited(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            (workspace / "cjpm.toml").write_text(
                "[workspace]\nmembers = [\"pkg\"]\n",
                encoding="utf-8",
            )
            source = workspace / "pkg" / "src" / "lib.cj"
            source.parent.mkdir(parents=True, exist_ok=True)
            source.write_text(
                (
                    "package pkg\n"
                    "func leak(): Unit {\n"
                    "    let result = windows_core.queryInterfaceRaw(source, iid)\n"
                    "    match (result) {\n"
                    "        case Some(raw) =>\n"
                    "            println(\"leaked\")\n"
                    "        case None => ()\n"
                    "    }\n"
                    "}\n"
                ),
                encoding="utf-8",
            )

            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                with self.assertRaises(SystemExit) as raised:
                    abi.check_query_interface_results_consumed(workspace)

            self.assertEqual(raised.exception.code, 1)
            self.assertIn("QueryInterface result 'raw'", stderr.getvalue())

    def test_discarded_owned_wrapper_assignment_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            (workspace / "cjpm.toml").write_text(
                "[workspace]\nmembers = [\"pkg\"]\n",
                encoding="utf-8",
            )
            source = workspace / "pkg" / "src" / "lib.cj"
            source.parent.mkdir(parents=True, exist_ok=True)
            source.write_text(
                (
                    "package pkg\n"
                    "func leak(raw: CPointer<Unit>): Unit {\n"
                    "    let _ = windows_interface.IUnknown.fromAbiTake(raw)\n"
                    "}\n"
                ),
                encoding="utf-8",
            )

            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                with self.assertRaises(SystemExit) as raised:
                    abi.check_discarded_owned_wrappers(workspace)

            self.assertEqual(raised.exception.code, 1)
            self.assertIn("owned ABI wrapper constructors must not be discarded", stderr.getvalue())


class IgnoredResultsAuditTests(unittest.TestCase):
    def test_constructor_receiver_ok_before_outer_work_is_rejected(self) -> None:
        lines = [
            "public func ok(): Result<Unit> {",
            "    HRESULT(hr).ok()",
            "    println(\"after\")",
            "}",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), ["<test>:2: ignored Result.ok() value"])

    def test_unsafe_block_receiver_ok_before_outer_work_is_rejected(self) -> None:
        lines = [
            "public func ok(): Result<Unit> {",
            "    HRESULT(unsafe { table.RemoveClick(raw, token) }).ok()",
            "    println(\"after\")",
            "}",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), ["<test>:2: ignored Result.ok() value"])

    def test_stored_constructor_receiver_ok_is_allowed(self) -> None:
        lines = [
            "public func ok(): Result<Unit> {",
            "    let result = HRESULT(hr).ok()",
            "    result",
            "}",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), [])

    def test_discarded_ok_assignment_with_semicolon_is_rejected(self) -> None:
        lines = [
            "public func ok(): Unit {",
            "    let _ = hr.ok();",
            "}",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), ["<test>:2: ignored Result.ok() value"])

    def test_typed_discarded_ok_assignment_is_rejected(self) -> None:
        lines = [
            "public func ok(): Unit {",
            "    let _: windows_core.Result<Unit> = hr.ok()",
            "}",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), ["<test>:2: ignored Result.ok() value"])

    def test_var_discarded_ok_assignment_is_rejected(self) -> None:
        lines = [
            "public func ok(): Unit {",
            "    var _ = hr.ok()",
            "}",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), ["<test>:2: ignored Result.ok() value"])

    def test_parenthesized_discarded_ok_assignment_is_rejected(self) -> None:
        lines = [
            "public func ok(): Unit {",
            "    let _ = (hr.ok())",
            "}",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), ["<test>:2: ignored Result.ok() value"])

    def test_discarded_conditional_ok_assignment_is_rejected(self) -> None:
        lines = [
            "public func ok(condition: Bool): Unit {",
            "    let _ = if (condition) { hr.ok() } else { other.ok() }",
            "}",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), ["<test>:2: ignored Result.ok() value"])

    def test_multiline_discarded_ok_assignment_is_rejected(self) -> None:
        lines = [
            "public func ok(): Unit {",
            "    let _ =",
            "        hr.ok()",
            "}",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), ["<test>:2: ignored Result.ok() value"])

    def test_multiline_discarded_match_ok_assignment_is_rejected(self) -> None:
        lines = [
            "public func ok(): Unit {",
            "    let _ =",
            "        match (value) {",
            "            case Some(_) => hr.ok()",
            "            case None => other.ok()",
            "        }",
            "}",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), ["<test>:2: ignored Result.ok() value"])

    def test_same_line_statement_ok_before_work_is_rejected(self) -> None:
        lines = [
            "public func ok(): Unit {",
            "    hr.ok(); println(\"after\")",
            "}",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), ["<test>:2: ignored Result.ok() value"])

    def test_same_line_ok_before_work_with_block_comment_brace_is_rejected(self) -> None:
        lines = [
            "public func ok(): Unit {",
            "    hr.ok() /* { */; println(\"after\")",
            "}",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), ["<test>:2: ignored Result.ok() value"])

    def test_parenthesized_statement_ok_before_work_is_rejected(self) -> None:
        lines = [
            "public func ok(): Unit {",
            "    (hr.ok());",
            "    println(\"after\")",
            "}",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), ["<test>:2: ignored Result.ok() value"])

    def test_same_line_discarded_ok_assignment_before_work_is_rejected(self) -> None:
        lines = [
            "public func ok(): Unit {",
            "    let _ = hr.ok(); println(\"after\")",
            "}",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), ["<test>:2: ignored Result.ok() value"])

    def test_inline_function_body_ok_before_work_is_rejected(self) -> None:
        lines = [
            "public func ok(): Unit { hr.ok(); println(\"after\") }",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), ["<test>:1: ignored Result.ok() value"])

    def test_function_tail_ok_before_next_declaration_is_allowed(self) -> None:
        lines = [
            "public func ok(): Result<Unit> {",
            "    hr.ok()",
            "}",
            "public func other(): Bool {",
            "    true",
            "}",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), [])

    def test_loop_tail_ok_is_rejected(self) -> None:
        while_lines = [
            "public func ok(): Unit {",
            "    while (condition) {",
            "        hr.ok()",
            "    }",
            "}",
        ]
        self.assertEqual(ignored.scan_lines("<test>", while_lines), ["<test>:3: ignored Result.ok() value"])

        for_lines = [
            "public func ok(): Unit {",
            "    for (item in items) {",
            "        hr.ok()",
            "    }",
            "}",
        ]
        self.assertEqual(ignored.scan_lines("<test>", for_lines), ["<test>:3: ignored Result.ok() value"])

    def test_branch_tail_ok_before_outer_work_is_rejected(self) -> None:
        lines = [
            "public func ok(): Result<Unit> {",
            "    if (condition) {",
            "        hr.ok()",
            "    }",
            "    println(\"after\")",
            "}",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), ["<test>:3: ignored Result.ok() value"])

    def test_inline_if_body_nontail_ok_is_rejected(self) -> None:
        lines = [
            "public func ok(): Unit {",
            "    if (condition) { hr.ok(); println(\"after\") }",
            "}",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), ["<test>:2: ignored Result.ok() value"])

    def test_assigned_inline_control_ok_before_lambda_work_is_rejected(self) -> None:
        lines = [
            "public func ok(): Unit {",
            "    let f = { => if (condition) { HRESULT(hr).ok() }; println(\"after\") }",
            "}",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), ["<test>:2: ignored Result.ok() value"])

    def test_assigned_lambda_tail_ok_is_allowed(self) -> None:
        lines = [
            "public func ok(): Unit {",
            "    let f = { => HRESULT(hr).ok() }",
            "}",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), [])

    def test_inline_case_body_nontail_ok_is_rejected(self) -> None:
        lines = [
            "public func ok(): Unit {",
            "    match (value) {",
            "        case Some(_) => hr.ok(); println(\"after\")",
            "        case None => other.ok()",
            "    }",
            "}",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), ["<test>:3: ignored Result.ok() value"])

    def test_single_line_inline_case_body_nontail_ok_is_rejected(self) -> None:
        lines = [
            "public func ok(): Unit {",
            "    match (value) { case Some(_) => hr.ok(); println(\"after\") case None => () }",
            "}",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), ["<test>:2: ignored Result.ok() value"])

    def test_inline_braced_case_body_nontail_ok_is_rejected(self) -> None:
        lines = [
            "public func ok(): Unit {",
            "    match (value) {",
            "        case Some(_) => { hr.ok(); println(\"after\") }",
            "        case None => other.ok()",
            "    }",
            "}",
        ]

        self.assertEqual(ignored.scan_lines("<test>", lines), ["<test>:3: ignored Result.ok() value"])

    def test_try_tail_ok_before_outer_work_is_rejected(self) -> None:
        lines = [
            "public func ok(): Result<Unit> {",
            "    try {",
            "        hr.ok()",
            "    } catch (e: Exception) {",
            "        other.ok()",
            "    }",
            "    println(\"after\")",
            "}",
        ]

        self.assertEqual(
            ignored.scan_lines("<test>", lines),
            [
                "<test>:3: ignored Result.ok() value",
                "<test>:5: ignored Result.ok() value",
            ],
        )

    def test_match_arm_tail_ok_before_outer_work_is_rejected(self) -> None:
        lines = [
            "public func ok(): Result<Unit> {",
            "    match (value) {",
            "        case Some(_) => {",
            "            hr.ok()",
            "        }",
            "        case None => {",
            "            other.ok()",
            "        }",
            "    }",
            "    println(\"after\")",
            "}",
        ]

        self.assertEqual(
            ignored.scan_lines("<test>", lines),
            [
                "<test>:4: ignored Result.ok() value",
                "<test>:7: ignored Result.ok() value",
            ],
        )

    def test_inline_match_arm_tail_ok_before_outer_work_is_rejected(self) -> None:
        lines = [
            "public func ok(): Result<Unit> {",
            "    match (value) {",
            "        case Some(_) => hr.ok()",
            "        case None => other.ok()",
            "    }",
            "    println(\"after\")",
            "}",
        ]

        self.assertEqual(
            ignored.scan_lines("<test>", lines),
            [
                "<test>:3: ignored Result.ok() value",
                "<test>:4: ignored Result.ok() value",
            ],
        )

    def test_inline_if_else_tail_ok_before_outer_work_is_rejected(self) -> None:
        lines = [
            "public func ok(): Result<Unit> {",
            "    if (condition) {",
            "        hr.ok()",
            "    } else { other.ok() }",
            "    println(\"after\")",
            "}",
        ]

        self.assertEqual(
            ignored.scan_lines("<test>", lines),
            [
                "<test>:3: ignored Result.ok() value",
                "<test>:4: ignored Result.ok() value",
            ],
        )


class ShellScriptGateTests(unittest.TestCase):
    def test_rejects_power_shell_and_batch_scripts(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            write_file(workspace, "tools/build.ps1")
            write_file(workspace, "tools/build.bat")
            write_file(workspace, ".git/ignored.ps1")
            write_file(workspace, "target/ignored.bat")

            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                with self.assertRaises(SystemExit) as raised:
                    setup.check_no_shell_scripts(workspace)

            self.assertEqual(raised.exception.code, 1)
            message = stderr.getvalue()
            self.assertIn("tools/build.ps1", message)
            self.assertIn("tools/build.bat", message)
            self.assertNotIn("ignored.ps1", message)
            self.assertNotIn("ignored.bat", message)


class WinuiXamlHelperGateTests(unittest.TestCase):
    def write_xaml_helper(self, workspace: Path, text: str) -> None:
        path = workspace / "windows-winui3" / "src" / "xaml" / "mod.cj"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")

    def test_rejects_winui_failed_out_slot_check_before_cleanup(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            self.write_xaml_helper(
                workspace,
                (
                    "func create(): Unit {\n"
                    "    checkHRESULT(hr, \"IWindowFactory.CreateInstance\")\n"
                    "}\n"
                    "func releaseFailedWinuiOutSlot(slot: CPointer<CPointer<Unit>>): Unit {\n"
                    "    releaseRaw(raw)\n"
                    "}\n"
                    "func readWinuiVtbl<T>(): Unit {}\n"
                ),
            )

            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                with self.assertRaises(SystemExit) as raised:
                    setup.check_winui_xaml_failed_out_cleanup(workspace)

            self.assertEqual(raised.exception.code, 1)
            self.assertIn("IWindowFactory.CreateInstance", stderr.getvalue())

    def test_accepts_winui_failed_out_slot_cleanup_before_check(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            self.write_xaml_helper(
                workspace,
                (
                    "func create(): Unit {\n"
                    "    releaseFailedWinuiOutSlot(CPointer<CPointer<Unit>>(inout inner))\n"
                    "    releaseFailedWinuiOutSlot(CPointer<CPointer<Unit>>(inout result))\n"
                    "    checkHRESULT(hr, \"IWindowFactory.CreateInstance\")\n"
                    "    releaseFailedWinuiOutSlot(CPointer<CPointer<Unit>>(inout result))\n"
                    "    checkHRESULT(hr, \"IFrameworkElement.FindName(${name})\")\n"
                    "    releaseFailedWinuiOutSlot(CPointer<CPointer<Unit>>(inout result))\n"
                    "    checkHRESULT(hr, \"IXamlReaderStatics.Load\")\n"
                    "}\n"
                    "func releaseFailedWinuiOutSlot(slot: CPointer<CPointer<Unit>>): Unit {\n"
                    "    unsafe { slot.write(CPointer<Unit>()) }\n"
                    "    releaseRaw(raw)\n"
                    "}\n"
                    "func readWinuiVtbl<T>(): Unit {}\n"
                ),
            )

            setup.check_winui_xaml_failed_out_cleanup(workspace)


class WindowsStringFinalizerGateTests(unittest.TestCase):
    def write_string_sources(self, workspace: Path, ref_count_text: str, native_text: str) -> None:
        strings = workspace / "windows-strings" / "src"
        strings.mkdir(parents=True, exist_ok=True)
        (strings / "ref_count.cj").write_text(ref_count_text, encoding="utf-8")
        (strings / "native.cj").write_text(native_text, encoding="utf-8")

    def test_rejects_hstring_ref_count_mutex(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            self.write_string_sources(
                workspace,
                "package windows_strings\nimport std.sync.Mutex\n",
                "package windows_strings\nfunc sysFreeStringAbi(ptr: CPointer<UInt16>): Unit {}\n",
            )

            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                with self.assertRaises(SystemExit) as raised:
                    setup.check_windows_string_finalizer_paths_are_lock_free(workspace)

            self.assertEqual(raised.exception.code, 1)
            self.assertIn("HString finalizer ref-count release lock-free", stderr.getvalue())

    def test_rejects_bstr_finalizer_symbol_resolution(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            self.write_string_sources(
                workspace,
                "package windows_strings\n",
                (
                    "package windows_strings\n"
                    "let sysFreeStringProc = windows_libloading.FinalizerSafeProc(\"oleaut32.dll\", \"SysFreeString\")\n"
                    "func sysFreeStringAbi(ptr: CPointer<UInt16>): Unit {\n"
                    "    let proc = resolveOleaut32Proc(\"SysFreeString\")\n"
                    "}\n"
                ),
            )

            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                with self.assertRaises(SystemExit) as raised:
                    setup.check_windows_string_finalizer_paths_are_lock_free(workspace)

            self.assertEqual(raised.exception.code, 1)
            self.assertIn("must not resolve symbols during finalization", stderr.getvalue())

    def test_requires_bstr_finalizer_safe_proc_table(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            self.write_string_sources(
                workspace,
                "package windows_strings\n",
                "package windows_strings\nfunc sysFreeStringAbi(ptr: CPointer<UInt16>): Unit {}\n",
            )

            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                with self.assertRaises(SystemExit) as raised:
                    setup.check_windows_string_finalizer_paths_are_lock_free(workspace)

            self.assertEqual(raised.exception.code, 1)
            self.assertIn("FinalizerSafeProc", stderr.getvalue())


class FinalizerCleanupGateTests(unittest.TestCase):
    def write_cj_source(self, workspace: Path, relative: str, text: str) -> None:
        path = workspace / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")

    def test_rejects_indirect_cleanup_helper_in_finalizer(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            self.write_cj_source(
                workspace,
                "windows-variant/src/variant_resource.cj",
                (
                    "package windows_variant\n"
                    "class VariantOwner {\n"
                    "    var closed: Bool = false\n"
                    "    ~init() {\n"
                    "        if (!closed) {\n"
                    "            releaseVariantStorageNoThrow(storage, false)\n"
                    "            closed = true\n"
                    "        }\n"
                    "    }\n"
                    "}\n"
                ),
            )

            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                with self.assertRaises(SystemExit) as raised:
                    setup.check_finalizers_do_not_block_on_locks(workspace)

            self.assertEqual(raised.exception.code, 1)
            self.assertIn("releaseVariantStorageNoThrow(", stderr.getvalue())

    def test_rejects_cleanup_helper_after_brace_in_string_literal_in_finalizer(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            self.write_cj_source(
                workspace,
                "windows-variant/src/variant_resource.cj",
                (
                    "package windows_variant\n"
                    "class VariantOwner {\n"
                    "    var closed: Bool = false\n"
                    "    ~init() {\n"
                    "        let marker = \"}\"\n"
                    "        if (!closed) {\n"
                    "            releaseVariantStorageNoThrow(storage, false)\n"
                    "            closed = true\n"
                    "        }\n"
                    "    }\n"
                    "}\n"
                ),
            )

            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                with self.assertRaises(SystemExit) as raised:
                    setup.check_finalizers_do_not_block_on_locks(workspace)

            self.assertEqual(raised.exception.code, 1)
            self.assertIn("releaseVariantStorageNoThrow(", stderr.getvalue())

    def test_rejects_array_proxy_clear_in_finalizer(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            self.write_cj_source(
                workspace,
                "windows-core/src/array_proxy.cj",
                (
                    "package windows_core\n"
                    "class ArrayProxy<T> {\n"
                    "    var closed: Bool = false\n"
                    "    let staged = AbiArray<T>()\n"
                    "    ~init() {\n"
                    "        if (!closed) {\n"
                    "            staged.clear()\n"
                    "            closed = true\n"
                    "        }\n"
                    "    }\n"
                    "}\n"
                ),
            )

            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                with self.assertRaises(SystemExit) as raised:
                    setup.check_finalizers_do_not_block_on_locks(workspace)

            self.assertEqual(raised.exception.code, 1)
            self.assertIn("array_proxy.cj", stderr.getvalue())
            self.assertIn(".clear()", stderr.getvalue())

    def test_allows_cleanup_helpers_outside_finalizers(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            self.write_cj_source(
                workspace,
                "windows-variant/src/variant_resource.cj",
                (
                    "package windows_variant\n"
                    "class VariantOwner {\n"
                    "    var closed: Bool = false\n"
                    "    public func close(): Unit {\n"
                    "        releaseVariantStorageNoThrow(storage, false)\n"
                    "        closed = true\n"
                    "    }\n"
                    "    ~init() {\n"
                    "        closed = true\n"
                    "    }\n"
                    "}\n"
                ),
            )
            self.write_cj_source(
                workspace,
                "windows-strings/src/native.cj",
                (
                    "package windows_strings\n"
                    "func sysFreeStringAbi(ptr: CPointer<UInt16>): Unit {\n"
                    "    releaseBstrStorageNoThrow(ptr, true, false)\n"
                    "}\n"
                ),
            )

            setup.check_finalizers_do_not_block_on_locks(workspace)

    def test_allows_windows_string_finalizer_safe_no_throw_cleanup_helpers(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            self.write_cj_source(
                workspace,
                "windows-strings/src/hstring.cj",
                (
                    "package windows_strings\n"
                    "class HStringOwner {\n"
                    "    var closed: Bool = false\n"
                    "    ~init() {\n"
                    "        let (_, _, nextClosed) = closeHStringStateNoThrow(storage, closed)\n"
                    "        closed = nextClosed\n"
                    "    }\n"
                    "}\n"
                ),
            )

            setup.check_finalizers_do_not_block_on_locks(workspace)

    def test_rejects_native_no_throw_close_helpers_in_finalizer(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            self.write_cj_source(
                workspace,
                "windows-variant/src/variant_resource.cj",
                (
                    "package windows_variant\n"
                    "class VariantOwner {\n"
                    "    var closed: Bool = false\n"
                    "    ~init() {\n"
                    "        closed = closeVariantStateNoThrow(storage, closed)\n"
                    "    }\n"
                    "}\n"
                ),
            )

            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                with self.assertRaises(SystemExit) as raised:
                    setup.check_finalizers_do_not_block_on_locks(workspace)

            self.assertEqual(raised.exception.code, 1)
            self.assertIn("closeVariantStateNoThrow(", stderr.getvalue())

    def test_rejects_unapproved_no_throw_close_helper_in_finalizer(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            self.write_cj_source(
                workspace,
                "windows-core/src/native_owner.cj",
                (
                    "package windows_core\n"
                    "class NativeOwner {\n"
                    "    var closed: Bool = false\n"
                    "    ~init() {\n"
                    "        closed = closeUnknownStateNoThrow(storage, closed)\n"
                    "    }\n"
                    "}\n"
                ),
            )

            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                with self.assertRaises(SystemExit) as raised:
                    setup.check_finalizers_do_not_block_on_locks(workspace)

            self.assertEqual(raised.exception.code, 1)
            self.assertIn("closeUnknownStateNoThrow(", stderr.getvalue())

    def test_ignores_finalizer_text_inside_string_literals(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir)
            self.write_cj_source(
                workspace,
                "windows-result/src/internal_test.cj",
                (
                    "package windows_result\n"
                    "func expectedGeneratedBody(): Unit {\n"
                    "    let oldLfReleaseBody = \"~init() {\\n"
                    "        if (!closed) {\\n"
                    "            releaseVariantStorageNoThrow(storage, false)\"\n"
                    "}\n"
                ),
            )

            setup.check_finalizers_do_not_block_on_locks(workspace)


if __name__ == "__main__":
    unittest.main()
