#!/usr/bin/env python3
"""Shared checks for the checked-in windows_common generated package manifest."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


GENERATED_MANIFEST_HEADER = "Generated by windows_bindgen. DO NOT EDIT."
IGNORED_GENERATED_FILES = frozenset({"README.md", "codegen-manifest.json", "cjpm.lock"})


class ManifestError(RuntimeError):
    pass


def rel_posix(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def normalized_file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes().replace(b"\r\n", b"\n")).hexdigest()


def load_manifest(
    root: Path,
    *,
    expected_header: str = GENERATED_MANIFEST_HEADER,
    expected_package: str = "windows_common",
) -> dict:
    path = root / "codegen-manifest.json"
    try:
        manifest = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ManifestError(f"missing windows_common manifest: {path}") from exc
    if manifest.get("generated_by") != expected_header:
        raise ManifestError("windows_common manifest generated_by marker is missing or wrong")
    if manifest.get("package_name") != expected_package:
        raise ManifestError(f"windows_common manifest package_name mismatch: {manifest.get('package_name')!r}")
    return manifest


def manifest_files(manifest: dict) -> list[str]:
    files = manifest.get("files")
    if not isinstance(files, list) or not all(isinstance(entry, str) for entry in files):
        raise ManifestError("windows_common manifest files must be a string array")
    if not files:
        raise ManifestError("windows_common manifest must list generated files")
    if len(files) != len(set(files)):
        raise ManifestError("windows_common manifest files contain duplicates")
    return files


def manifest_hashes(manifest: dict) -> dict[str, str]:
    hashes = manifest.get("file_hashes")
    if not isinstance(hashes, dict) or not all(isinstance(k, str) and isinstance(v, str) for k, v in hashes.items()):
        raise ManifestError("windows_common manifest file_hashes must be a string map")
    files = set(manifest_files(manifest))
    keys = set(hashes)
    if keys != files:
        raise ManifestError(
            f"windows_common manifest hash key mismatch; missing={sorted(files - keys)}, extra={sorted(keys - files)}"
        )
    return dict(hashes)


def requested_features(
    manifest: dict,
    *,
    prefix: str | None = None,
    require_nonempty: bool = False,
) -> list[str]:
    features = manifest.get("requested_features", [])
    if not isinstance(features, list) or not all(isinstance(entry, str) for entry in features):
        raise ManifestError("windows_common manifest requested_features must be a string array")
    if require_nonempty and not features:
        raise ManifestError("windows_common manifest requested_features is empty")
    if prefix is None:
        return list(features)
    return [feature for feature in features if feature.startswith(prefix)]


def generated_tree_files(root: Path, *, ignored_files: frozenset[str] = IGNORED_GENERATED_FILES) -> set[str]:
    files: set[str] = set()
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        relative = rel_posix(path, root)
        if relative.startswith("target/") or relative in ignored_files:
            continue
        files.add(relative)
    return files


def validate_manifest_hashes(
    root: Path,
    *,
    expected_header: str = GENERATED_MANIFEST_HEADER,
    expected_package: str = "windows_common",
) -> dict:
    manifest = load_manifest(root, expected_header=expected_header, expected_package=expected_package)
    files = set(manifest_files(manifest))
    hashes = manifest_hashes(manifest)
    actual_files = generated_tree_files(root)
    if actual_files != files:
        raise ManifestError(
            f"windows_common generated file set mismatch; "
            f"missing={sorted(files - actual_files)}, extra={sorted(actual_files - files)}"
        )

    mismatches: list[str] = []
    for relative in sorted(files):
        actual_hash = normalized_file_sha256(root / relative)
        if hashes[relative] != actual_hash:
            mismatches.append(relative)
    if mismatches:
        raise ManifestError(f"windows_common manifest hash mismatch: {mismatches[:10]}")
    return manifest
