[package]
  name = "windows_interface"
  version = "0.1.0"
  description = "Windows interface descriptors and wrappers for Cangjie bindings"
  authors = ["Zxilly"]
  repository = "https://github.com/Zxilly/windows-cj"
  license = ["MIT"]
  output-type = "static"
  cjc-version = "1.1.0"

  compile-option = "--experimental --incremental-compile"
[dependencies]
  windows_result = { path = "../windows_result" }
  windows_strings = { path = "../windows_strings" }
