#!/usr/bin/env python3
"""Verify the active windows-cj workspace layout.

This script intentionally checks the current JSON-backed Cangjie generator
layout. Legacy cfg-era and Python bindgen packages must live outside this
workspace under the sibling deprecated_windows_cj directory.
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path


ACTIVE_WORKSPACE_MEMBERS = {
    "windows-metadata",
    "windows-libloading",
    "windows-result",
    "windows-strings",
    "windows-interface",
    "windows-implement",
    "windows-core",
    "windows-polyfill",
    "windows-future",
    "windows-collections",
    "windows-numerics",
    "windows-threading",
    "windows-version",
    "windows-targets",
    "windows-registry",
    "windows-services",
    "windows-common",
    "windows",
}

REFERENCE_ONLY_PACKAGES = {
    "windows-sys",
    "windows-webview2-sys",
    "windows-appsdk-sys",
    "windows-webview2",
    "windows-appsdk",
    "windows-bindgen",
    "windows-bindgen-legacy",
    "windows-cfggen",
    "windows-cfggen-legacy",
    "windows-cj-bindgen-py",
    "windows-cj-cfggen-py",
}


def fail(message: str) -> None:
    print(f"FAIL: {message}", file=sys.stderr)
    sys.exit(1)


def check_path_exists(path: Path, kind: str) -> None:
    if not path.exists():
        fail(f"missing {kind}: {path}")


def load_toml(path: Path) -> dict:
    with path.open("rb") as f:
        return tomllib.load(f)


def check_workspace_members(workspace: Path) -> None:
    config = load_toml(workspace / "cjpm.toml")
    members = set(config.get("workspace", {}).get("members", []))
    if members != ACTIVE_WORKSPACE_MEMBERS:
        missing = sorted(ACTIVE_WORKSPACE_MEMBERS - members)
        extra = sorted(members - ACTIVE_WORKSPACE_MEMBERS)
        fail(f"workspace members mismatch; missing={missing}, extra={extra}")
    for member in sorted(members):
        root = workspace / member
        check_path_exists(root / "cjpm.toml", f"{member} cjpm.toml")
        check_path_exists(root / "src", f"{member} src/")


def check_reference_only_packages(workspace: Path) -> None:
    deprecated_root = workspace.parent / "deprecated_windows_cj"
    check_path_exists(deprecated_root, "deprecated_windows_cj root")
    for name in sorted(REFERENCE_ONLY_PACKAGES):
        active_root = workspace / name
        if active_root.exists():
            fail(f"{name} must be moved out of windows-cj; found {active_root}")
        archived_root = deprecated_root / name
        check_path_exists(archived_root, f"{name} deprecated reference root")
        check_path_exists(archived_root / "REFERENCE_ONLY.md", f"{name} REFERENCE_ONLY.md")


def check_generated_common_package(workspace: Path) -> None:
    generated = workspace / "windows-common"
    check_path_exists(generated / "cjpm.toml", "windows-common cjpm.toml")
    check_path_exists(generated / "src" / "support_deps.cj", "windows-common support_deps.cj")
    check_path_exists(generated / "src" / "mod.cj", "windows-common mod.cj")
    first_line = (generated / "src" / "mod.cj").read_text(encoding="utf-8").splitlines()[0]
    if first_line != "// Generated by windows-gen. DO NOT EDIT.":
        fail("windows-common generated files must start with the generated-by header")
    config = load_toml(generated / "cjpm.toml")
    package = config.get("package", {})
    if package.get("name") != "windows_common":
        fail(f"windows-common package name must be windows_common, got {package.get('name')!r}")


def check_active_tools(workspace: Path) -> None:
    check_path_exists(workspace / "windows" / "src" / "main.cj", "Cangjie bindgen CLI")
    check_path_exists(workspace / "windows" / "src" / "json_loader.cj", "JSON loader")
    check_path_exists(workspace / "winmd-to-json" / "Program.cs", "winmd-to-json source")
    check_path_exists(workspace / "windows-winui3" / "src" / "xaml" / "mod.cj", "WinUI3 XAML helper")


def main() -> None:
    workspace = Path(__file__).resolve().parent.parent
    print(f"workspace = {workspace}")
    check_workspace_members(workspace)
    print("OK: active workspace members match JSON-backed layout")
    check_reference_only_packages(workspace)
    print("OK: reference-only packages live under deprecated_windows_cj")
    check_generated_common_package(workspace)
    print("OK: generated windows-common package is present and marked DO NOT EDIT")
    check_active_tools(workspace)
    print("OK: active Cangjie generator and WinUI helper files are present")


if __name__ == "__main__":
    main()
