# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""Select which windows_common namespaces are compiled, via cfg.toml rewriting.

windows_common is generated with one Cangjie cfg variable per namespace (the
namespace with '.' replaced by '_') and every top-level declaration gated by
`@When[<ns_var> == "on"]`. The per-package ``cfg.toml`` files default every
variable to ``"off"`` (opt-in baseline: nothing is compiled). This tool reads the
generated ``namespace-deps.json`` dependency map, computes the transitive closure
of the namespaces a consumer enables, and rewrites every ``cfg.toml`` under the
package so the selected namespaces (and their closure) are ``"on"`` and the rest
are ``"off"``.

This mirrors the reference projection's per-namespace feature flags: a consumer
declares the namespaces it needs and the build only compiles those (plus the
namespaces they transitively reference).

The cfg.toml-rewriting modes (``--enable`` / ``--all`` / ``--none``) mutate
windows_common's single global state and are therefore only suitable for
*standalone* windows_common builds and measurements. The recommended per-consumer
path is ``--emit-override`` / ``--write-override``: these compute the same
transitive closure but emit a complete ``override-compile-option`` ``--cfg`` string
that a consumer injects into its own ``cjpm.toml``. Because cjpm's
``override-compile-option`` from the entry module applies to every dependency
package (and wins over cfg.toml), each consumer selects its own namespaces without
touching windows_common's shared cfg.toml.

Usage::

    # enable a set of namespaces (plus their transitive closure)
    python tools/select_features.py --enable Windows.Foundation,Microsoft.UI.Xaml

    # enable everything (compatibility / full regression build)
    python tools/select_features.py --all

    # print the computed closure without writing anything
    python tools/select_features.py --enable Windows.Foundation --print-closure

    # print the complete override-compile-option string for a consumer
    python tools/select_features.py --emit-override Win32.System.Registry,Win32.Security

    # write/update that string into a consumer's cjpm.toml [package] section
    python tools/select_features.py --emit-override Windows.Foundation \\
        --write-override windows_foundation/cjpm.toml

The default package is ``windows_common`` next to this repo root; override with
``--package-dir``.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import deque
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PACKAGE_DIR = ROOT / "windows_common"
NAMESPACE_DEPS_NAME = "namespace-deps.json"
CFG_TOML_NAME = "cfg.toml"
GENERATED_HEADER = "# Generated by windows_bindgen. DO NOT EDIT.\n\n"
# The impl package's cfg.toml declares the complete universe of namespace cfg
# variables (every variable any @When may reference). An override-compile-option
# --cfg must list *all* of them (omitting any referenced variable triggers
# "conditional compilation have not supported this condition").
OVERRIDE_VARS_SOURCE = ("src", "impl", CFG_TOML_NAME)


def fail(message: str) -> "NoReturn":  # type: ignore[name-defined]
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def namespace_to_cfg_var(namespace: str) -> str:
    """Mirror the generator's namespaceToCfgVar: '.' -> '_', empty -> sentinel."""
    if namespace == "":
        return "Windows_root"
    return namespace.replace(".", "_")


def load_namespace_deps(package_dir: Path) -> dict[str, list[str]]:
    path = package_dir / NAMESPACE_DEPS_NAME
    if not path.exists():
        fail(
            f"missing {NAMESPACE_DEPS_NAME} under {package_dir}. Regenerate windows_common "
            "with the current generator (scripts/regenerate_windows_common.py)."
        )
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        fail(f"{path} is not valid JSON: {exc}")
    if not isinstance(data, dict):
        fail(f"{path} must be a JSON object mapping namespace -> [namespaces]")
    deps: dict[str, list[str]] = {}
    for key, value in data.items():
        if not isinstance(key, str) or not isinstance(value, list) or not all(isinstance(v, str) for v in value):
            fail(f"{path} entries must map a namespace string to a string array")
        deps[key] = list(value)
    return deps


def all_namespaces(deps: dict[str, list[str]]) -> set[str]:
    namespaces: set[str] = set(deps)
    for targets in deps.values():
        namespaces.update(targets)
    return namespaces


def transitive_closure(seeds: list[str], deps: dict[str, list[str]]) -> set[str]:
    known = all_namespaces(deps)
    unknown = [s for s in seeds if s not in known]
    if unknown:
        fail(
            "unknown namespace(s) not present in the dependency map: "
            f"{sorted(unknown)}. Known namespaces include e.g. "
            f"{sorted(known)[:5]}..."
        )
    closure: set[str] = set()
    queue: deque[str] = deque(seeds)
    while queue:
        ns = queue.popleft()
        if ns in closure:
            continue
        closure.add(ns)
        for target in deps.get(ns, []):
            if target not in closure:
                queue.append(target)
    return closure


def all_cfg_vars(package_dir: Path) -> list[str]:
    """Return the complete, sorted universe of namespace cfg variables.

    Read from the impl package's cfg.toml, which the generator emits with every
    namespace variable. An override --cfg must list all of them.
    """
    source = package_dir.joinpath(*OVERRIDE_VARS_SOURCE)
    if not source.exists():
        fail(
            f"missing {'/'.join(OVERRIDE_VARS_SOURCE)} under {package_dir}. Regenerate "
            "windows_common with the current generator (scripts/regenerate_windows_common.py)."
        )
    names = parse_cfg_vars(source)
    if not names:
        fail(f"{source} declares no cfg variables; regenerate windows_common.")
    return sorted(set(names))


def build_override_cfg(enabled_namespaces: set[str], cfg_vars: list[str]) -> str:
    """Render the full ``--cfg="..."`` value: every variable, closure on, rest off."""
    enabled_vars = {namespace_to_cfg_var(ns) for ns in enabled_namespaces}
    pairs = ", ".join(
        f'{name}={"on" if name in enabled_vars else "off"}' for name in sorted(cfg_vars)
    )
    return f'--cfg="{pairs}"'


def build_override_compile_option(override_cfg: str) -> str:
    """Render the full ``override-compile-option = "..."`` cjpm.toml value."""
    # cjpm.toml is TOML: the value is a double-quoted string, and the embedded
    # --cfg="..." double quotes must be escaped as \".
    return override_cfg.replace('"', '\\"')


def write_override_to_cjpm(cjpm_path: Path, override_value: str) -> bool:
    """Idempotently set ``override-compile-option`` in the [package] table.

    Returns True if the file changed. Minimal line-oriented TOML edit (the repo's
    cjpm.toml files are flat key = value under section headers); avoids a TOML
    dependency and preserves formatting/comments.
    """
    if not cjpm_path.exists():
        fail(f"consumer cjpm.toml not found: {cjpm_path}")
    original = cjpm_path.read_text(encoding="utf-8")
    lines = original.splitlines(keepends=True)

    # The value is rendered as a TOML double-quoted string with escaped inner quotes.
    new_line_body = f'override-compile-option = "{override_value}"'

    # Detect indentation used in the [package] table by sampling an existing entry.
    package_start: int | None = None
    package_end = len(lines)
    for i, raw in enumerate(lines):
        stripped = raw.strip()
        if stripped == "[package]":
            package_start = i
            continue
        if package_start is not None and stripped.startswith("[") and stripped.endswith("]"):
            package_end = i
            break
    if package_start is None:
        fail(f"{cjpm_path} has no [package] table to host override-compile-option.")

    indent = "  "
    for raw in lines[package_start + 1 : package_end]:
        if raw.strip() and not raw.strip().startswith("#"):
            indent = raw[: len(raw) - len(raw.lstrip())] or ""
            break

    new_line = f"{indent}{new_line_body}\n"

    # Replace an existing override-compile-option line anywhere in the [package] table.
    for i in range(package_start + 1, package_end):
        if lines[i].strip().startswith("override-compile-option"):
            if lines[i] == new_line:
                return False
            lines[i] = new_line
            cjpm_path.write_text("".join(lines), encoding="utf-8")
            return True

    # Otherwise insert after the last non-blank line of the [package] table.
    insert_at = package_start + 1
    for i in range(package_start + 1, package_end):
        if lines[i].strip():
            insert_at = i + 1
    lines.insert(insert_at, new_line)
    cjpm_path.write_text("".join(lines), encoding="utf-8")
    return True


def find_cfg_tomls(package_dir: Path) -> list[Path]:
    paths = sorted(package_dir.rglob(CFG_TOML_NAME))
    paths = [p for p in paths if "target" not in p.relative_to(package_dir).parts]
    if not paths:
        fail(
            f"no {CFG_TOML_NAME} files found under {package_dir}. Regenerate windows_common "
            "with the current generator (scripts/regenerate_windows_common.py)."
        )
    return paths


def parse_cfg_vars(path: Path) -> list[str]:
    """Return the cfg variable names declared in a cfg.toml, preserving order."""
    names: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        key, sep, _ = stripped.partition("=")
        if not sep:
            continue
        names.append(key.strip())
    return names


def render_cfg_toml(cfg_vars: list[str], enabled_vars: set[str]) -> str:
    body = "".join(
        f'{name} = "{"on" if name in enabled_vars else "off"}"\n' for name in sorted(cfg_vars)
    )
    return GENERATED_HEADER + body


def rewrite_cfg_tomls(package_dir: Path, enabled_namespaces: set[str]) -> int:
    enabled_vars = {namespace_to_cfg_var(ns) for ns in enabled_namespaces}
    written = 0
    for path in find_cfg_tomls(package_dir):
        cfg_vars = parse_cfg_vars(path)
        if not cfg_vars:
            continue
        path.write_text(render_cfg_toml(cfg_vars, enabled_vars), encoding="utf-8")
        written += 1
    return written


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Select compiled windows_common namespaces via cfg.toml.")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--enable",
        metavar="NS[,NS...]",
        help="Comma-separated namespaces to enable (their transitive closure is added automatically).",
    )
    group.add_argument(
        "--all",
        action="store_true",
        help="Enable every namespace (compatibility / full regression build).",
    )
    group.add_argument(
        "--none",
        action="store_true",
        help="Disable every namespace (the opt-in baseline; impl compiles to nearly nothing).",
    )
    group.add_argument(
        "--emit-override",
        metavar="NS[,NS...]",
        help=(
            "Compute the transitive closure of these namespaces and emit the complete "
            "override-compile-option --cfg string (every namespace variable, closure on, "
            "rest off). Prints the string; combine with --write-override to install it. "
            "Does NOT touch windows_common cfg.toml."
        ),
    )
    parser.add_argument(
        "--write-override",
        metavar="CONSUMER_CJPM_TOML",
        type=Path,
        help=(
            "With --emit-override: write/update the override-compile-option field in the "
            "[package] table of this consumer cjpm.toml (idempotent)."
        ),
    )
    parser.add_argument(
        "--print-closure",
        action="store_true",
        help="Print the computed enabled-namespace closure and exit without rewriting cfg.toml files.",
    )
    parser.add_argument(
        "--package-dir",
        type=Path,
        default=DEFAULT_PACKAGE_DIR,
        help=f"Generated package directory containing {NAMESPACE_DEPS_NAME} and cfg.toml files (default: {DEFAULT_PACKAGE_DIR}).",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    package_dir = args.package_dir.resolve()
    deps = load_namespace_deps(package_dir)

    if args.write_override is not None and args.emit_override is None:
        fail("--write-override requires --emit-override.")

    if args.none:
        enabled = set()
    elif args.all:
        enabled = all_namespaces(deps)
    elif args.emit_override is not None:
        seeds = [s.strip() for s in args.emit_override.split(",") if s.strip()]
        if not seeds:
            fail("--emit-override requires at least one namespace")
        enabled = transitive_closure(seeds, deps)
    else:
        seeds = [s.strip() for s in args.enable.split(",") if s.strip()]
        if not seeds:
            fail("--enable requires at least one namespace")
        enabled = transitive_closure(seeds, deps)

    if args.emit_override is not None:
        cfg_vars = all_cfg_vars(package_dir)
        override_cfg = build_override_cfg(enabled, cfg_vars)
        override_value = build_override_compile_option(override_cfg)
        if args.print_closure:
            print(f"enabled namespaces ({len(enabled)}):")
            for ns in sorted(enabled):
                print(f"  {ns}")
        if args.write_override is not None:
            changed = write_override_to_cjpm(args.write_override.resolve(), override_value)
            state = "updated" if changed else "unchanged (already current)"
            print(
                f"OK: closure={len(enabled)} ns over {len(cfg_vars)} cfg vars; "
                f"override-compile-option {state} in {args.write_override}."
            )
        else:
            # Print the exact cjpm.toml line so it can be pasted directly.
            print(f'override-compile-option = "{override_value}"')
        return 0

    if args.print_closure:
        print(f"enabled namespaces ({len(enabled)}):")
        for ns in sorted(enabled):
            print(f"  {ns}")
        return 0

    written = rewrite_cfg_tomls(package_dir, enabled)
    print(
        f"OK: enabled {len(enabled)} namespace(s); rewrote {written} {CFG_TOML_NAME} file(s) under "
        f"{package_dir}."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
