[package]
  name = "windows_sys"
  version = "0.1.0"
  description = "Raw FFI bindings to Windows APIs for Cangjie"
  output-type = "static"
  cjc-version = "1.1.0"
  compile-option = "--cfg . -Woff unused --profile-compile-memory --profile-compile-time"

[dependencies]
  windows_result = { path = "../windows-result" }
  windows_interface = { path = "../windows-interface" }
  windows_polyfill = { path = "../windows-polyfill" }
