[package]
  name = "windows_result"
  version = "0.1.0"
  description = "Result and status-code primitives for Windows bindings in Cangjie"
  authors = ["Zxilly"]
  repository = "https://github.com/Zxilly/windows-cj"
  license = []
  output-type = "static"
  cjc-version = "1.1.0"
  compile-option = "-Woff unused"

[dependencies]
  windows_libloading = { path = "../windows_libloading" }

[profile.customized-option]
  slim = "--cfg=\"slim_errors = true\""
